### ISSUE TITLE
Ordering inherited  form controls

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1251]
Suppose, I have a form like this

   ```
public class UserMappingForm : AppUserForm
    {
        [Category("User Office")]
        [CssClass("hidden")]
        public List<UserOfficeRow> UserOffices { get; set; }

        [Category("User Project")]
        public List<int> UserProjects { get; set; }

    }
```

which is inherited from this form

```
public class AppUserForm
    {
        public String Username { get; set; }
        public String DisplayName { get; set; }
        public Int32? TenantId { get; set; }
       
    }
```

Now in dialog it shows the following order
1. UserOffices
2. UserProjects 
3. Username 
bla bla bla

I can order them using jQuery in dialog but I think there is a elegant way to do this.

Please give me your valuable hint to order them as follows
1. Username 
2. UserOffices
3. UserProjects 
bla bla bla

**Comment by volkanceylan** [comment]
Unfortunately, there is no simple way i know to do this. You might override getPropertyItems in dialog and do ordering client side. 

But i usually avoid inheritance in forms, because of this complexity, i simply define a new form if i need such. As most settings are in row, my forms are usually plain simple.

**Comment by dfaruque** [comment]
Ok. Thank you.
