### ISSUE TITLE
Support for Multi-Instance of App on a single Database

### ISSUE THREAD

**Issue by serenitydev** [volkanceylan/Serenity#1260]
Our application uses SQL Server 2008 and most of our customer databases (each customer has its own database) are pretty small. I'm trying to build a reporting application and would want to use customers connection string key based on their login credentials. How would this be possible in Serenity?

I have read the Multi-tenant example but that does not apply in my case as data for each customer is stored in specified database for the customer. However all databases reside on a single SQL Server instance.

Would you be able to help out or point me into right direction on how to accomplish above?

**Comment by Estrusco** [comment]
I have look around for the same task, for distribution on Azure. I have found these link. But as said Volkan this forum is out of scope for this. 

http://stackoverflow.com/questions/20488712/how-to-connect-multiple-database-with-single-application-in-asp-net

And

http://stackoverflow.com/questions/13094265/single-website-multiple-databases-database-switching

But I didn't test it, because isn't a priority.
