### ISSUE TITLE
datetime editor quickfilter

### ISSUE THREAD

**Issue by wimdevriendt** [volkanceylan/Serenity#1321]
i have a datetime column and want to have a datetimepicker in the quickfilter 
I only see a date picker how can i get a datetime picker ?
        [QuickFilter,DisplayFormat("dd/MM/yyyy HH:mm:ss"),DateTimeEditor(),Width(150)]
        public DateTime Timestamp { get; set; }

**Comment by volkanceylan** [comment]
See source of addDateFilter, you need to write similar one

**Comment by john20xdoe** [comment]
@volkanceylan 
related to this question (I also have a Date filter), in initializing a default value like 3 months from now for Date Start field. I have seen `InitialValuesForQuickFilters` grid sample. I want to improve it by using moment.js which is already in Serene instead of Javascript Date(). 

but how do I include it in Grid.ts so that I can use `moment()` functions?

**Comment by volkanceylan** [comment]
See a TypeScript guide please.
