### ISSUE TITLE
[Bug] Advanced Filter

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1545]
Dear @volkanceylan,
I think that there is an issue on the advanced filter:

![image](https://cloud.githubusercontent.com/assets/17425690/20754311/a39fe3ca-b70a-11e6-93ac-40d389dfc89f.png)

and this is the filter shown in the interface

    [Ship Via <> Federal Shipping and Ship Via <> United Package and (Customer contains 'alfreds' or Employee contains 'nancy' or Ship City contains 'berlin') and Ship Country = Germany]

As you can see the filter should exclude the "Ship Via" Federal Shipping and United Package, but instead I can found them in the result.
Also here there is the query that has been generated:

    SELECT count(*)  
    FROM [Orders] T0 
    LEFT JOIN [Customers] c ON (c.[CustomerID] = T0.[CustomerID]) 
    LEFT JOIN [Employees] e ON (e.[EmployeeID] = T0.[EmployeeID]) 
    LEFT JOIN [Shippers] via ON (via.[ShipperID] = T0.[ShipVia]) 
    WHERE ((((((((T0.[ShipVia] != @p1) AND (T0.[ShipVia] != @p2)) AND c.[CompanyName] LIKE @p3) OR CONCAT(e.[FirstName], CONCAT(' ', e.[LastName])) LIKE @p4) OR T0.[ShipCity] LIKE @p5)) AND ((T0.[ShipCountry] = @p6))))

It seems that the transposition of the query it's wrong: I mean the way the logical operators are nested.

Thank you very much
Bye

**Comment by sayuga** [comment]
I think it's more the syntax of the criteria. 

Your criteria essentially says: 

Filter Criteria 1
(((T0.[ShipVia] != @p1) AND (T0.[ShipVia] != @p2)) AND c.[CompanyName] LIKE @p3) 

Filter Criteria 2
 CONCAT(e.[FirstName], CONCAT(' ', e.[LastName])) LIKE @p4) 

Filter Criteria 3
((T0.[ShipCity] LIKE @p5)) AND ((T0.[ShipCountry] = @p6))

If any of the information matches any of the 3 criteria it gets displayed. Since the Federal Shipping and United Package have Items that match in Criteria 2 and 3, there are still items being displayed. 

The best way to notice this is by adding each filter criteria one by one and then looking at the result. Try adding the Ship Via Not Equal Federal Shipping and running it, then adding the United Package Exclusion. You should see the pattern as you go adding more filters.

**Comment by volkanceylan** [comment]
It looks like a bug to me, try adding full parenthesis and see if it changes anything.

**Comment by steax85** [comment]
hello we are also experiencing this issue, @volkanceylan I've tested your suggestions and if you try with "explicit" parenthesys it works as expected:

![working](https://cloud.githubusercontent.com/assets/19575101/20760975/c455809a-b721-11e6-8f84-39c013eb0e18.png)

the only think i've changed from @marcobisio 's example is "wrapping the first 2 conditions into parenthesys.

I guess there is something wrong with the translation from filter to sql, but i'm not an expert..

hope this helps

**Comment by volkanceylan** [comment]
It's a bug in javascript code of FilterPanel where it converts lines to criteria. There is no bug in server side. Will release with next version.

**Comment by steax85** [comment]
great news! thanks a lot for your efforts

**Comment by marcobisio** [comment]
Thanks @volkanceylan and @steax85 for your feedbacks!

**Comment by marcobisio** [comment]
Just realized that you have already released the next version, which include also this fix: wow too fast!
Thank you very much for your support Volkan!
Bye
