### ISSUE TITLE
Product list difference between PDF and XLS

### ISSUE THREAD

**Issue by chizdamasii** [volkanceylan/Serenity#1559]
When i try to list in PDF Product, the Supplier and Category Column show the id integer, in Excel it shows the string value. How can it be fixed in PDF so it can show the string value?

**Comment by stixoffire** [comment]
@chizdamasii Is your grid showing ID fields or is it showing a formatted value ?

**Comment by chizdamasii** [comment]
**I am using as a reference: http://serenity.is/demo/Northwind/Product. If you click on the PDF export it doesnt show the supplier or category, only their id, although in the excel export file it shows correctly.**

**Comment by stixoffire** [comment]
@chizdamasii  the columns are being filtered out is why, they are not filtered in the excel helper.
Navigate in your solution to common > reporting > PdfExportHelper.ts

In the code file look for the method exportToPdf(options) {}

In that method you will find this 

```
            var gridColumns = g.slickGrid.getColumns();
            gridColumns = gridColumns.filter(x => x.id !== "__select__");
```
after this comes code to actually manipulate the data and the follwoing method is where the issue seems to be:

> toAutoTableData() 

You will need to look at this line 
```
                    if (src.formatter) {
                        html = src.formatter(row, cell, item[fld], src, item);
```
The item and  item[Fld] are the values you are interested in - you are getting the Id in that parameter instead of the referenced column - I have spent a few hours looking at it - and so far I am at a loss.

 this link should give at least some help:
[https://github.com/mleibman/SlickGrid/wiki/Column-Options](https://github.com/mleibman/SlickGrid/wiki/Column-Options)

**Comment by chizdamasii** [comment]
After some digging, i found the culprit: in ProductGrid.ts remove the

`        protected getColumns(): Slick.Column[] {....}`

and it will list the pdf normally. This means, of course disabling the in grid editor. Maybe someone will find a better fix.

**Comment by stixoffire** [comment]
Maybe in your button for PDF - on click event you can disable the in grid editor and then re-enable it after the print. I know not the best , your print pdf also has those referenced columns from the ts (you might be able to rewrite that to handle there.

**Comment by volkanceylan** [comment]
PDF export tries to use your formatter defined client side. That's a rare case where there is a select in a column. So it uses its value like an input. It should actually take the text. Maybe i'll have a look laters.
