### ISSUE TITLE
Why My Issue IS Closed??

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#1610]
Serenity is an open source software. Open source doesn't always mean free to use, but Serenity with its MIT licence is one of them that are **free to use and modify**.

This doesn't mean it's **with unlimited free support**. No one can offer such a thing, even commercial ones. When you buy Windows, which is not free, you don't get unlimited free support from Microsoft. When you have a problem with your Windows PC, you either try to fix it yourself, or get help from a friend or your local PC technician.

I spent thousands of hours, maybe more to develop Serenity, write guide, faq, how to and samples for it. Yes, there might be some areas it is lacking but no documentation can be complete. Anyway, i did my homework and trying to do better every other day, offering you this platform with so much hardwork for free (to use).

We have about 2000 questions here and in VS Gallery. If we categorize them, we'll see that most of them are not even related to Serenity. 

Some people expect to get help on programming basics, how to write a delegate, how to add an attribute, how to publish an application to IIS, setting application pool to integrated, general TypeScript help etc. This is not the place for this questions. There is StackOverflow for that, and even before using that site, you should take your time and read their relevant guides.

Some issues are reported simply with **not working**. Serenity tries to make it easier to develop business applications. But it is still a platform for **developers**, not end users. Developers should have some fundementals, like how to **report properly**, unlike an end user. Your report should include details like environment, version, stack trace, what you were trying to do, when it started to fail, what changes you did etc. Some of these users find it *rude* when i answer unpolitely or close issue right away. Believe me its not rude, it's **fair**. I don't have to waste time for person who doesn't show respect for my right to preserve my spare time.

Most of questions are already answered in *faq*, *guide*, *samples* and *prior issues in GitHub*. Yes, i understand you may not always find them easily, but i feel like some people are trying to use me like *Google*, which is run by machines, while i am not.

Believe me only %5, or even less of issues so far are real issues. 

There might be times when i lose my temper, misunderstand the issue and answer unpolitely. I apologize for that.

So please, before opening an issue finish this check list:

[ ] Read the tutorials
[ ] Check how-to section in guide
[ ] See WIKI topics
[ ] Search prior issues in GitHub
[ ] See samples under Basic Samples in Serenity
[ ] Have a look around in Northwind and other modules
[ ] Report properly with details

**Comment by williamhodges** [comment]
I took the time to Wiki-fy this posting with some guidelines on issue reporting.

[Wiki article](https://github.com/volkanceylan/Serenity/wiki/Issue-Guidelines)

**Comment by dfaruque** [comment]
You are correct @volkanceylan . 
I have also notice that.

**Comment by DucThanhNguyen** [comment]
As a software developer, I prefer to learn from the code and add pull requests instead of posting questions

**Comment by marcobisio** [comment]
You're right Volkan and sometime in the past I've done the same mistake, but trust me sometimes there are problems that are misunderstood simply because we all have different backgrounds: what for you is clearly a false positive, may not be so for others (myself included) just because we do not have all your programming skills and above all do not know so thoroughly Serenity (at least not as much as you).
Say that, I'm sorry you wasted time with my false issues and I apologize for that...I hope at least to have "repaid" your effort (just a bit) by sharing with the community some of my implementations!

Have a nice day!
Bye

**Comment by volkanceylan** [comment]
@marcobisio this wasn't meant for you or any commenter here.

**Comment by marcobisio** [comment]
I know Volkan, but I think that if you opened this issue is also to have our feedbacks here and last but not least, I can recognize when I'm wrong (albeit in good faith)! ;-)

**Comment by jmace** [comment]
Do not feel like you have to answer every question. This process also helps build the community knowledge for others who stumble onto Serenity and have the same non-serene questions. Let your community grow. 

Once I find myself up to speed, I plan on being around to contribute often. It may serve to add a link or two to resources for getting up to speed on MVC, Entity framework, etc...

**Comment by john20xdoe** [comment]
> _Some people expect to get help on programming basics, how to write a delegate, how to add an attribute, how to publish an application to IIS, setting application pool to integrated, general TypeScript help etc. This is not the place for this questions._ 

_I'm guilty on this =)._

Back on topic:
I added the link of wikified article by @williamhodges to the Home Page. =)

**Comment by mhussein67** [comment]
I have spent a lot of time to understand the concepts on serenity platform development, and now I've covered most of the features and the functions in additional to building a full applications for my work in students admission and registration. 
The mean issue I was facing is because I'm using Oracle as a backend and I have to codes most of the screens manually without using sergin At the beginning I've asked a lot of silly questions:( but now I can answer questions:) however I'm still stuck with some issues related to serenity core such as: Define multiple idField to the row definition, Oracle stored procedure grid, but there are always  workaround to solve these issues:)

Thanks  @volkanceylan
