### ISSUE TITLE
Chat Implementation

### ISSUE THREAD

**Issue by mcb2323** [volkanceylan/Serenity#1703]
Has anyone implemented any third party chat modules within Serenity?  Wanted to know which packages played well with the framework before I dove into it.

Thanks

**Comment by VictorTomaili** [comment]
I prefer third party chat service instead of modules. Like HappyFoxChat or Intercom.

**Comment by sayuga** [comment]
I'm a personal fan of Slack. The documentation is pretty straight forward and it's pretty well used in team environments. On the other hand you could simply take the AdminLTE sample and add a table to log it. I assume you could use a approach similar to tenancy for private messaging vrs public chat. In essence it's a matter of using the chat box instead of the Grid to display the data. 

I'll play around with it and let you guys know what I find. 

Slack: https://api.slack.com/custom-integrations

**Comment by ms4hafiz** [comment]
Hi @sayuga;

Did you have the chance to implement the chat and any experience to share with us please.
