### ISSUE TITLE
Need help with TreeGridMixin

### ISSUE THREAD

**Issue by mhussein67** [volkanceylan/Serenity#1712]
I've a table with DeptCode and a list of Courses for each Dept, I want to show the gird as tree, so I'he add the below code, but it shows nothing on the grid (blank) if I remove it the grid show the data.

What is wrong? 

```
private treeMixin: Serenity.TreeGridMixin<Schedule.ScheduleRow>;

        constructor(container: JQuery) {
            super(container);
            this.treeMixin = new Serenity.TreeGridMixin({
                grid: this,
                getParentId: x => x.COURSE_CRN,
                toggleField: ScheduleRow.Fields.DEPT_CODE,
                initialCollapse: () => true
            });
        }
```

**Comment by stixoffire** [comment]
@mhussein67 - I think if you just set it on your object rather than setting your object to a new  this.treeMixin = new Serenity.TreeGridMixin({ - you will see the result you want. I think I had this with a different object - not the treeMixin .

Look here    How to implement TreeView by SlickGrid in Serenity #1394

**Comment by volkanceylan** [comment]
First place you should look is browser console...

**Comment by stixoffire** [comment]
@mhussein67 as volkanceylan said - F12 in IE will allow you to see what is happening.
