### ISSUE TITLE
Serenity Calendar bug

### ISSUE THREAD

**Issue by brunobola** [volkanceylan/Serenity#1724]
The sample Calendar as a BUG when using jquery 3, the events aren't created at the calendar and the console gives: 

Uncaught TypeError: elem.getClientRects is not a function

![image](https://cloud.githubusercontent.com/assets/10889019/21598678/bed52e44-d158-11e6-92cf-7e1ca935d918.png)

**Comment by sayuga** [comment]
See issue #1555. I worked on this a bit and ran into the same problem. jQuery 3 doesn't play nice with our current model but the full calendar can take multiple forms of data entry so it can probably be manipulated by using it as a replacement to the grid and using dialogs to enter and edit the data. I put some sample in the posts for the issue that you are welcome to look into. 

From what my research had panned out, I believe it's a matter of implementing the jquery-migrate to allow for a better interaction of the older jQuery functionality which is in place with full calendar and the JQuery 3 which we currently use

**Comment by sayuga** [comment]
I was reviewing the general notes I had and went to troll the fullcalendar github repository and it appears they should have JQuery 3 support since V 2.8.0 (https://github.com/fullcalendar/fullcalendar/releases/tag/v2.8.0). 

The Full Calendar version in the samples is 2.2.5. I do know, though, that I wasn't able to figure out a fix after updating the package to FullCalendar 3.1.0 but my JQuery knowledge is somewhat limited.
