### ISSUE TITLE
Generate Lookup problem

### ISSUE THREAD

**Issue by euclidesgc** [volkanceylan/Serenity#1807]
The "Generate Lookup" option in "Generation Options" of sergen.exe only works if you select the "Row Fields Surround with Region" option.
Does anyone know where we can fix this problem?

![image](https://cloud.githubusercontent.com/assets/12780402/21948200/b337657c-d9d0-11e6-8fb8-18d04352b976.png)

**Comment by dfaruque** [comment]
you are right. there is no such option to generate lookup with standard row template.
may be this feature is something that @volkanceylan  does not like personally. So he does not include it in standard row template. Or @rolembergfilho  who added this feature is ignore that.

**Comment by stixoffire** [comment]
Look in the serenity code generator code here https://github.com/volkanceylan/Serenity/blob/master/Serenity.CodeGenerator/Views/EntityRow.generated.cs line 94 .. but here is th eline you need to look at and it comes from the Model 
I think when I looked in the GenerateRowModel code I saw something like this endswith(" Id") note the space but I was perusing quickly and did not exam closely 

In the views of the code generator look at RowWithRegion Generated under the views  versus Row without region

**Comment by rolembergfilho** [comment]
After a long time....
@stixoffire: I decided to put only on "Row Fields Surround with Region" option in order to maintain @volkanceylan as original "pure" implementation.

Nowadays the "Row Fields Surround with Region" option is more a place to do new things without disturbing original Volkan implementation.

@volkanceylan: would you like to merge both generation in one? or maintain both separate like now?
