### ISSUE TITLE
Proper Location of common fields.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#191]
In my Database, All tables have some common fields (like ID,CreatedOn,CreatedBy etc.)
I want to put these common fields in a base class.
What is your recommendation?

[Should I modify Row.cs? or create a new class derived from Row then use it as base class of all rows]

**Comment by VictorTomaili** [comment]
I will prefer ignore. Also if you want to use polymorphism you need handle it yourself. I prefer create an interface for this.

**Comment by ademc** [comment]
There is an example about this on Users Table- userRow.
Users table contains İnsertUsertİd, İnsertDate, UpdateUserİd, UpdateDate
LoggingRow handle this fields.
UserRow class inherits LoggingRow instead of Row and UserRowFields inherits LoghingRowFields instead of FieldsBase

This methods is very usefull for managing audit log. You can add same behaviur leki this with own fileds

**Comment by volkanceylan** [comment]
Make sure you use a base class, similar to LoggingRow, and use same field names everyware, it's easier to manage
