### ISSUE TITLE
Serenity Premium Support Packages are Available

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#1912]
Hello Serenity Community,

As requested by some users, premium support packages with annual subscription are available at http://serenity.is.

Serenity itself as a platform is a free and open source project, and will stay so. These are just options for those who require support beyond basic help that is offered here in GitHub, by me and community.

By purchasing one of these packages, you'll be getting direct support through e-mail over support@serenity.is address. You may ask questions about Serenity itself, integration with some other products, architecture guidance, troubleshooting, help on basic widget development, request a feature to be added to Serenity etc. There is a limit on monthly support incidents, but this limit will be relaxed initially.

You'll have access to private repositories in GitHub with premium samples and prioritized issues.

Premium subscriptions also include "live credits" which are hours that you can use for remote support, troubleshooting, screen sharing, live guidance over Skype, custom development etc. This kind of live support has long been available and so far we had good experiences.

I'm on the verge of leaving my job to focus solely on Serenity, and make it shine as a platform. Wish me luck, thanks.

PS. If you have any question or suggestion about these premium support offers, please let me know.

**Comment by uwascan** [comment]
Wishing you the best. I will look into these premium support offers.

**Comment by Estrusco** [comment]
Great

**Comment by sayuga** [comment]
Good luck. Looking at the strong uptake that Serenity has had and how wonderfully it's been received, I expect you to become a very very busy man

**Comment by javaman63** [comment]
Good Luck! You deserve it

**Comment by dfaruque** [comment]
Good Luck.

**Comment by mahmuthaktan** [comment]
Serenity is going to be best framework for .Net

**Comment by BrMail** [comment]
You accomplish a lot to now!
 with full commitment the results will be even greatest!!! 
:-)

**Comment by john20xdoe** [comment]
Is it also possible for community members to join as part of support team? like paid support associate or some sort that can be part-time or fulltime. 😁

**Comment by volkanceylan** [comment]
Not yet but you can count yourself first on list :)

**Comment by jmptrader** [comment]
What are the Premium Samples?  Please you can provides more detail.

**Comment by volkanceylan** [comment]
There is a background task system and a batch mail service sample using it initially. I'm planning to add more samples / modules in following weeks, including task management, e-commerce, integration with third party tools like VueJS, React etc.

**Comment by marcobisio** [comment]
Good luck! I'am available to give you (free) hand as a potential member of the support team ;-)
Bye

**Comment by uwascan** [comment]
+1 for more samples / modules in following weeks, including task management, e-commerce, integration with third party tools like VueJS, React etc.

**Comment by SpiraMira** [comment]
Fantastic!  I've been waiting for this to happen, coz frankly this is a great framework for quickly launching business apps.  And, believe me, I've looked at many competent others.  It's more than paid for itself in my budding consulting practice.  Plus the new direction supporting .net core plugs the last few gaps I was (a little) worried about. This ensures long term cross-platform viability (even though we all agree that core still has a little ways to go).  

I am about to pull the trigger on a personal license (pro or enterprise may not be too far away if my client list grows) , but I just want a sniff sense of the samples you will provide and when: the roadmap? I ask only because I've been customizing my Serenity based architecture with Hangfire + SignalR support for background and notification services and looking into integrating external batch e-mail services (like SendGrid) just because that dimension is still missing from the publicly available version.  Should I continue (and possibly share) or scrap it if you have Serenity compatible modules for these services? This would be great. Task management, e-commerce, VueJS and React - just icing on the cake!

Best of luck in your new venture. You deserve it.

Regards Patrice

**Comment by fzhenmei** [comment]
Good luck.

**Comment by VR-Architect** [comment]
Signing up for personal license now. Good luck on your venture.

**Comment by ms4hafiz** [comment]
Good luck. I should sign up soon.
