### ISSUE TITLE
MasterDetailRelation

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#1958]
I'm looking more closely at MasterDetailRelation and how it creates its own handlers on the fly for the detail items. I get why that's needed (no existing way to correlate a given handler with a rowtype) but that means it both bypasses any logic in the row's repository/handler and prevents MDR-specific custom handler logic.

Any chance this topic could be revisited? Right now the only way to consolidate any logic would be using a database trigger which is not ideal. I can think of a couple ways of accomplishing it...maybe searching for a public xHandler<DetailRow> within the assembly and instantiating that, or adding a parameter passed to the MDR attribute for the name of the class(es) to instantiate at runtime?

**Comment by volkanceylan** [comment]
Yes, behaviors can't call repositories, but they call other behaviors defined for other row types. So as long as you write your custom handlers, e.g. triggers at behavior level, they will be called.

I would consider locating repositories / handlers for a given row type, but that is not a trivial thing. One row might have multiple repositories, multiple save handlers and even if it is just one type, there might be other problematic cases.

Another similar issue is about forms. Anything you write on a Form.cs is not validated at repository level. It only works if you use them on Row.

I'll revisit these sooner or later, but for now its blurry. I recommend staying in behavior world, instead of customizing at repository level.

**Comment by wldkrd1** [comment]
Ahh, so (for example) create a custom SaveBehavior that inherits from BaseSaveBehavior and apply that to my DetailRow?

**Comment by wldkrd1** [comment]
Or rather...inheriting from SaveRequestBehaviorAttribute and apply that attribute to DetailRow
