### ISSUE TITLE
InplaceAdd used issue

### ISSUE THREAD

**Issue by cp1319421** [volkanceylan/Serenity#1981]
when i use the lookupeditor, enable inplaceadd, but when click the create new button it show a edit dialog, how can i do this?
![default](https://cloud.githubusercontent.com/assets/19610257/23207719/39a4190e-f92d-11e6-8f63-9a3ff47c7e4e.PNG)

**Comment by sayuga** [comment]
Inplace add opens the edit dialog for the linked table. If you happen to have something selected in the field before you click the button you'd end up with the edit dialog for that item. This is by design. What are you trying to do?

**Comment by cp1319421** [comment]
@sayuga, as the picture show, wo had not do any selected before i click the button, and my code as below
[DisplayName("Product"), Column("ProductID"), Size(20), NotNull, ForeignKey("[dbo].[ProductInfo]", "ProductNumber"), LeftJoin("jProduct"), TextualField("ProductPcbpn"), LookupInclude]
        [LookupEditor(typeof(ProductInfoRow), InplaceAdd = true)]
        public String ProductId
        {
            get { return Fields.ProductId[this]; }
            set { Fields.ProductId[this] = value; }
        }

**Comment by sayuga** [comment]
is ProductNumber the Id(key) field for the Product Info table? Your foreign key should be the Id field for the matched table. Otherwise, if Product Number field in the Product Info table happens to allow nulls, you'll end up opening the row entry with a "null" value on the product table thus you'd be editing that row. 

Think of linking in this set of steps.:
*Assuming Table A has the form you are working on and  Table B is the table you are linking to. 

-First add a single row to Table A to hold the IdField for Table B [Example: linkedTableBId]. This Id field holds the key field value for the matched table. 
-Add the foreign key and left joint [Example: Foreignkey(typeof(TableBrow), "tableBId"), LeftJoin("tblB")
-Now you can use the LeftJoin value to map the linked fields to your current form using the Expression() attribute. [Example: Expression("tblB.someField")]
-Note that you are technically filtering and adding/editing the the joint table per the Id field. The information you display in the LookupEditor Combobox is the field you designated in the INameRow.NameField on the TableBRow.cs. 
-left join expressions are used to display the information matching the key identifier that is linked. 

A good way to think about it is that the 'person' is the Id and the clothes are the other fields. When you want to talk to the 'person', you always talk to the 'person' but you only look at the 'clothes' because the clothes may change but the person doesn't 

Looking at what you have you don't seem to be matching to the Id Field of the ProductInfo Table. The Northwind OrderRow.cs has a good couple samples of joint fields. Take a look there and you'll see some usable examples.
