### ISSUE TITLE
How to catch dialog event before occuring dialog in xxx.ts

### ISSUE THREAD

**Issue by harrypassport** [volkanceylan/Serenity#2005]
Dear community,

Here I use the below scripts in xxx.ts: 
var dlg = new DWellDialog(opt0).dialogOpen();

I want to catch certain event just before the dialog completely opened. Just like to use beforeSend function in async service as below:
 
xxx.service( {option},
      response => { ...} 
     , {
         async: true,
         beforeSend: function () {
         $('#rptprocess').css({ display: "block" });
         });

Thanks,
Harry

**Comment by Estrusco** [comment]
You can override in xyzDialog.ts  some method before dialog is open (see in EntityDialog), and also in the constructor you can set your function to specific event.

What do you want to achieve?

**Comment by harrypassport** [comment]
Thanks @Estrusco for your comments.

I want to open a dialog yyyyDialog.ts in another xxxxGird.ts's constructor.  So I can not override some method in the specific yyyyDialog.ts(such as onOpenDialog()). 

If need longer time to open yyyyDialog, the page will stay xxxxGrid page a long time, so it's not better for user to just wait.

I means if there is any event to be caught before open a dialog. If so, I can put some progress bar in it and let user to feel well.


Thanks to get your help
Harry

**Comment by harrypassport** [comment]
Can anyone comment that. It's appreciated to get your help.
Harry

**Comment by edson** [comment]
I'm afraid it does not have... It should work in onOpenDialog() or you could put in dialog's constructor but
maybe your issue is with slickgrid + dialog template (re)rendering browser issues... It freezes UI and  breaks the async feeling if you have too much things loading in it (it renders, apply styles, loads data, rerender again, apply styles, so on)... Simple usecase data renders fast though... 

If you don't see pace loading or if is kinda freezing... that's the case... It is more noticeable in firefox...

You could put Q.blockUI("blabla") when row is clicked and setTimeout to call dialogOpen so the message is rendered, shown and not frozen by browser rendering consuming time... 



Best Regards

**Comment by harrypassport** [comment]
Many Thanks @edson for your explaination
Harry

**Comment by harrypassport** [comment]
Thanks @Estrusco 
I build an empty service from server side without doing anything, which can be called with "async: true"  That can implement what I expected.

Harry
