### ISSUE TITLE
Will work with DatabaseViews

### ISSUE THREAD

**Issue by DanielBasler** [volkanceylan/Serenity#2009]
We would like to see views from the database as a grid (also Databaseviews…)
We generate the code with the Serenity Code Generator and the Grid is Empty…
What are we doing wrong? With tables from the database everything works perfectly!!!
Can you give me a tip or help us.
Thank you for your quick response

**Comment by volkanceylan** [comment]
Set your identity field in Row.cs

**Comment by jmace** [comment]
To add some detail to what Volkan has said,

1)	Go into the xxxxxRow.cs file… you will have an error in the lines like below
IIdField IIdRow.IdField
        	{
            		get { return Fields.; }
       }
Modify so that Fields.xxxxxx;   defines your ID field
2)	Go into the xxxxxxGrid.ts file and add the identity refrence to the typescript
protected getIdProperty() { return xxxxxxxxxRow.idProperty; }

Rebuild, should see data now.

**Comment by DanielBasler** [comment]
Thank you. There was still the entry getIdProperty () in the TypeScript file :-))
