### ISSUE TITLE
 how can i use CustomImageUploadBehavior after creating it

### ISSUE THREAD

**Issue by zasZakareia** [volkanceylan/Serenity#2036]
I read the issues #207 but i don't know how can i use CustomImageUploadBehavior after creating it, i tried to solve my problem by adding byte[] column to database and define a row with ByteArrayField, i added some code to SaveResponse method in ServiceEndpoint to set value to this feild before saving it's working and save image to database but this not my desire which i want to change imageupload behavior to save image of file to database directly without saving file to folder or saving URL to database.

My main problem is how can i use the CustomImageUploadBehavior class after creating it?

**Comment by volkanceylan** [comment]
See multi tenant behavior on how it works

**Comment by JohnRanger** [comment]
Good evening @volkanceylan ,

I have studied Issue #207 as well as your documentation in the Serenity guide on the multi-tenant behavior. I think that I generally have understood how it is applied in the case of the Multi-Tenancy - but I really don't understand how to translate this into the case of the customFileUploadBehavior.

So far I have created the customFileUploadBehavior according to what I think I would need:

```cs
public class CustomFileUploadBehavior : ImageUploadBehavior
    {
        
        public byte[] FileData { get; set; }

        public string newFilename { get; set; }
        public string path { get; set; }

        public string TempFolder { get; set; }

        public override void OnBeforeSave(ISaveRequestHandler handler)
        {
            base.OnBeforeSave(handler);
            var filename = (StringField)(Target);
            newFilename = filename[handler.Row] = filename[handler.Row].TrimToNull();
            if (newFilename == null)
                return;
            path = UploadHelper.DbFilePath(UploadHelper.ToPath(newFilename));

            string[] esetse = UploadHelper.GetThumbFileName(newFilename).Split('\\');

            TempFolder = UploadHelper.TemporaryPath;
            FileData = File.ReadAllBytes(path);
        }

        public override void OnAfterSave(ISaveRequestHandler handler)
        {
            base.OnAfterSave(handler);
            new SqlUpdate(handler.Row.Table)
                .Set("JRXML", ((newFilename == null) ? new byte[0] : FileData))
                .WhereEqual((Field)((IIdRow)handler.Row).IdField, ((IIdRow)handler.Row).IdField[handler.Row].Value)
                .Execute(handler.UnitOfWork.Connection);

            File.Delete(path);
            //File.Delete(ThumbFilePath);
            DirectoryInfo di = new DirectoryInfo(TempFolder);

            foreach (FileInfo file in di.GetFiles())
            {
                file.Delete();
            }
        }

    }
```

(most code above comes from #207).

But what I don't find out is how to define the interface for it (if it is at all needed - in the case of the Multi-Tenancy it makes sense) and where to "attach" it (and why).

As you refer in different issues to the fact that you have already implemented such a custom file upload behavior to sharepoint (but it is proprietary code), it would be very kind if you could just share the "skeleton" of how to use a custom File upload behavior if someone has developed one - with a few words.

(Where and how to "attach" the customFileUpload behavior so that the code within the customFileUploadBehavior is used instead of the code within ImageUploadBehavior).

Thank you for your feedback and

with kind regards,

John

**Comment by softsolutions** [comment]
You need to implement IImplicitBehavior interface in your behavior

public bool ActivateFor(Row row)
        {
            if (ReferenceEquals(null, Target))
                return false;

            var attr = Target.GetAttribute<ImageUploadEditorAttribute>();
            if (attr == null)
                return false;

            if (!(row is IIdRow))
                throw new ArgumentException(String.Format(
                    "Field '{0}' on row type '{1}' has a ImageUploadEditor attribute but Row type doesn't implement IIdRow!",
                        Target.PropertyName ?? Target.Name, row.GetType().FullName));

            return true;
        }
