### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by rebuscao** [volkanceylan/Serenity#2051]
Hello,

I have developed an application using the framework, everything works fine except when I access the web page througth the Citrix Secure Web browser from an IOS device.

The problem is when calling for example 
`Q.serviceRequest(..., ..., ...);`

sometimes specially if i use 3G I got and error popup

![imagen](https://cloud.githubusercontent.com/assets/537756/23939408/c6330ed2-0960-11e7-9608-5b815017b6ec.png)

saying only "undefined".

Is there a way to ask Serenity when is ready to process the service requests?

Any help will be appreciated

Thanks.

**Comment by volkanceylan** [comment]
Unfortunately XHR (ajax) requests doesn't give any error text when a connection error like CONNECTION_REFUSED or CONNECTION_RESET occurs. That's why you see "undefined" as there is no message to show. This is a limitation with XHR itself. I tried to give a more descriptive message in latest commit, but it will always be limited.
