### ISSUE TITLE
Once again : .Net Core DynamicScriptMiddleware - exception : Headers are read-only, response has already started.

### ISSUE THREAD

**Issue by TomaszKustra** [volkanceylan/Serenity#2078]
Steps to reproduce:
1. Clone Serene repository from github.
2. Open in Visual Studio Serene.Core.sln
3. Set startup project to Serene.Core
4. Set server to Kestrel (not IISExpress)
5. Start Serene.Core (Debug or Release).
6. Open in Edge/Chrome http://localhost:5000
7. Login to serene
8. Press F12 to open Develeopr Tools in Edge or Chome
9. In dotnet window you'll see the log with exception.

![sereityexception](https://cloud.githubusercontent.com/assets/4504375/24174200/c0c062ea-0e8f-11e7-85cc-d3bf99ad73a9.JPG)

[http://stackoverflow.com/questions/37918547/middleware-to-set-response-contenttype](http://stackoverflow.com/questions/37918547/middleware-to-set-response-contenttype)

**Comment by volkanceylan** [comment]
That stack overflow answer is meaningless here. These errors are not that important, and is simply ignored as it just happens when Chrome tries to load a ".map" file that doesn't exist from DynamicScriptMiddleware. You can see in your screenshot that it is a request to a "toastr.js.map" file that doesn't exist there. Anyway see my latest commit in Serenity that fixes this.
