### ISSUE TITLE
build halted at new TaskExecutor(runner).Execute(); with .NET Framework 4.5.1 

### ISSUE THREAD

**Issue by thesnide1** [volkanceylan/Serenity#228]
I was exploring the "Serenity Application Template" with good results using Visual Studio  2013 Professional on Windows 10. At some point I switched from .NET Framework 4.5 to 4.5.1 and was unable to build the project. 

During the build a file dialog appeared asking for a file called GenericProcessorBase.cs. Upon canceling the file dialog the build halted at 'new TaskExecutor(runner).Execute();` with an error like: 
"System.Data.SqlClient.SqlException was unhandled by user code.....  Message=Cannot open database "Serene2_Default_v1" requested by the login. The login failed........"  It is clear to me that this error was because the Default database was not being generated. 

Once I switched back to >NET Framework 4.5 everything worked as expected.

There are "Known issues for the .NET Framework 4.5.1" that may be related.
[https://support.microsoft.com/en-us/kb/2890857](url)

Nice template. Thank you.

**Comment by volkanceylan** [comment]
I did a quick test with VS2015 and switching Serene.Web to .NET 4.5.1, but didn't have this issue. It might be a problem with SQL local db. Yesterday it stopped working without a reason, and i had to reinstall it.

**Comment by thesnide1** [comment]
The problem is unrelated to the .NET Framework version.  After getting my  system rights (temporarily) elevate to administrator   I was able to rebuild some of my system.  I am able to repeatedly create new projects using the Serene template without a problem. Those projects that had failed as described above still cannot be built. I have tried cleaning/rebuilding and updating the packages. I suspect I need more experience with the IDE to figure this out  myself. Do you have any ideas?

**Comment by volkanceylan** [comment]
I don't have any other ideas unfortunately.

**Comment by klaidez** [comment]
I had this problem. I think that it is not related to the .NET version.
I guess you were doing experiments, hence the database name "Serene2_Default_v1". 
If you create a project named Serene2, then delete the folder, and create another project with the name Serene2, you will get this error, because, the LocalDB instance still has the first Serene2_Default_v1 attached.
you need to delete the database too.
Using SQL Management Studio, connect to (LocalDB)\MSSQLLocalDB with windows auth, and delete the offending DB.

**Comment by SyndicateOfSwing** [comment]
I encountered the exact same issue.
