### ISSUE TITLE
Attach Login Username as Default Value for the form fireld

### ISSUE THREAD

**Issue by questionmaker** [volkanceylan/Serenity#2354]
I have a table with multiple columns
there is a column name Created By and it has to get the default value as logged in Username.
how can I retrieve the logged in username as a default value in the column field and it needs to be updatable(false) as well.
I tried this code and it seems not suitable or logically not connected
DefaultValue(Serenity.Authorization.Username)

**Comment by sayuga** [comment]
Look at the MultiTenancy sample. there are a few examples there as to how to grab the active user information and then manipulate it. Hint: you care most for UserDefinition

https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/multi_tenancy/filtering_users_by_tenantid.html

**Comment by gguadalupe** [comment]
Everything you need is in the examples @sayuga is talking about. There is so much info you can build a time machine... true story.

Based on the multi tenancy example, I did the following and is working.
In the form I don't ask for the User (or the Quote Date), I take care of that behind doors, because I don't want the user to touch it.

```
        private class MySaveHandler : SaveRequestHandler<MyRow> {
            protected override void SetInternalFields()
            {
                base.SetInternalFields();

                if (IsCreate)
                {
                    Row.UserId = Authorization.UserId.TryParseID32();
                    Row.QuoteDate = DateTime.Today;
                }
            }
        }

```
Warning! I'm not sure about the TryParseID32. Maybe is another, better, way of doing the same.

Hope this helps. (Read the guide!!)

**Comment by amonragz** [comment]
Hi Questionmaker,

I'm needing to make the same you asked in this issue, so just one question have you applied right code to retrieve Default Username in Form.cs or how was your approach applied to your solution?

**Comment by dfaruque** [comment]
implementing `IInsertLogRow` might be the solution

**Comment by alak447** [comment]
Thank you dfaruque Vhia
