### ISSUE TITLE
InPlaceAdd (set default value from previous screen)

### ISSUE THREAD

**Issue by mustafalotiya** [volkanceylan/Serenity#2385]
Dear Serenity members,

Query is regarding InPlaceAdd Button.

When user clicks new button next to lookup editor (Inplaceadd=True), Can we set defaults value in field to new windows from previous window (Value from previous window from which Add Button clicked)?

Thanks in advance.
Mustufa

**Comment by JohnRanger** [comment]
Hi @mustafalotiya ,

I don't understand exactly, what is your Situation. In order to help, please clarify your question.

(1) What is your 1st "Window"? (a grid?)
(2) what are the "fields" whose values you want to Transport over to the next "window"?
(3) What is the "next window"? (the Form Dialog?)

With Kind regards,

John
