### ISSUE TITLE
Bio-metric Integration

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#2448]
Hi
I want to Integrate a Bio-Metric device to my serenity project and am entirely new to this platform can you please provide me with an example or the procedure for the Integration of the Bio-metric. Am having the SDK available with me for Nitgen eNBioScan-C1 device. And how to get the quick filter field name to the title of the pdf exporter.

Thank you

**Comment by JohnRanger** [comment]
Hi Srinivas1910,

I quickly have looked at this device. This is not a HID device (something that emulates a Keyboard) - therefore the Integration of such a device is a hard Task.

On a very high Level, you have to do the following:

As the Serenity Framework is basically a Website, you have to develop a wrapper application (for the OS platform you want to run your app on) which embeds a Serenity-compatible web browser and you have to do the authentication part within this wrapper application and then transmit the required data to the embedded browser into the serenity Framework..

From my Point of view this is not a Serenity question but a question of how to integrate your Fingerprint device with any Website.

@Volkan: Please correct me if I am wrong.

With Kind regards,

John

**Comment by vinaykulkarni89** [comment]
@JohnRanger true, or even you can write application on PC which will push data from device to DB on server and then you can manipulate data in web application

**Comment by srinivas1910** [comment]
@vinaykulkarni89  hi can you help me with an example for this. One doubt about PC application  data will be pushed to DB but what abt the verification part. Please can you explain me a little more detail as how can i do this bcoz my app is almost done and stuck at this point. My users will be authenticate them self in different locations on biometric device.

**Comment by JohnRanger** [comment]
Hi srinivas1910: 
The Problem is that your biometric device cannot natively interact with a Webpage (speaking of Technology). Therefore you have to provide a self-developed application to your users which uses the mentioned SDK and does the identification part and uses an embedded Internet Explorer (or whatever browser you will provide to your users) and then fill in the Login and Password field on the Login page of your serenity Framework-based WebApp or - as vinaykulkarni89 pointed out: Send first a random-generated Password to the Serenity user Table into the record of the specific user and then log in within the page with the user's Name and the just randomly generated Password to increase the security a bit (so that users cannot Login without the biometric device and your app).

But if your users will only have the biometric device and a browser, this will not work as there is nothing which will connect the browser and the Content of the web page with your biometric device. That's where your custom - os-specific - app will come into Play which accesses the biometric device and does the identification of the user pushing his finger on the Fingerprint Reader of the biometric device and then sending the matching user's username and Password into the Login form of your serenity WebApp.

If your users all are using Windows PCs and their browser will all be Internet Explorer, then look at System.Windows.Forms.Webbrowser class: https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-add-web-browser-capabilities-to-a-windows-forms-application

With Kind regards,

John

**Comment by srinivas1910** [comment]
Hi @JohnRanger 
Thank you for your reply, I am using the Bio-metric for attendance authentication not for user login. Please let me known is there any solution for this bcoz almost my application is done and only the attendance part is pending, also let me know how to implement the same.

Thanks and Regards,
Srinivas
