### ISSUE TITLE
How to passing value to grid editordialog fields?

### ISSUE THREAD

**Issue by vinslake** [volkanceylan/Serenity#2465]

**Comment by JohnRanger** [comment]
You Need to describe your Problem more in Detail. 

What do you want to achive (end result)?

What did you already try?

From where to where do you want to pass a value?

Otherwise it is really impossible to help.

Also please always mention which Serenity Version you are Building an App with.

With Kind regards,

John

**Comment by vinslake** [comment]
ah sorry Im new to this,by the way i have MasterDetailRelation on the details list add new button when the dialog for the list was call i wanted to pass values on some fields?

**Comment by vinslake** [comment]
found a solution in this thread;
https://github.com/volkanceylan/Serenity/issues/837
