### ISSUE TITLE
Condense table 

### ISSUE THREAD

**Issue by judejay** [volkanceylan/Serenity#2516]
All new to me, but I have managed to install, and get another database hooked up. I would like to condense a table I inherited, to display either by Tabs, or Accordion, the table has around 30-40 columns that need to be displayed. Tried doing Grid in tabs, "Another Form In Tab" and "Another Form In Tab With One Toolbar", but neither worked. They all work correctly on the same page outside of the tab. Thanks in advance.  PS when I run sergen, it imports all 200+ columns.

**Comment by JohnRanger** [comment]
Can you not work with the column selector Feature and create a solution which dynamically only Shows the desired columns?

John

**Comment by judejay** [comment]
Yeah, it's OK, but that requires user to make changes. I was actually looking for something like this :-
https://github.com/jeantimex/ios-swift-collapsible-table-section

**Comment by sayuga** [comment]
Sergen will import all existing columns in the table by design. You then manipulate the fields that you want to show using the Form.cs or Column.cs. 

As far as the columns are concerned, Serenity uses SlickGrid and I don't believe a collapsible column structure is available. If you want something similar you'd have to develop it yourself. You could, for example, add a toolbar button to the toolbar that when pressed, will display and/or hide preset columns. 

as a side note, why does your DB have 200+ columns? can't you subdivide them into themed tables and then just link tables as needed? It should make things much easier to maintain.

**Comment by judejay** [comment]
I think that's what I am gonna have to do, split the table up. I didn't
design the schema, it is all part of a existing setup.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
