### ISSUE TITLE
loading data into some columns based on row click in the grid

### ISSUE THREAD

**Issue by PalaniMurali** [volkanceylan/Serenity#2635]

**Comment by JohnRanger** [comment]
Hi,

in order to be able to potentially help you, please describe exactly what you want to achieve.

Provide some screenshots on which you paint what the desired result should look like.


With Kind regards,

John

**Comment by Zahar661** [comment]
@JohnRanger is that possible?
![image](https://user-images.githubusercontent.com/26430136/30272630-14775668-96fe-11e7-86fc-bad245e7b7f0.png)

**Comment by JohnRanger** [comment]
Hmm,

from my (little) understanding of Serenity Framework, I don't think that with Serenity Framework this is possible because the grid's columns are defined as "constants" within xyzColumns.ts.

That means - in your case the columns with the Dates are completely dynamic - according to the values within the records/rows of your table. --> This would require that the xyzColumns.cs would have to be dynamic which it is not.

With Kind regards,

John

**Comment by volkanceylan** [comment]
It would be possible but you should be competent with javascript and read slickgrid docs.
