### ISSUE TITLE
serenity with dmz and lan

### ISSUE THREAD

**Issue by shacharon** [volkanceylan/Serenity#2643]
Hi 
We plan to run Serenity in DMZ and our DB server in the LAN behind a firewall.
We'll probably have to expose the services at backend.
What's the best way to do that and do SERENITY support it?
We want to use restapi in the backend.

shachar

**Comment by JohnRanger** [comment]
Hi Shacharon,

if you are allowed to just put the SQL Server into the Intranet Zone and the IIS with full Serenity in the DMZ then you are fine (if you run the Serenity-App's database on the SQL Default instance, just open TCP 1433 (your SQL instance) and UDP 1434 (the SQL browser Service) and this works as Long as you use SQL internal authentication. 
If - in the above scenario - you use Windows authentication, then depending on where your AD Domain Controllers are located (Intranet or DMZ), you have also to open all the AD related ports from your Serenity IIS to the Domain Controllers on the Intranet.

If - in the above scenario - you are running the Serenity's database on a non-Default SQL instance (e.g. on a SQL-Cluster), you must make sure that the SQL instance's TCP port is configured fix to a (freely definable) port. Otherwise the SQL instance uses every time on startup different port and you would have to open any TCP port above 1024 in order to work this permanently.

----------

But if you Need to host the Client part of Serenity in your DMZ and the Server part (MVC) in the Intranet Zone (including the Serenity SQL Database), then I cannot help you how to Stretch the app .

Probably Vokan knows how to do it.

With Kind regards,

John

**Comment by shacharon** [comment]
תרגם

תודה רבה על התשובה , לצערי המקרה שתיארת הוא אינו המצב שלנו.
אנחנו בדיוק במצב  ההופכי למה שתיארת, SQL ב LAN וה MVC ב FRONTEND.
אני מקווה שולקן יוכל לעזור 



Thank you very much for the answer. 
Unfortunately, the case you described is not our situation.
We are exactly in the opposite position to what you have described, SQL in LAN and MVC in FRONTEND.
I hope Vokan can help or will give an idea.

**Comment by volkanceylan** [comment]
That is possible and we implemented it for some project, but it is not as simple as explaining it with a few words here and that's pretty out of scope.

**Comment by gguadalupe** [comment]
Hey @shacharon, follow @JohnRanger instructions, it is exactly what you need.
I have the same you need (sql behind the firewall in the lan, and the app in the public web server) and the only thing I needed to do is to open the sql port. (right now I'm not using the AD to authenticate, but I expect to implement that part soon.)

Gus.

**Comment by shacharon** [comment]
Unfortunately, in terms of the system, we will not be able to open ports due to information security limitations.

We do want to use the system, how can (if at all) expose the services to another server.
You mentioned before you did something like this.

**Comment by VR-Architect** [comment]
I concur that  @shacharon gave the correct approach. I would only add that the firewall should only open the database ports from the IP of the front-end to/from the database server IP address/es. For security, you may consider having two network cards with different IP addresses. One for pacing the Internet firewall, and another facing the LAN firewall. From a Serenity perspective, this is really out of scope of the application and really in the network security domain.

**Comment by gguadalupe** [comment]
After reading the first post again, I think Shachar want to separate the data layer from the UI and host the data layer in the lan, and the ui in the dmz, and communicate the two with apis.
But this means to cut Serenity in two and sew the two parts back together.
Without the help of the original architect (@VR-Architect, no put intended!) of Serenity (#VolkanForPresident) you are creating a security risk grater than opening the port (witch btw you can do it without any security risk at all if you do it correctly).

@shacharon, If you really need to do this, I encourage you to hire Volkan and his team to do it.

Gus.
