### ISSUE TITLE
 use an application like a selected user

### ISSUE THREAD

**Issue by volkanturk** [volkanceylan/Serenity#2654]
Hello there,
I want to select any user after login as admin in SERENE and use SERENE as that user (by taking the rights of the selected user)

Because I want to test the forms on the selected user

I do not want to ask the user's password

**Comment by JohnRanger** [comment]
Hmm,

I don't know if this is possible because of security reasons (you as the admin could do Things on behalf of the user which the user doesn't know).

From my Point of view (security view) the Framework should prevent this :-)

If you have to test something from a specific user's perspective on a PROD System, ask the user for permission to reset his/her Password and to do your Tests.

Of Course - if you for whatever reasons want to test something without letting the user know - you always can copy the Database, reset the particular user's Password in the copy of the DB, copy your Serenity Framework Project, Point the DB connectionstring in web.config over to the copy of your DB and then perform your Tests.


With Kind regards,

John

**Comment by volkanturk** [comment]
Thanks John, i will try
