### ISSUE TITLE
creating fields dynamically

### ISSUE THREAD

**Issue by AbhishekBorkar04** [volkanceylan/Serenity#2694]
hello,
i want to add fields dynamically i.e from front end.
for eg.
![btmuss](https://user-images.githubusercontent.com/30266516/30894972-c3402428-a364-11e7-84eb-67c39a6e60d9.jpg)

when user click on  add ,fields should be  added in corresponding table and also creates its respected UI
pls help....

**Comment by sayuga** [comment]
I don't believe that feature is currently available. Take into account you'd have to build something on your own. An alternative is to create a table with a cap number of string columns that you can then manipulate through a separate module to handle data types on the programaticalyl instead of from the table. Then you could have a second table that could store the values needed to tell clientside which columns are 'active' and have what virtual data type.

**Comment by AbhishekBorkar04** [comment]
ty @sayuga  so there is no option to create field from front end

**Comment by volkanceylan** [comment]
Many things are possible but sometimes you should code it...
