### ISSUE TITLE
How to implement serenity style google map page?

### ISSUE THREAD

**Issue by zehranur** [volkanceylan/Serenity#27]
I already write a simple pure javascript code for google maps page but i wonder is there any better solution.

I want to handle google maps canvas and and marker and others stuffs in cs file in the Script project. I don't know is TemplateDialog right class for base panel.

I put a simple class in Script project like that:

```
 [Panel]
    public class HaritaDialog : TemplatedDialog<object>
    {
        Widget<object> map;

        public HelalMarketHaritaDialog()
        {
         map = ById("GridDiv");   
        }

        protected override string GetTemplateName()
        {
            return "GridDialog";
        }
    }
```

I have create a Page and cshtml file in Web solution. In the cshtml 

```
<div id="GridDiv"></div>

<script type="text/javascript">
    jQuery(function () {
        new Project.Module.HaritaDialog($('#GridDiv'), {}).init();

        Q.initFullHeightGridPage($('#GridDiv'));

        var myLatlng = new google.maps.LatLng(41.0191602,29.086761);

        var mapOptions = {
            center: myLatlng,
            zoom: 16,
            // disableDefaultUI: true // un-comment to remove default Maps UI
            // map type options: HYBRID, ROADMAP, SATELLITE, TERRAIN
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        var map = new google.maps.Map(document.getElementById("GridDiv"), mapOptions);

        Q.serviceRequest('Module/SubModule/List', {}, function(result){
    if(result!=null && result.Entities != null && result.Entities.length>0){

    for(var i=0;i<result.Entities.length;i++){
    if(result.Entities[i].Koordinat == undefined || result.Entities[i].Koordinat == null)
    break;

    var koordinat = result.Entities[i].Koordinat.split(',');
    var myLangLat = {lat: parseFloat(koordinat[0]), lng: parseFloat(koordinat[1])};

    var marker = new google.maps.Marker({
    position: myLangLat,
    map: map,
    animation: google.maps.Animation.DROP,
    title: result.Entities[i].Ad
  });

    }

    }
    }, null);
});
</script>
```

**Comment by VictorTomaili** [comment]
you must implement a import cs file for google map js library. after that you can use it in dialog.cs file with intellisense support. Otherwise you can use dynamic object for one time use. 

implementation examples is there 
https://github.com/volkanceylan/Serenity/tree/master/Serenity.Script.Imports

**Comment by volkanceylan** [comment]
To use Google Maps or other 3rd party javascript library in Saltarelle with intellisense, you need to write an import library (mess with dynamic).

Google maps import library will be available in Serenity.Script.Imports from version 1.5.6.

I did a quick transfer of one i found at https://gmapsharp.codeplex.com/. That one was written for Script#, so i only had to do only a few find/replaces.

Now, when it comes to how to write your page in Serenity style, i would do something like this:

```cs

namespace MyApplication
{
    using google.maps;
    using jQueryApi;
    using Serenity;

    public class MapPanel : TemplatedWidget
    {
        public MapPanel(jQueryObject container)
            : base(container)
        {
            var gm = new GoogleMap(this.ById("Map"), new GoogleMapOptions
            {
                Latitude = 41.0191602,
                Longitude = 29.086761,
                Zoom = 16
            });

            new Marker(new MarkerOptions
            {
                Title = "Test 1",
                Position = new LatLng(41.0191752, 29.086901),
                Map = gm.Map
            });

            new Marker(new MarkerOptions
            {
                Title = "Test 2",
                Position = new LatLng(41.0190552, 29.085711),
                Map = gm.Map
            });
        }

        protected override string GetTemplate()
        {
            return "<div id='~_Map'></div>";
        }
    }
}
```

I recommend using TemplatedWidget, instead of TemplatedDialog as base class, because it seems like you don't actually need dialog functionality.

And my Page.cshtml code would be like this:

```html
<div id="MapPanel"></div>

<script type="text/javascript">
    jQuery(function () {
        new MyApplication.MapPanel($('#MapPanel'), {}).init();
    });
</script>
```

Try to keep script code to minimum, and encapsulate logic and other code inside a widget written in C#.

**Comment by ademc** [comment]
This is the key:

***Try to keep script code to minimum, and encapsulate logic and other code inside a widget written in C#.***

OK I guess your last check-in explains how to implement javascript library in serenity. We really apreciate your help. 

So i see that convert a javascript component to serenity component
- Create all library types in c# with empty classes, empty properties, full listed enums and etc.
- After all use c# types to write javascript code.

So I want to ask that How to understand/map serenity javascript library with c# imports?

**Comment by volkanceylan** [comment]
Actually i didn't convert javascript component to serenity component, i just imported it for Saltarelle/Script#, this is just like writing a ".h" file for C, or ".d.ts" file for Typescript. Or, in C# terms, importing a Win32 library with "extern" definitions.

To import library X, first you need to know what classes, options etc. library has.

You can look at documentation of library, or check TypeScript import libraries at 

https://github.com/borisyankov/DefinitelyTyped

After this, you need to map the external library to Saltarelle [Imported] classes. Though at start it might feel a bit hard, but once you learned some basics, it gets easier. Unfortunately, there is no guide for writing imports at the moment for Script# or Saltarelle. I learned how to do this mapping by checking other import libraries for Script#/Saltarelle source code, for example jQuery and jQuery UI. You can also check samples in Serenity.Script.Imports.

I will try to add a chapter about this topic to Serenity Developer Guide.

Saltarelle recently acquired by Bridge.Net, and they have plans to auto-convert TypeScript import libraries to C# imports. So we won't have to write imports manually for common libraries, as DefinitelyTyped has many of them already.

Also, i'm considering if it will worth switching to TypeScript completely, instead of Saltarelle or Bridge.Net.

**Comment by ademc** [comment]
Ok i understand now. Thank you very much.
