### ISSUE TITLE
AutocolumnSize problem with Tabs

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#2737]
I am using the autoColumSize plugin to avoid setting size on each column. 
Everything is working fine unless you display an autosized grid in a (second) tab.

In the code :
        function resizeAllColumns() {
...
                elHeaders.each(function (index, el) {
                    var columnDef = $(el).data('column');
                    var headerWidth = getElementWidth(el);
...
                });

This can be easily reproduced using Movies Sample.
when autosize grid is second tab then the line :  var headerWidth = getElementWidth(el);
always is set to 0 (so basically grid column is sized based on column content (not on column header length).

The problem can be fixed by displaying the Grid tab first (on EntityDialog.Template.html) but it's not correct solution.

Any chance someone could fix this ?

**Comment by kilroyFR** [comment]
Problem is related to using offsetWidth (that should be applied to display:block).
Test : https://jsfiddle.net/Lvntyrjy/1/

Solution  : (on slick.autocolumnsize.js) 
clone.style.cssText = 'display: block; visibility: hidden;right: auto;text-overflow: initial;white-space: nowrap;';

**Comment by ArsenioInojosa** [comment]
Hello, I also have this problem. Columns do not display correctly when in a secondary tab.

![image](https://user-images.githubusercontent.com/11929923/87844134-63946b00-c888-11ea-8149-10df5316cdf0.png)

But when you change any of the filters then the columns show fine.

![image](https://user-images.githubusercontent.com/11929923/87844145-7d35b280-c888-11ea-974b-86f432c73d02.png)

I noticed that when you load the grid and there is no data to display then the columns resize and look good. The problem is when there is data the first time it loads.

![image](https://user-images.githubusercontent.com/11929923/87844219-2d0b2000-c889-11ea-958e-11ba8026a857.png)

Code:

`
        private autoSize;

        constructor(container: JQuery) {
            super(container);
        }

        protected createSlickGrid(): Slick.Grid {
            let grid = super.createSlickGrid();
            this.autoSize = new Slick.AutoColumnSize(true);
            grid.registerPlugin(this.autoSize);

            return grid;
        }

        protected markupReady() {
            super.markupReady();
            if (this.autoSize != null) {
                this.autoSize.resizeAllColumns();
            }
        }`

Thank you!
