### ISSUE TITLE
How to represent and capture relational data

### ISSUE THREAD

**Issue by yangyer** [volkanceylan/Serenity#28]
Is there a way to represent relation data (ex: Orders & OrderItems)?  If I want to adjust the view where can I do that?

**Comment by ademc** [comment]
For now there is no Master-Detail view in serenity. But I think you can add yours.

Or simply try this is experimental funny solution:

Change Web.Proj/Views/Templates/EntityDialog.Template.html file to

```
<div class="s-DialogContent">
    <div id="~_Toolbar" class="s-DialogToolbar">
    </div>
    <div class="s-Form">
        <form id="~_Form" action="">
            <div class="fieldset ui-widget ui-widget-content ui-corner-all">
                <div id="~_PropertyGrid"></div>
                <div class="clear"></div>
            </div>
        </form> 
    </div>
    ***<div id="~_DetailGridDiv" class=""></div>***
</div>
```

In Master entitiy dialog  file little change:

```
protected override void LoadEntity(MasterEntityRow entity)
        {
            base.LoadEntity(entity);
            detailEntityGrid = new DetailentityGrid(ById("DetailGridDiv"));
            detailEntityGrid.MasterRow = entity;
        }
```

**Comment by volkanceylan** [comment]
Though it might seem to work, I wouldn't recommend this solution @ademc. 

First, editing EntityDialog.Template.html means changing all entity dialog templates, not just one where you will use this functionality.

Also, creating a widget in LoadEntity means, whenever an entity is loaded to dialog, a new widget is created. Although, LoadEntity is is usually called once in dialog lifecycle, it is also possible to be called several times, e.g. when you click Apply Changes button instead of Save. I'd recommend creating widget in constructor, while assigning master id in LoadEntity.

Actually, master/detail editing functionality exists in Serenity, and there are several ways to do it. There is just no sample in the Serene template.

I'll try to add a sample to Serene and also update Movie tutorial with cast editing.

**Comment by yangyer** [comment]
Thanks @volkanceylan  for the quick  feedback.

I have another question, slightly related, I need to implement a custom design for list pages and form pages.

Any thought about implementing Bootstrap in the future?

**Comment by volkanceylan** [comment]
I answered your question about related records in Visual Studio Gallery, but copy/pasting here just in case:

> Now with version 1.5.7, Order and Detail interface is ready. Order details are edited in memory. It means when you edit and update an order detail in Order Detail dialog, it is just updated in the detail grid of Order dialog (no service call to update db happens yet). After you click *Update* in the Order dialog, the Order and its details are updated within a transaction.

> Of course, it would be also possible to update them independently, but i wanted to show how it works if required that way.

> As an independent master/detail listing and editing sample, Customer dialog has a tab to show and edit orders related to the customer.

> I'll also add a sample chapter to Movie tutorial in Serenity Developer Guide. Let me know if anything is not clear enough.

About theming, it is possible to style interface to whatever you like using CSS. I'm actually overriding default Serenity look in Serene template. Check site.overrides.serenity.less and site.layout.less. 

As widgets has very simple CSS, it should be straightforward. But i'm afraid you can't simply use a Bootstrap theme just by including its CSS file. I can try to help if you get stuck working on looks.

Actually there are parts where i use Bootstrap, like menu, layout etc, but there are also some jQuery UI widgets (there was no Bootstrap when i started Serenity), some custom widgets i wrote, and SlickGrid doesn't support Bootstrap, afaik.

I have plans to use more Bootstrap components (or whatever becomes the trend), switch to flex-box model, remove jQuery UI dependency etc, but i can't give a timeline. I want to do this with as less breaking changes as possible, because i have some large-scale projects running on Serenity.

**Comment by zehranur** [comment]
when i try to update detail entity of grid editor,  creates duplicate item. 
When use the validatioun which in the northwind example, dialog does not allow update detail item.
I can not figure out.
Thanks.
