### ISSUE TITLE
Dailog not opening in Update mode using sql View

### ISSUE THREAD

**Issue by ManzoorPK** [volkanceylan/Serenity#2833]
Hello Friends.

I have a grid which is coming from View but when i click on any record its always opens form in Insert mode. even the fields are felling but the Id columns got null.

**Comment by JohnRanger** [comment]
Hi @ManzoorPK ,
can you Show us the Tables which are the base for your view - and also how the view is constructed? (Print Screen from SQL Management Studio as well as the resulting query?

Otherwise it is impossible even to consider any help.

For the record, I use often views as the base for a grid and it always works like It would work with a real table. 

But my views are always only innerjoined Tables and sometimes they also include calculated fields.

With Kind regards,

John

**Comment by ManzoorPK** [comment]
![view](https://user-images.githubusercontent.com/2439608/32309918-a4e71550-bfb0-11e7-9ac5-691b33f373aa.png)

**Comment by JohnRanger** [comment]
Hi @ManzoorPK ,
I don't know if the calculated ID (over clause) can be causing Problems.

Doesn't your original table (dbo.loanTypes) have an identifier column already which you could use?

--> Use original ID field from LoanTypes table and also remove the "order by".

Please let us know if this helps.

With Kind regards,

John
