### ISSUE TITLE
Can't load script data: Lookup.Units.UnitData

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#2924]
Working on some recent change requests I've been updating a Dialog.ts to add some data to be displayed from another Row. Using the code in image 1 (as I have done in a number of other dialogs), I have all of a sudden started getting the error in image 2 via browser console. Anyone have any idea why this has stopped working for me?

1: ![image](https://user-images.githubusercontent.com/31215482/32791176-5d9810dc-c92e-11e7-8ef1-221a02adb6f5.png)

2: ![image](https://user-images.githubusercontent.com/31215482/32791186-67227bc4-c92e-11e7-8217-b4d2a9b15e79.png)

**Comment by JohnRanger** [comment]
Hi z-combs,

do you have a [LookupScript] defined within your UnitDataRow?
If yes: Can you do the following:

(1) remark everything within your xyzDialog.ts which would Need the lookup
(2) clean and rebuild your solution
(3) Do a T4 transform
(4) rebuild again
(5) uncomment everything you had previously put to remarks because of this error

Hope this helps,

John

**Comment by z-combs** [comment]
Yes the lookupscript attribute is there: 
![image](https://user-images.githubusercontent.com/31215482/32798290-3f32436a-c942-11e7-9ff5-99d38a5c1f7c.png)

I've tried doing the transform trick quite a few times now. I went as far as completely removing all the typescript files associated with the UnitData from ServerTypings and regenerating them by doing the transform. Still not working.

**Comment by z-combs** [comment]
Updated Serenity and having different issues, closing and opening new issue

**Comment by volkanceylan** [comment]
You know there is an option of looking at URLs  that gives errors e.g. open in window and check whats wrong.
