### ISSUE TITLE
Thank you Note 2017 

### ISSUE THREAD

**Issue by Magik3a** [volkanceylan/Serenity#3103]
Hi @volkanceylan . I am writing this issue to say how much i appreciate the software that you created! Really man, i can't thank you enough!

I am using Serenity for almost a year now with the only purpose to help Bulgarian people with their medical appointments because in that case the country is real sh-t,
and as a fellow developer that is trying to work on full time job, to keep his knowledge up to date, to have a personal life and to help a little bit on other people, i can only say Thank You Man, you are the best! 

Happy New Year if you see this late, and if some day i make any money of this i will buy a ticket to have a drink with you with the Best Bulgarian Rakia that i can find!

**Comment by volkanceylan** [comment]
Thanks Svet I appreciate you and your support as far:) Happy New Year and looking forward to meet, really happy to hear that thing works!

**Comment by wldkrd1** [comment]
Agreed, we very much appreciate the work you and the other contributors have done!

**Comment by 04071967** [comment]
Thank you @volkanceylan , Happy new year to you too

Serenity ......... Excellent work.

**Comment by VR-Architect** [comment]
Totally agree too! The software is visionary and your dedication is wonderful.  I look forward to renewing the support contract next year.

**Comment by ms4hafiz** [comment]
@volkanceylan 
Thank you for the great tool and support.... Happy new year.

**Comment by gguadalupe** [comment]
Wait!! I want to give a little love too!

My case is a little selfish. You @volkanceylan and your team not only gave us an awesome platform, but in my case you gave me back the confidence to go back to programming.

As an employee in a software company, I started as a programmer and I move my way to manager, project manager, even a little sales, but in that transition I had to give up programming in favor of other, more manage-y, skills.
At some point with so much new technology I felt really out of place (Yay! I'm old!) but with Serenity I finally understand many of the concepts that were completely different from VB6, and how all these technologies comes together.

I don't have Serenity in any production app just because I'm not there yet (too risky), but with a little more of swimming in the code, I will be ready.

Thank You @volkanceylan and your team for this, for giving me back my hobby and my passion.

Happy New Year for all or you!

Gus.

**Comment by GreenUtil** [comment]
Yes,, it's a great framework, thank you @volkanceylan. A healthy 2018 for everybody here. Technically spoken, I am wondering if the ASP.NET MVC webservices provided by the Serene platform actually can be re-used in a Xamarin mobile context.  (or with some minor additional programming effort)

**Comment by dfaruque** [comment]
Happy new year.
In my opinion, Serenity is an unique ASP.NET MVC platform. There is no alternative to Serenity at the moment (I believe).

Thank you @volkanceylan  and others who contributes.

**Comment by karimhyatt** [comment]
I would also like to leave my thanks and wish everyone and @volkanceylan in particular a very Happy New Year. I appreciate the patience you have all shown and appreciate the support from everyone over 2017. May you all have a prosperous and productive 2018.

**Comment by volkanceylan** [comment]
@GreenUtil they can be used from Xamarin, Android, IOS, actually anywhere that can make a JSON post
