### ISSUE TITLE
QuickFilter filtering

### ISSUE THREAD

**Issue by vgalicc** [volkanceylan/Serenity#3159]
Can I filter QuickFilter with dynamic parameter e.g. on Orders I would like to have items filter and display only items from current Order:
![image](https://user-images.githubusercontent.com/34982947/35031244-6a6dcebc-fb62-11e7-9046-79630a331bee.png)

**Comment by volkanceylan** [comment]
Probably not, see quick filter samples.

**Comment by UlyssesAlves** [comment]
Where can I find QuickFilter samples?

**Comment by minhhungit** [comment]
@UlyssesAlves http://serenity.is/demo

**Comment by UlyssesAlves** [comment]
Thanks, @minhhungit 

I had actually already seen this page, but I couldn't make some quick filters work in the project I'm working on. 

There's two problems I couldn't resolve:

- One of the problems is that I couldn't implement a quick filter for a field of fixed pre-defined values, because Serenity didn't recognize the new Enum I created on the project to represent the fixed values related to the field I wanted to filter. The error reported by Serenity was that I should put my new Enum in the project root namespace (it was there, like other enums which already exist and work on the project) and I also have to be sure the project compiles and generates the T4 templates.

- The other problem was that I couldn't find out how to build a quick filter for a filed which has a limited set of string values on the database. Sure I could have refactored these pre-defined string values to an enum and replace the text with the corresponding new enum values, but I didn't try this approach, since the first problem would disallow me from completing this solution by the way.

It looks like the root cause for the T4 templates being not generated is because TypeScript doesn't recognize the types like System.Threading.Tasks.Task<Serenity.SaveResponse> in some of my service files. The compiler says "(TS) Namespace 'System' has no exported member 'Threading'". Since these service files are automatically generated by Serenity, I can't resolve this issue by myself. That is, my project depends on Serenity generating the files correctly for it to work properly (of course). But I don't know why the files are being generated with these errors, and also I don't know to to fix it.
