### ISSUE TITLE
MasterDetail and many rows

### ISSUE THREAD

**Issue by Zahar661** [volkanceylan/Serenity#3188]
Hi!
Help please! 
1) How can I enable page navigation in MastreDetails?
or 
2) How can I increase the limit?
Not Work
```
protected getViewOptions() {
            var opt = super.getViewOptions();
            opt.rowsPerPage = 10000;
            return opt;
        }
```
3) And more problems, you can turn on the search bar at MasterDetails?

**Comment by kilroyFR** [comment]
2. rowsPerPageOptions is defined internally in Serenity as list of following possible values [20, 100, 500, 2500]
=> Any of those can be set (so 10000 is not possible)

**Comment by Zahar661** [comment]
@kilroyFR 1000 should be enough

**Comment by kilroyFR** [comment]
@volkanceylan maybe could be useful to add the 1000 value in the default list (between 500 and 2500 the gap is huge).

**Comment by biggikalli** [comment]
Also "0" to Show All,  when & if the query is volume safe.This parameter keeps the dropdown option available on front-end, instead of disabling the element with an override. Bad practice for transactional tables/views, but useful in some cases of static/higherKey data tables or sp's.On Jan 29, 2018 20:52, Zahar661 <notifications@github.com> wrote:@kilroyFR 1000 should be enough

**Comment by biggikalli** [comment]
... if 1000 is "a must" you could look into Paging options in the back-end. Most SQL's offer this option and Custom Paging in MS is beneficial for boosting performance on client-side.  Perhaps VC may alter/add parameters in source but Serenity wouldn't be this great if not for his moderation.>> MaxRows 1000 set in db & 2500 in xyzGrid.ts - but the dropdown option will be useless with this.- - - Just throwing this out here because I haven't noticed it discussed in past issues. On Jan 29, 2018 21:24, Biggi Kalli <biggi@biggi.is> wrote:Also "0" to Show All,  when & if the query is volume safe.This parameter keeps the dropdown option available on front-end, instead of disabling the element with an override. Bad practice for transactional tables/views, but useful in some cases of static/higherKey data tables or sp's.On Jan 29, 2018 20:52, Zahar661 <notifications@github.com> wrote:@kilroyFR 1000 should be enough

**Comment by Zahar661** [comment]
The drop-down menu is missing from the MasterDetails
and
does not work 0, 1000, 2500, 10000
```
protected getViewOptions() {
            var opt = super.getViewOptions();
            opt.rowsPerPage = 2500;
            return opt;
        }
```

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/35553630-c8d03ea8-05a9-11e8-87f7-7376b22236c0.png)

**Comment by volkanceylan** [comment]
MasterDetail doesn't support paging, it has to load all rows, so pager is not supported

**Comment by Zahar661** [comment]
@volkanceylan Good! but it does not load all the data only about 100 first. Unfortunately.
Can I somehow increase this threshold?

**Comment by volkanceylan** [comment]
If that is an ordinary master detail relation, there is no 100 limit, or 10000000 limit, it loads all rows

**Comment by Zahar661** [comment]
```
[DisplayName("Сотрудники"), MasterDetailRelation(foreignKey: "DepartmentId"), NotMapped]
        public List<PersonRow> PersonList
        {
            get { return Fields.PersonList[this]; }
            set { Fields.PersonList[this] = value; }
        }
```

```
 [PersonEditor, Tab("Сотрудники"), DisplayName(""), LabelWidth(0)]
        public List<Entities.PersonRow> PersonList { get; set; }
```

![image](https://user-images.githubusercontent.com/26430136/35554909-659ca100-05ae-11e8-9b6d-4f5dd5b1aef9.png)

![image](https://user-images.githubusercontent.com/26430136/35554940-89d3e06a-05ae-11e8-929e-ba180e4bc4f7.png)

**Comment by Zahar661** [comment]
Excuse me! Began to collect an example, found an error in the database!
