### ISSUE TITLE
Single Sign-on (SSO)

### ISSUE THREAD

**Issue by GreenUtil** [volkanceylan/Serenity#3221]
Hello all,

I am wondering, is it possible to make a construction in which users can login to more than one Serenity application by using Single Sign-on ?
Each application has its own database and its own user-table, and Usernames/Passwords are the same across the seperated databases.

Greetings

**Comment by kilroyFR** [comment]
I am doing this at this time.
We had an SSO webAPI already where all our ASPNet webforms applications were connected.

I wanted to keep the SSO interest (i mean connecting to an API/URL with ONE single logon and permissions are retrieved for the user and the application).
After successful connect, 'ReturnUrl' sends the user back to Serenity application with all permissions (these infos are saved in db locally).

Each application is having its db model (with users/permissions etc.) 
=> these tables are NOT filled by the application but are retrieved from a SSO URL

It works well with very few changes and most important, i could keep existing structures of serenity (permissionservices etc.).
I also have enabled possibility to connect to my application in case SSO is in failure (API not available).
It was important not to hang all applications because SSO is in failure.
With user informations and permissions already stored in db i can still use my application.
So for me it's best of 2 worlds (strongly coupled with SSO and independancy with non SSO).

**Comment by GreenUtil** [comment]
Hello kilroyFR, thank you for your answer.
An additional SSO webAPI is a way of solving this.
I am going to think about that.

For the moment, I concentrate on the Serenity framework itself, and then I have these thoughts  : 

1. when implementing SSO, I think   **AccountLogin.cshtml**   has to be by-passed when starting another Serenity application :  how can this be achieved ?
2. instead of loading the  **AccountLogin.cshtml** form, the Login service from AccountPage.cs should be called : 
```
[HttpPost, JsonFilter]
        public Result<ServiceResponse> Login(LoginRequest request)
        {
            return this.ExecuteMethod(() =>
            {
                request.CheckNotNull();

                if (string.IsNullOrEmpty(request.Username))
                    throw new ArgumentNullException("username");

                var username = request.Username;
                
                if (WebSecurityHelper.Authenticate(ref username, request.Password, false))
                    return new ServiceResponse();

                throw new ValidationError("AuthenticationError", Texts.Validation.AuthenticationError);
            });
        }
```
3. And when the Login service doesn't raise a validationerror, then a returnUrl can be set.....

Is this going to work ?

**Comment by kilroyFR** [comment]
What i did in AccuntPage.cs : 
`public ActionResult Login(int? denied, string activated, string returnUrl)`

test existing SSO Cookie
 if cookie is present and valid then perform a redirect to current serenity application (dashboard actually):
`RedirectResult("~/");` 
otherwise perform a redirect to the SSO login screen :
`return Redirect(config.AuthAPIServer + "AUTH.HTML/");`

On successful login on my SSO API it saves a cookie in the session (saving permissions and some others infos useful in serenity app).
This is easy and works pretty well as i said thanks to a very well designed Serenity components.

**Comment by GreenUtil** [comment]
Thank you, it's a cookie thing !
