### ISSUE TITLE
MultiTenant Migration

### ISSUE THREAD

**Issue by postonoh** [volkanceylan/Serenity#3333]
I added the MultiTenant class to add for migration trying running Add-Migration, update-database not working. I do I add this to my database. How does the Migration work.

**Comment by ga5tan** [comment]
This is, how migration works:
https://volkanceylan.gitbooks.io/serenity-guide/content/tutorials/movies/creating_movie_table.html

you create or copy and edit file in migration folder, and if all is proper it will be executed on application start. Make sure namespace matches, otherwise your file wont be run. You can place breakpoint in your migration, to see if it gets started or not. Also make sure it runs on proper DB.
If name of your DB is not default you will get warning on app start and suggestion to uncomment the check.

**Comment by postonoh** [comment]
Thanks it worked
