### ISSUE TITLE
Initializing GridEditorBase default values

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3472]
I have a GridBaseEditor list embedded in a dialog and listed in xyzRow.cs

I would like to set some initial default values in the Editor form when clicking on AddButton.

how is that possible ? I tried several ways with no luck. 

These default values are important to be set at init as they are used on `CascadeFrom` fields in the form.

**Comment by hairangsua** [comment]
I think you should overide retrieve function in repository or make new retreve request to get default value of your entity and pass it to your dialog.
Sorry because my english is so bad. 
I have init some example for u. Hope it work
In ordergrid.ts
`        protected initEntityDialog(itemType: string, dlg: OrderDialog) {
            super.initEntityDialog(itemType, dlg);

            var details: OrderDetailRow[] = [];

            var orderEntity: OrderRow;
            //Your service. this is just example about how to get data of list
            OrderService.Retrieve({
                EntityId: ''
            }, resp => {
                orderEntity = resp.Entity;
            },
                { async: false });


            //init sample data
            details.push({ DetailID: 1, OrderID: 1, LineTotal: 100 });
            details.push({ DetailID: 2, OrderID: 1, LineTotal: 100 });
            details.push({ DetailID: 3, OrderID: 1, LineTotal: 100 });

            //set data to property in dlg
            dlg.OrderDetails = details;
        }`

In OrderDialog.ts
`   private orderDetails: OrderDetailRow[];
        set OrderDetails(value: OrderDetailRow[]) {
            this.orderDetails = value;

            console.log(value);
            this.form.DetailList.value = value;

        }`

Order is one of modules in Serenity NorthWind example.

**Comment by kilroyFR** [comment]
well, could not make it work.

I think it's pretty common scenario.

The main idea is that i have a property from master xyzRow (named ReferenceID).
I also have a CustomerEditor in this class.
In the Detail dialog, i would like to get this value and use them in the CascadeFrom based on this field.

**Comment by kilroyFR** [comment]
Looks like my answer is in : http://serenity.is/demo/BasicSamples/FilteredLookupInDetailDialog#
