### ISSUE TITLE
Location to place wkhtmltopdf

### ISSUE THREAD

**Issue by kimheangcheng** [volkanceylan/Serenity#3509]
Dear Serenity team,

I have hosted Serenity ASP.NET core on Ubuntu Server cloud. Unfortunately, I could not export any report to PDF due to issue with wkhtmltopdf. 

Could you tell where should I place wkhtmltopdf to on Ubuntu?

Thank you,

**Comment by javaman63** [comment]
Some time ago I had a problem with the PDF GENERATOR also and since the server was from a hosting company I could not solve it.
Here you can see what was discussed at that moment: 

https://github.com/volkanceylan/Serenity/issues/3390

However I found a workaround that allowed me to at least visualize and print the reports almost without problems
Add a : `extension: 'html', ` on your reporter call on xyzDialog


```
            buttons.push(CronSeguros.Common.ReportHelper.createToolButton({
                title: 'Print',
                cssClass: 'export-pdf-button',
                reportKey: 'CronSe.Pol',
                extension: 'html',
                getParams: () => ({ IdCot: this.get_entityId() })
            }));
```

**Comment by kimheangcheng** [comment]
Thank @javaman63, I will try it.

**Comment by reacharihant** [comment]
Can anyone suggest a solution? I am getting the error "System.ComponentModel.Win32Exception: 'The requested operation requires elevation' "
Which location do we actually have to store the wkhtmtopdf.exe?
