### ISSUE TITLE
US States and Countries of the World Lookups

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3609]
Hi

In legacy app I had hardcoded combo with 50 US states and server generated combo with Countries of the world (generated from .NETs CultureInfo.GetCultures +few blacklisted countries)

How would it be best done in Serenity? Lookup from table? Editor with hardcoded values somehow does not work as attribute in Colums file

thx

**Comment by brunobola** [comment]
@ga5tan personally I like to save/get all from DB but you're the only one to answer that for you because of your needs and/or specifications.

If you may have settings related to a country then it would make sense to be a table otherwise if it would always be static and never mutates just hardcode it and you're done.

**Comment by ga5tan** [comment]
thx @brunobola 
I ended up with both in DB
