### ISSUE TITLE
Serenity Update Issue

### ISSUE THREAD

**Issue by basselz** [volkanceylan/Serenity#3647]
Hi @volkanceylan 

I've updated to Serenity v3.7.1
I had an Error regarding "some" of the fields with lookupEditor tag
where it were converted to IntegerEditor
some others have conveted into LookupEditor normally 

what could be the problem please? 

Regards

**Comment by dfaruque** [comment]
I am facing the same problem too...

It seems to me that T4 does not generate correct editor type for Forms which are based on the row with custom base row classes.

would you please help us @volkanceylan

**Comment by Estrusco** [comment]
These fields are standard lookup or have custom lookup editor?

**Comment by dfaruque** [comment]
Standard LookupEditor.

**Comment by dfaruque** [comment]
However, in form, there is no editor specified. 
If specified it works.

Attributes of the property are not gathered from base row classes. 
it only gathered from direct row properties not inherited properties.

**Comment by dfaruque** [comment]
before updating to 3.7 it worked that way though.

**Comment by basselz** [comment]
I've changed the fields names and that worked now

**Comment by dfaruque** [comment]
To fix that, I've specified LookupEditor in form for now.

**Comment by Cossey** [comment]
I've attempted to modify Serenity to add a new option to the BasedOnRow attribute for specifying a Base Class Row for the Forms. I think I have some good progress with the ServerTyping Form code in sergen by making it also check the BaseClass row for attributes but when it generates it still appears to push out the wrong Serenity type (still not picking up those LookupEditors and noting them as IntegerEditors in the Form ServerTypings, which is the problem I'm certain we are having here). I'm sure I have missed something in the code as its still still not picking up the based on base row class, so I will look at it again soon, but an extra set of eyes may help me resolve this faster.

I need this fix too because of the same issues you two are facing. I'm sure others will come across this as the Base Row class eventually gets documented on the Serenity help files.
