### ISSUE TITLE
Integer value in Lookup

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#3706]
I want an Id-field in my lookup instead of Name field.
 what should I do for that? Is it possible in serenity?

**Comment by Zahar661** [comment]
```
[LookupScript("MyModyle.MyLookupName", Permission = "*")]
    public class MyLookupName: RowLookupScript<Entities.DepartmentsRow>
    {
        public DepartmentTextLookup()
        {
            IdField = TextField = "Id";
        }
    }
```

**Comment by Shraddha996** [comment]
hey @Zahar661 thanks for the quick reply 
[LookupScript("PurchaseOrder.MyLookupName", Permission = "*")]
        public class MyLookupName : RowLookupScript<Entities.TblPoRow>
        {
            public MyLookupName()
            {
                IdField = TextField = "PrId";
            }
        }
I just added this code in my master row but it doesn't show the difference

![screenshot 46](https://user-images.githubusercontent.com/39983941/42315142-56b0fa98-8064-11e8-84c7-4a6baffa831b.png)

**Comment by dfaruque** [comment]
do you use the newly created `MyLookupName ` as your lookup type?

**Comment by Shraddha996** [comment]
Yes @dfaruque  just check once
![screenshot 47](https://user-images.githubusercontent.com/39983941/42315625-89af9e3a-8065-11e8-813b-82f810463612.png)
but my lookup is empty
![screenshot 48](https://user-images.githubusercontent.com/39983941/42315649-9c0bb370-8065-11e8-8bb7-f6e262d09932.png)

**Comment by dfaruque** [comment]
delete MyLookupName class 
and try to use the following in TblPoRow
```
        [Expression("T0.PrId")]
        public String LookupText { get { return Fields.LookupText[this]; } set { Fields.LookupText[this] = value; } }
```

and use that field as your NameField

**Comment by Shraddha996** [comment]
hey @dfaruque I think I need to explain my module
see, I have created a module called PurchaseOrder in that there are two tables TblPo and TblPoTran where TblPoTran is in detail section

Now on my TblPoRow, there is a foreign Key field called PrId which derived from PurchaseRequisition Module 

and I want PrId should display all the ID in the lookup, not the IndentorsName(which is my NameField)

**Comment by dfaruque** [comment]
ok. then you need to add that lookuptext field in PurchaseRequisitionRow
and make it namefield in PurchaseRequisitionRow  like the following
       ```
 StringField INameRow.NameField
        {
            get { return Fields.LookupText ; }
        }
```

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/42324885-32eb46fa-806d-11e8-91d2-5998778ec0e1.png)
![image](https://user-images.githubusercontent.com/26430136/42324902-42223494-806d-11e8-9fda-66cb8e7730fa.png)
![image](https://user-images.githubusercontent.com/26430136/42324932-5f951c9e-806d-11e8-973a-801df87e7b20.png)

**Comment by Zahar661** [comment]
The Loopup class is not worth doing in Row.

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/42325406-d7729952-806e-11e8-8e42-32fc22ea5f1b.png)

**Comment by Zahar661** [comment]
https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Supplier/SupplierCountryLookup.cs example

**Comment by AbhishekhHugar** [comment]
hey @Zahar661  
As per you suggestions I have added class file of Lookupscript but it is not showing the data.

Actual requirement :

1. We have two tables - 1.PR and PO
2.In PO entry we have to show PRId integer filed in lookupeditor so it is considered as foreign key.Just now it is showing the value of string field in lookupeditor
but we have to show an primary key value of PR table i.e.Prid .
![screenshot 11 _li](https://user-images.githubusercontent.com/40484328/42366503-f9cbea66-811e-11e8-8df7-0931af04394a.jpg)
as in the above screenshot the pr id in admin which comes from the foreign key from pr all i want is prid instead of intenders name (i.e. admin) from the below screenshot
![screenshot 12 _li](https://user-images.githubusercontent.com/40484328/42366686-7495f91c-811f-11e8-93f5-78d54331ce07.jpg)
thankyou in advace
