### ISSUE TITLE
[Announcement] Serenity / StartSharp Roadmap

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#3781]
Hello Serenity Users,

For those interested Serenity roadmap is in GitHub Projects:

https://github.com/volkanceylan/Serenity/projects/1

By looking at the list, you may have a rough idea of what we are cooking in the coming days for StartSharp (primarily) and Serenity.

I have divided it into four columns. Leftmost one is the features that doesn't have a development plan yet, next three is divided into short, middle and long term, and last column is the ones that are already done (most of them are completed this month).

There might be some others that we haven't yet added to this list.

I'm open to your ideas, and taking note of suggestions / issues here, but please note that our list is already pretty long, so can't make any promises.

**Comment by Estrusco** [comment]
Nice, thanks :)

**Comment by dfaruque** [comment]
You deserved more than thanks

**Comment by iuryamicussi** [comment]
Great roadmap, thanks a lot @volkanceylan !

**Comment by rolembergfilho** [comment]
Amazing!!!

How we can include more feature in this roadmap?

For example: we, @serenitybrasil, trying to do some features important to us, like get photo from camera or scan or folder.

If this feature is ok, how to share it with you?

**Comment by JohnRanger** [comment]
@volkanceylan - Wow - looks really good. :-) 

The only concern I have is, that - as you say - most of these innovations will be reserved for StartSharp. As the price tag of a personal license is nearly USD 1000.- / year, this would prevent at least some of us to switch to StartSharp... because the projects I create with Serenity are not commercial projects where the cost of a Serenity license can be integrated with the project but I would have to pay for it from my own private pocket.

As you somewhere have written, the prices of the Serenity licenses are mostly because of the elevated support like priority support, etc. Some of us would be fine with the forum support we already have here but would be happy to just have access to StartSharp for a clearly lower price (e.g. 190 USD / year).

Would that be something to consider?

Again thanks at this point here that you let us use the extremely high quality Serene (non-StartSharp) project for absolutely free.

With kind regards,

John

**Comment by volkanceylan** [comment]
@JohnRanger no minimum you can get is Basic package, which doesn't include support. There won't be any lower prices.

**Comment by JohnRanger** [comment]
@volkanceylan ,

for the sleekgrid desired features - I have another one which could be very useful also for others:

Realtime Dynamic updates of visible / all row content when changes occur on MS SQL database (see SQLTableDependency, SignalR, etc for supporting push-based and not poll-based logic) 

With kind regards,

John
