### ISSUE TITLE
MultipleFileUploadEditor x FileDownloadFormatter

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#3858]
When I use [MultipleFileUploadEditor] in the form.cs and then in the columns utilzo the [FileDownloadFormatter] I have an error while trying to download the files.

Error:
A possibly dangerous value Request.Path was detected on the client (:).
Description: An unhandled exception occurred during the execution of the current Web request. Examine the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Web.HttpException: A possibly dangerous Request.Path value was detected on the client (:).

I would like to know if it is possible to create a grid of files as shown below:

![image](https://user-images.githubusercontent.com/7516443/44725618-206e5a80-aaac-11e8-8b0f-51eb0bf80385.png)

**Comment by chadburnett** [comment]
I'm not sure how to solve your problem but the CSS for that is gorgeous.  Mind sharing?

**Comment by chadburnett** [comment]
Yea, that looks great.  I've been looking for the same thing.

**Comment by juliermefelix** [comment]
@chadburnett  
Can you do it?

**Comment by edwardch** [comment]
It looks like someone had a similar issue [here (#2942)](https://github.com/volkanceylan/Serenity/issues/2942).

As far as I know MultipleFileUploadEditor stores the values for one row in a json array. I have been wondering if we can save a Detail record for each file instead of a json array field. 

In the columns.cs this determines what is shown in the grid, and if there are multiple files you'll need to decide how you want the user to receive the download. e.g one zip file.? 

I have only used the FileDownloadFormatter for single files (with FileUploadEditor), but am interested in a solution for multiple files as well.

**Comment by juliermefelix** [comment]
The files are saved in the database as shown below. how to retrieve this information to be able for example exibilos in the grid.
![image](https://user-images.githubusercontent.com/7516443/44918180-bc000500-ad10-11e8-9cc0-c960c0fd1d5a.png)

**Comment by juliermefelix** [comment]
how to make the files appear here and be available for download?
![image](https://user-images.githubusercontent.com/7516443/45154016-77f77f00-b1ac-11e8-9bee-a1a2cc4116c9.png)

**Comment by volkanceylan** [comment]
You'll need to write a formatter, parse JSON and display them as you like.
