### ISSUE TITLE
[Improvement Idea] Material Design theme

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#3866]
hey, this is an idea i wanted to submit. We get customers that are used to work on smartphone or tablet.
They recently told us design is nice but grid and adminLte template would be great 'converted' to Material Design for consistent design with others applications. Designers consulting told us it was the actual trend.

I know someone here already moved adminLte template to MaterialDesign (https://github.com/DucThanhNguyen/MaterialAdminLTE).
Any chance this could be in the project map ? (also the SlickGrid as been listed as 'old school grid').
For me it's totally great the way it is but for flat designers it looks too 'round' buttons etc.

thanks

**Comment by brunobola** [comment]
Those chances despiste a good idea almost certainly will broke the current development and updates, even slickgrid with a certain amount oficial effort would bem changeable to responsive if anyone would try.

For me because i develop almost 100% for business i like this plataform alot and think volkan is on the right path.

🙂

In regards to the theme perhaps you came try to make a WIKI when you have a cool theme to Share.

**Comment by volkanceylan** [comment]
I don't have any plans for the moment to apply themes. But, following his tutorial and applying his changes to AdminLTE less files in your project should be a good start.
