### ISSUE TITLE
Hide menu items

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#3899]
Hi

How is it possible to manipulate (hide) certain menu items?

I saw in demo how to generate them, but I would just need to hide bunch depending on date

**Comment by ga5tan** [comment]
yeah, I found example, but it is only dealing with adding of items.
I don't want to add, I want to remove/hide some existing...

**Comment by chadburnett** [comment]
I am currently trying to figure this out as well.  I have built a bunch of modules that users don't actually need to see.  I thought I would hide them via permissions but then the module they have permissions to calls the modules I am trying to hide.  

If I come across anything I think can help I will post it here.

**Comment by ga5tan** [comment]
rite now I am just filtering it out in Model

**Comment by JohnRanger** [comment]
@ga5tan ,
you can completely hide an entry (for everybody) by removing the following line(s) from your xyzPage.cs /NavigationItems.cs:

```cs
[assembly: NavigationLink(2100, "TACMasterLayouts/TacMasterLayouts", typeof(RALayoutManager2.TACMasterLayouts.Pages.TacMasterLayoutsController))]
```
and then use the approach in above linked Wiki article to show them dynamically to people who should see it.

But... i like the approach above from @chadburnett better because it also really protects the access to these pages - while my approach just hides the pages but if somebody knows the link he/she still can access the hidden page.

**Comment by erehtolleh** [comment]
I know this is old but was looking for same, so just posting for others.  There is a permission setting that you can use and it appears to work.  Use the same permission keys on the row class.  By default everyone has permissions on these tables so the navigation items are shown.  You can hide them by setting permission on the navigation link.  I set it to the row update permission.  So if users has permission to update the table, then they should see the link.

`
[assembly: NavigationLink(2100, "TACMasterLayouts/TacMasterLayouts", typeof(RALayoutManager2.TACMasterLayouts.Pages.TacMasterLayoutsController),Permission= PermissionKeys.Update)]
`
