### ISSUE TITLE
Can we upgrade the Nuget Packages?

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#4214]
Hello,

Running Serenity latest on .NET Core. Can/should we upgrade any of these packages? **_Note for Azure app services Linux users: As of today Azure only supports Microsoft.AspNetCore.All version 2.1.2_**

![image](https://user-images.githubusercontent.com/5250669/51253788-55048500-196d-11e9-8a0b-4ee3595b238b.png)

**Comment by ga5tan** [comment]
You can do MailKit, 
I believe EPPlus did not work for me (MVC)
I dont think I use Sqlite
BE CAREFUL with MSBuild, it wont transpile TS out of the box. See other thread with proposed fix from Volkan

**Comment by volkanceylan** [comment]
Updating Serenity updates many packages. There are some in StartSharp that is referenced separately so they are not updated. As long as you update to versions in latest StartSharp that would be fine. Otherwise you'll be risking having issues as it means we didnt test them yet. Most might work but one breaking change might cause you many troubles, so i'd wait unless there is a compelling reason.

**Comment by brunobola** [comment]
you can update some but for instance typescript no because of compatibility issues (no tsc.exe anymore).

The the Exception modules also can't upgrade because of new bin force to implement methods as sync and serenity override still have sync methods (older version).

Also latest Bootstrap (V4) and lead to issues, so better just upgrade serenity to keep everything working properly just like the @volkanceylan said.

**Comment by VR-Architect** [comment]
Thanks everyone! I will stay in sync with latest StartSharp going forward.
