### ISSUE TITLE
Objectif :0 AppSettings in web.config - Dream or Reality ?

### ISSUE THREAD

**Issue by kilroyFR** [volkanceylan/Serenity#4309]
hey all, i was wondering if someone already tried to get a web.config file holding almost no AppSettings but only a ConnectionString to DB (where parameters could be stored/shared easily) ?

For each application we develop we tend to multiply configuration files (sometimes multiples standalone applications share same DB).
Idea is to centralize those settings so it's unecessary to access application files to modify/change settings (we experienced a user that did not accept deployment of software (even a little modification in app.config) and requested complete new version each time (when a simple modification in DB would have done the job perfectly).
When appConfig holds nothing related to application, the file can be overwritten by mistake without worrying. How many time an app.config has been overwrittent by mistake, loosing some settings ?
On all our standalone applications we now stick to these rules and it's perfect for maintenance.

My only remaining problem deals with Web.config file for webapps.
I noticed a set of parameters : 
example : 
 ```
   <add key="BackgroundTasks" value="{ Enabled: false }" />
    <!--<add key="DevelopmentSettings" value="{ IsDevelopmentMode: true }" />-->
    <add key="LocalTextPackages" value="{ Site: [ 'Controls.', 'Db.', 'Dialogs.', 'Enums.', 'Forms.', 'Permission.', 'Site.', 'Validation.' ], Login: [ 'Forms.Membership.Login.', 'Db.Administration.User.', 'Validation.Required', 'Dialogs.' ] }" />
    <add key="Logging" value="{  Level: 'Verbose' }" />
    <!-- File: '~\\App_Data\\Log\\App_{0}_{1}.log',  FlushTimeout: 0 -->
    <add key="MailingService" value="{ Enabled: true, AutoUse: true }" />
    <add key="CDNSettings" value="{ Enabled: false, Url: '', Include: [], Exclude: ['dynjs.axd/Lookup.*', 'dynjs.axd/RemoteData.*', 'dynjs.axd/RegisteredScripts.js'] }" />
    <add key="CssBundling" value="{ Enabled: false, Minimize: true, UseMinCss: true}" />
    <add key="ScriptBundling" value="{ Enabled: false, Minimize: true, UseMinJS: true, NoMinimize: ['~/Scripts/ckeditor/ckeditor.js'], Replacements: { REACT: 'development' } }" />
    <add key="UploadSettings" value="{ Path: '~\\App_Data\\upload\\' }" />
    <add key="RequireHttps" value="false" />
    <add key="vs:EnableBrowserLink" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
```
  Is it possible or would it be possible to reduce all these settings and move them to db (i mean thru a custom adapter) ?

**Comment by edwardch** [comment]
You can probably move some of them. Like background tasks - you have access to the code where the config gets set, so there you could pull values from the database's "Config" table. 
I'm not 100% sure if script/css bundling will work there because this would be done when being built/compiled.

In my web config (that is added to source control), I use 
```xml
<configuration>
  <appSettings file="..\..\AppSettingsSecrets.config">
    <add key="BackgroundTasks" value="{ Enabled: true }" />
```

Then in the AppSettingsSecrets.config file it looks something like this:
```xml
<appSettings>
    <add key="BackgroundTasks" value="{ Enabled: false }" />
</appSettings>
```
Anything in this secret file takes preference over what's in app config.

This means you can keep secret and custom settings in this file without worrying that passwords/keys get uploaded to source control.

Maybe you could do the same for your deployed apps (assuming they're separate apps, and one DB). So if you overwrite your app config on the app server, it still references a secret file that is in a higher directory and these mistakes wont hurt you as much.
