### ISSUE TITLE
StoredProcedureGrid getQuickFilters() 3 questions

### ISSUE THREAD

**Issue by Takecarecom** [volkanceylan/Serenity#4316]
![image](https://user-images.githubusercontent.com/13514630/54048964-c6461300-420d-11e9-9389-7a1dfae4c571.png)

**Comment by edwardch** [comment]
```ts
protected getQuickFilters() {
    var filters = super.getQuickFilters();

    filters.push({
        type: Serenity.LookupEditor,
        options: {
            lookupKey: YourProject.YourModule.xyzRow.lookupKey
        },
        field: 'xyzID',
        title: 'Filtering Field',
        handler: w => {
            (this.view.params as YourStoredProcedureRequest).xyzID = Q.toId(w.value);
        }
    });

    return filters;
}
```

**Comment by edwardch** [comment]
This should help. But you don't have a question so it's hard to say.

Good luck!

**Comment by Takecarecom** [comment]
we need to set StartDate and EndDate and CustomerID custom parameters of our CustomerGrossSalesListRequest

**Comment by edwardch** [comment]
Ok cool, then what I posted above will do the trick... I also have an ID field that is a parameter to a stored procedure and that's the code I used on my Grid.ts.

For the dates, the code from the example that you pasted above will also work.

Remember to run your T4 transformations so that any script keys get recognised.

**Comment by Takecarecom** [comment]
Thank You @edwardch
