### ISSUE TITLE
how to assign value to a field based on substraction of two fields.

### ISSUE THREAD

**Issue by rajashekargoka** [volkanceylan/Serenity#4337]
I have a Login Table with LoginTime and LogoutTime am using TotalHours like 
` [Expression("([LogOutTime] - [LoginTime])", Dialect = "SqlServer")]
        public TimeSpan? WorkHours  {get... set..}`
 here LoginTime ,LogoutTime,totalhours are of Timespan.
when am working with this
its throwing error  System.Data.SqlClient.SqlException: 'Operand data type time is invalid for subtract operator.'can anyone help me to fix this..

**Comment by edwardch** [comment]
When working with dates in SQL you can subtract them by using the DATEDIFF function. 

Expression would be something like: 
```cs
[Expression("(DATEDIFF(SECOND, [LogInTime], [LogOutTime]))")]
```
And store this as TotalSeconds, as an integer or big integer.

Use seconds because it is more precise, and you can easily convert seconds to hours when presenting data to the user on the screen/grid or in a report.
