### ISSUE TITLE
users logged in system

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#4340]
Dear,
I need to view the users who are logged into the system. How to make?

**Comment by JohnRanger** [comment]
Hmm,

the problem imho. is that the serenity app is a stateless web application (it loads a page and then does nothing anymore). So you theoretically _could_ set a flag (additional boolean/bit field) within the users table on the user's record when he/she logs on and clear that flag when they log out of the app - but the problem is that they can close their browser (or enter a different url) without notifying the serenity app.

So they could "sneak" away from the serenity app in reality but your user's record would still state that the user is logged on.

So the question is: How precise/reliable is your need of "who is currently really logged on or not" - and how many users are expected max. to be connected at a single point in time.

If it is sufficient to know it by a precision of - lets say - 15 mins, you could implement a client-side scheduled call to an endpoint (MVC Controller) on the server side where the cliend-side of the serenity app sends the user's id every 15 minutes and store a is-alive timestamp within the user's record.

Then, when you need to know who is currently logged on (has been logged on at least max. 15 mins ago) you simply query the users table and filter on the is-alive timestamp <=15 min from now.

then you have a list of all users which are currently logged on (or have moved away from the serenity app less than 15 mins ago).

Another possibility would be to implement a SignalR hub (Websocket+) and push a "are you alive" request to all SignalR clients (your serenity app users' webbrowsers) and all browsers which are still showing the app can silently send the user id back to the SignalR hub in realtime. So this would be a realtime way of knowing, who is really currently using the serenity app.

The feasibility of this depends of course how many users do you expect to use your app max. at a given point in time and how often you need to know who is currently logged on.

Hope this gives you some ideas.

With kind regards,

John

**Comment by ga5tan** [comment]
Yeah, it would be sweet to keep track of them, how long they have been on site, or what they did...

**Comment by volkanceylan** [comment]
Just add lastactivity column to user table, update it on request start

**Comment by stixoffire** [comment]
@juliermefelix 
Actually if you look into the WIKI for Signal R you will find in the NotificationHub where this is being done - perhaps you could utilize something similar (or if you implement SignalR - that would be a way to do it.

**Comment by ga5tan** [comment]
thx man, it's only year later :) but we still did not get down to it.
are you talking about this?
https://github.com/volkanceylan/Serenity/wiki/Realtime:-Group-notifications-with-SignalR-(by-marcobisio)

**Comment by stixoffire** [comment]
@ga5tan 

Yes - that is it look at the notification hub .. I know it is a long time ago and a roundabout way to do it .
I understand about getting back to things a year later .. Man I am a one man deal and the hats I am wearing .. busy. 

But you could also do it in the log in  to add the user to a static list field in your project - you can access a static field like that from any webpage and any client .. 
The difference is that you will need to remove the user that logs out from that list ..

```
static class MyWebRootStuff  
static list List<Users> MyWebRootUsersList {get; set;}
```

Keep in mind when you do this - it is accessible from any and all your clients .
