### ISSUE TITLE
Show orders grid in orders form

### ISSUE THREAD

**Issue by TechAspirant** [volkanceylan/Serenity#4375]
Hello,

Is there any way I can show order grid in order form ? I want to show all the previous records present in order table in form of grid in order form.

**Comment by ga5tan** [comment]
master detail ?
or just instantiate grid in form

**Comment by TechAspirant** [comment]
No master detail. I want to show grid of same entity on form.

**Comment by JohnRanger** [comment]
@TechAspirant ,

is the grid just to be statically showed or does it need to have some interaction like sorting, filtering and "opening" a different form instance when clicking on a row/editlink in the grid?

Because your requirement more or less seems to technically resemble what is the entityGriddialog in paid StartSharp (see demo here: https://serenity.is/demo/AdvancedSamples/EntityGridDialog#).

With kind regards,

John
