### ISSUE TITLE
"Editor" error message while creating an Editor For Movie Cast List

### ISSUE THREAD

**Issue by denonc** [volkanceylan/Serenity#44]
Hi,

I have encountered 2 error message while trying to create Editor List similar to MovieCastEditor : 
1) CS0104 'Editor' is an ambiguous reference between 'System.ComponentModel.EditorAttribute' and 'Serenity.EditorAttribute'	TestFeature.Script	../PermissionCheckEditor.cs	11
Severity	Code	Description	Project	File	Line
2) CS0104	'Editor' is an ambiguous reference between 'System.ComponentModel.EditorAttribute' and 'Serenity.EditorAttribute'	TestFeature.Script	../PermissionModuleEditor.cs	12

The error show up after creating the new editor type and rebuild solution, before proceeding to transform all t4 templates. I had saw the same error message when using V1.5+ and had caused some issues which makes me decided to work on the latest v1.6.3, but still same error message appear. The visual studio using now is 2015 community edition.

Thanks to advise for the error message!

**Comment by ademc** [comment]
Remove System.dll reference from Script project and try rebuild.

I faced same issue before, it is very interesting that serenity do not like System.dll :)

**Comment by denonc** [comment]
Wow, thanks for the solution! Yeah, this is really a strange thing.. Thanks ademc!

**Comment by volkanceylan** [comment]
This is not a problem with Serenity, but Saltarelle compiler uses a specialized mscorlib and don't have System.dll. This means you can't add reference to a regular .NET assembly, including System.

Unfortunately, if you used File -> Add -> New in Visual Studio, it automatically adds reference to System.dll, that's why i always use copy paste for creating new files.
