### ISSUE TITLE
Use captured webcam image

### ISSUE THREAD

**Issue by juliermefelix** [volkanceylan/Serenity#4477]
Dear,
I am using a WebCam to capture image, I need the captured image to be automatically inserted into the "Photo" field of xyzDialog.
In xyzDialog I put a button to call the capture window of the WebCam, in the open window click the "Fotografar" button and the image is captured, I need this image to be placed in the Photo field of xyzDialog.
![image](https://user-images.githubusercontent.com/7516443/59268109-656e1280-8c22-11e9-928e-9891828af5a6.png)

**Comment by JohnRanger** [comment]
Hi @juliermefelix ,

I don't think that is possible because of security reasons (the Upload button is very restricted) and because you don't want to force the user to first save the image to local disk and then to upload it via the upload file button. 

Where is the image data directly stored after the capture? Within a client-side browser variariable? 

If yes, then copy the data into a hidden byte[] serenity form field and then it gets automatically directly inserted into the database (use a varbinary(max) field to store it on SQL side) when saving the whole record. I have stopped to use the upload file shelf for permanent image storage and put everything as a binary blob into the Database. Works much faster and much more reliable than relying on the upload folder (except when letting the user browse for a local file and upload this then I use the upload folder shelf and then do immediately an import and delete of the uploaded file when saving the record on the server side).

Hope, this helps.

John

**Comment by juliermefelix** [comment]
Dear @JohnRanger ,
I'm using the option to write the image to a folder and then the user upload it.
I believe that to work would have to change the upload button to open the camera, similarly as it does when running on mobile, or create another function to replace the ImageUploadEditor

**Comment by JohnRanger** [comment]
Hmm, 
as I have experienced it with all usual browsers, the ability to control the upload button (e.g. in which path it should default, etc) is absolutely limited (for security reasons). But as your camera seems to have a web server it should be possible to either directly fetch the picture from the ip camera out of serenity / javascript client-side (see som generic javascript example here: [https://stackoverflow.com/questions/8850233/jquery-fetch-jpeg-image-from-ipcam](url) or fetch the image from server side (a generic example you can find here: [https://www.aspsnippets.com/Articles/Capture-Image-Photo-from-Web-Camera-Webcam-in-ASPNet-MVC.aspx](url)).

This is much more convenient for your users and the workflow is much more controllable by you / Serenity.

 Check the Web-API of your camera. If you don't get to this information, check out this project: [https://www.ispyconnect.com/](url). Just download and install it - and then add your camera. It supports 1000s of ip cams - so yours will most probably be supported. And then just poke around in the app to see how it does the connection (normally this is done via one URL which includes many parameters like UID, Password and sometimes the desired graphical output format.  If he cam works in iSpy and you don't figure out how it calls to the cam, then install a network niffer app (wireshark or MS Network Monitor 3.4) and capture the traffic between your iSpy computer and the cam. You will immediately see the format of the URL it is using. 

Hope this helps,

John.

**Comment by JohnRanger** [comment]
Hi @juliermefelix ,

if this issue has been resolved, would you mind to close it? :-)

With kind regards,

John
