### ISSUE TITLE
How to  send data from one editor to another

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4502]
Hello everyone! I want to send the Editor data to other Editor from the same form.cs
couldn't find any solution regarding this
Please help

**Comment by wezmag** [comment]
Bind a `change` event to the editor, and change the value of another editor.

``` typescript
@Serenity.Decorators.registerClass()
export class OrderDetailDialog extends Serenity.EntityDialog<OrderDetailRow, any> {
    protected getFormKey() { return OrderDetailForm.formKey; }
    protected getIdProperty() { return OrderDetailRow.idProperty; }
    protected getLocalTextPrefix() { return OrderDetailRow.localTextPrefix; }
    protected getService() { return OrderDetailService.baseUrl; }

    protected form = new OrderDetailForm(this.idPrefix);

    constructor() {
        super();
        //bind change event here
        this.form.Width.change(() => {
            this.form.Height.value = this.form.Width.value;
        });
    }
}
```

**Comment by Shraddha996** [comment]
hello @wezmag  Thanks for the quick response
actually, I want to access the current entityId on one of my editors when updating records

**Comment by JohnRanger** [comment]
Hi @Shraddha996 ,

may I kindly ask why you would need this?

I ask this, because ormally, detail records are modified/stored in-memory and automatically saved/updated/deleted on save of the master record. This is built-in functionality of master-detail and you don't have to care about storing the master's ID in the detail record's foreign key field to keep master record and detail records together.

With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger I actually would like to know how to do this ; there is a special situation where I need to add multiples at the same time from my editor and in order to add rows to the in memory grid they are of type for an intermediary table of Position_Training. I select multiple training rows for the Position but I do not have the position data for the new row to place in the grid - if a single record exists already I can get the required info from there and this does work how I desire it to work. 

If no records exist I need to  access that data .. I know it is there somewhere - just don't know where.
