### ISSUE TITLE
Authorization Denied to call Create Service with Postman

### ISSUE THREAD

**Issue by MaziarSangi** [volkanceylan/Serenity#4519]
I want to call Create Service of my Class with Postman and need to Authenticate before send request to Serenity.
I have set Authorization tab in Postman with  (Basic Auth) Type  with Username and Password of Serenity App.
Butt always It returns Authorization Denied to call service. 
I don't know how to solve it!

**Comment by wezmag** [comment]
Serenity uses ASP.NET FormsAuthentication for authentication and authorization. 
If you want to use Postman to call service endpoints.
First, you need to call `http://localhost:53875/Account/Login` with Username and Password to obtain FormsAuthentication cookie.
![Image 1](https://user-images.githubusercontent.com/340794/60798055-0230bb00-a1a3-11e9-9ec9-e735fc56e870.jpg)
Afterwards, you can then call service endpoint along with the cookie.
![Image 2](https://user-images.githubusercontent.com/340794/60798797-70c24880-a1a4-11e9-8de4-a28a20ff67cc.jpg)
*Don't forget to change the port number.

**Comment by MaziarSangi** [comment]
@wezmag 
Thanks for Answering 
I received 400 Bad Request When called /Account/Login service in Postman.

**Comment by MaziarSangi** [comment]
Solved by adding [IgnoreAntiforgeryToken] on Login Method.
Thank you so much.

**Comment by fwd079** [comment]
An Update that this does not work in ASP.NET CORE version of Serenity:

> *Don't forget to change the port number.

![image](https://user-images.githubusercontent.com/7912632/77955492-323b6380-72c8-11ea-87b6-8d619f0e317c.png)

You need to go via form data values (either form-data or x-www-form-urlencoded way) and then it works, I am guessing here that it still uses form data instead of json if we call it externally (outside Serenity, from a console app, for example).

![image](https://user-images.githubusercontent.com/7912632/77955709-93fbcd80-72c8-11ea-846b-0ec6624d13cf.png)


Regards.

**Comment by ziaatrix** [comment]
@fwd079,

I tried to use form-data or x-www-form-urlencoded to pass the request parameter to retrieve List but it is not working. Any idea?

![image](https://github.com/serenity-is/Serenity/assets/118987818/9043caf0-c25f-4565-a258-d1201713bc61)
