### ISSUE TITLE
[Tutorial] Using Hangfire Background Jobs with Serenity

### ISSUE THREAD

**Issue by edwardch** [volkanceylan/Serenity#4593]
Hi Serenity contributors and members!

I've just added a Wiki entry on you to set up background tasks with Serenity: [Using Hangfire Background Jobs with Serenity](https://github.com/volkanceylan/Serenity/wiki/Background-Tasks:-Using-Hangfire-Background-Jobs)

Sorry to use an issue to announce this, I'll close this issue in a few days. 

I hope somebody finds this useful, please give feedback if something doesn't work or is confusing.

Edward

**Comment by samdubey** [comment]
Hi @edwardch edwardch,

following package got restored using ASP.NET  4.6.1 than .NET Core 2.2

Please advice.

1>------ Rebuild All started: Project: RioLMS.Web, Configuration: Debug Any CPU ------
1>E:\RioLMS\RioLMS\RioLMS\RioLMS.Web\RioLMS.Web.csproj : warning NU1701: Package 'Hangfire.Dashboard.Authorization 2.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
1>E:\RioLMS\RioLMS\RioLMS\RioLMS.Web\RioLMS.Web.csproj : warning NU1701: Package 'Owin 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
1>Transforming MVC at: E:\RioLMS\RioLMS\RioLMS\RioLMS.Web\Imports\MVC
1>Transforming ClientTypes at: E:\RioLMS\RioLMS\RioLMS\RioLMS.Web\Imports\ClientTypes
1>RioLMS.Web -> E:\RioLMS\RioLMS\RioLMS\RioLMS.Web\bin\Debug\netcoreapp2.2\RioLMS.Web.dll
1>RioLMS.Web -> E:\RioLMS\RioLMS\RioLMS\RioLMS.Web\bin\Debug\netcoreapp2.2\RioLMS.Web.Views.dll
1>Transforming ServerTypings at: E:\RioLMS\RioLMS\RioLMS\RioLMS.Web\Imports\ServerTypings
1>Done building project "RioLMS.Web.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by edwardch** [comment]
Hey @samdubey I have updated the guide

You need to **remove** the `Hangfire.Dashboard.Authorization` package.

I left that there by mistake, and I didn't check my warnings when testing with .NET Core.

I had only been testing in Windows, but confirmed this works when deploying to a linux docker container.

Good luck

**Comment by samdubey** [comment]
It worked thanks
