### ISSUE TITLE
Show a StreamField in the grid

### ISSUE THREAD

**Issue by leovamos** [volkanceylan/Serenity#4615]
Hi, guys

So, I have a problem. I need to show a StreamField in the grid, and I'm using the same method used in Multiple Genres for a single Movie: retrieving the ID for every genre associated to the movie, then using a formatter to convert this ID for the genre name.
In my case, I want to show all the Hashes an App has. But these Hashes are StreamField when they come by Sergen (being binary in SQL). Using the formatter, the only fields capable to show are ID and UniqueName. The field of interest is CertificateHash.
I was thinking of creating a new Interface for StreamField, like IIDRow and INameRow, but I don't know if I really need to do that.

`

    [ConnectionKey("Smic"), Module("Smic"), TableName("[dbo].[AppCertificateHash]")]
    [DisplayName("App Certificate Hash"), InstanceName("App Certificate Hash")]
    [ReadPermission("Administration:General")]
    [ModifyPermission("Administration:General")]
    [LookupScript("Smic.AppCertificateHash")]
    public sealed class AppCertificateHashRow : Row, IIdRow
    {
        [DisplayName("App"), ForeignKey("[dbo].[App]", "AppId"), LeftJoin("jApp"), TextualField("AppUniqueName")]
        public Int32? AppId
        {
            get { return Fields.AppId[this]; }
            set { Fields.AppId[this] = value; }
        }
        [Identity,PrimaryKey]
        public Int32? HashId
        {
            get { return Fields.HashId[this]; }
            set { Fields.HashId[this] = value; }
        }

        [DisplayName("Certificate Hash"), Size(32)]
        public Stream CertificateHash
        {
            get { return Fields.CertificateHash[this]; }
            set { Fields.CertificateHash[this] = value; }
        }

        [DisplayName("Status"), NotNull]
        public AppHashStatus? Status
        {
            get { return (AppHashStatus?)Fields.Status[this]; }
            set { Fields.Status[this] = (Int16?)value; }
        }
`

The formatter is:

`

    @Serenity.Decorators.registerFormatter()
    export class HashFormatter implements Slick.Formatter {
        format(ctx: Slick.FormatterContext) {
            let idList = ctx.value as number[];
            if (!idList || !idList.length)
                return "";

            let byId = AppCertificateHashRow.getLookup().itemById;

            return idList.map(x => {
                let g = byId[x];
                if (!g)
                    return x.toString();

                return Q.htmlEncode(g.CertificateHash);
            }).join(" - ");
        }
    }

`

But g only have two field when debug is running, Id and UniqueName

Any suggestion is welcome.

**Comment by JohnRanger** [comment]
Hi @leovamos ,

why not making the streamfield a hidden field in your form and add an in-memory-only string field to your xyzRow.cs and in the form and then in your xyzDialog.ts in the afterLoadEntity event, convert the streamfield to a string and update the in-memory-only stringfield with that value.

This would at least solve it for the form/dialog.

For the grid, there is also an overwritable method in xyzGrid.ts to format the output (e.g. fill the in-memory-only field row by row) but I don't have right now access to any of my projects where I have used this in the past.

Hope this helps a bit.

With kind regards,

John

**Comment by JohnRanger** [comment]
@leovamos ,

regarding the missing has field in the formatter - because you use a lookup for your byId variable
- and you didn't specify the hash field to be included in lookup, it is not there. Id is alwys there and namefield.

Modify the hash field in the xyzRow.cs like this:

```cs
 [DisplayName("Certificate Hash"), Size(32), LookupInclude]
```
Then build + Transform T4 template.

After that the missing hashfield will show up in "G".

With kind regards,

John

**Comment by leovamos** [comment]
@JohnRanger you're amazing!

Your solution worked. It's showing the value of the hashes in the grid, thank you a lot.
Now, I want to understand what was done: why LookupInclude is necessary?

But I have another problem: 
The form must show the values in the dropdown ​​as well, but they appear blank. It looks like it finds all the values, because it shows a list, but all the values are blank, so I can't select them.

Anyway, thank you so much for your help.

**Comment by leovamos** [comment]
I know that some Rows have NameField and it is responsible for show a StringField of the row in many areas of the site, like DropDowns lists (like the tutorial, showing the movie name in MovieRow). But in that case, AppCertificateHashRow doesn't have any StringField, and again, it should show the CertificateHash field, which is StreamField. How to proceed with that? That's the question.

**Comment by JohnRanger** [comment]
Hi @leovamos ,

no - I am not amazing - just an long-time Serenity Framework user :-). Really amazing here a guys like MarcoBisio, MinhunIt, Ga5tan, killroyFR, Brunobola and dfaruque - and of course Volkan. (and I surely have missed a few others).

------------

The reason why only fields with the [lookupInclude] tag are included in the lookup scripts is performance and reduction of network traffic between client- and server-side. 

These Lookup scripts are generated (re-created) each time when the data in the underlying table gets changed (when the data is edited via the official Serenity Framework's functions - Beware: Just updating data in the table e.g. via SSMS **does not** update the corresponding lookup scripts). 

And each time something on the client-side needs accessing data in these lookup scripts, the framework checks if the script has changed and if yes, it has to re-fetch it from server-side. Therefore it would be extremely bad to just add all fields of the xyzRow.cs by default into the lookup script. Therefore Volkan has wisely added the possibility to selectively add the required fields to the lookup script with the [LookupInclude] tag.

Please note that the data on the client-side is not queried in Realtime from the database e.g. when filling the dropdown of a form field which has a lookupeditor attached. This is all cached data coming from these pre-created lookup scripts. 

Hope this answers your [lookupInclude] question.

with kind regards,

John

**Comment by JohnRanger** [comment]
@leovamos 

 Regarding your question of how to get some visible values in the dropdown:

I believe that - if I regard your overall situation - the easiest solution would be to have a calculated field directly within your database which is of type nvarchar and contains the hash in string (nvarchar) form of the binary hash field of the same record. 

Then you could just map this additional field within your xyzRow.cs (the lookup row) and define this calculated field as the namefield.

Assuming that you are using Microsoft SQL server, have a look at this article here about how to generate calculated fields in MS SQL: https://www.sqlservercentral.com/articles/using-computed-columns

If your RDBMS is not Microsoft SQL, then the next (more complicated) possibility would be to fill the dropdown (is a jQuery select2 element) completely by your own code (e.g. attach an empty lookupeditor to the field where you normally would attach the lookupeditor (see https://github.com/dfaruque/Serenity.Extra for the empty lookupeditor) and then fetch the data (a list of IDs and Hashtexts) from server-side via an endpoint (see in general my answer in your other issue). On the server side in the endpoint (or the xyzRepository behind it) you can easily convert the binary hash into a string and then return it to the client-side where you just iterate through all returned  "records" (the elements of the returned list) and add those items to the select2.

Does this hlep you?

With kind regards,

John

**Comment by leovamos** [comment]
Thanks for the help, @JohnRanger.

I ended up finding another way with the people who work with me and it's working out apparently. Thanks for your help, and I would like to know where I can learn more about these attributes and the logic of Serenity. I already did the tutorial, but I feel that I don't know how to fully use the features of it and also ASP.NET MVC, like the attributes.

Thank you very much

**Comment by JohnRanger** [comment]
Hi @leovamos ,

glad that you could solve this problem :-)

---------------

I did the serenity guide (was in old times a downloadable pdf but has now moved to : https://serenity.is/docs 

And then hang out here in the serenity issues and learn of the problems of other people - and their solutions - and ask questions here.

Most of my knowledge of Serenity Framework however comes of having an idea, trying to solve it - then look at the Serenity demo (search for something similar - and if not found, google for infos outside Serenity framework.

Often the problem is a javascript/typescript or slickgrid problem. Or if on server side, it is either an ASP.NET MVC, dapper framework or a MS SQL server thing. I can solve a lot of the problems with infos from outside of he actual serenity framework. Stack Overflow is a good friend of mine :-)

As Volkan has said somewhere in his intro to the Framework: It is made up of a carefully selected list of already existing open source frameworks (and a lot of his own genius stuff, putting this all together ins a rapid development framework).

Key to start your search for infos at the right place is to make a good guess what areas/frameworks (or client-side/server-side) are involved by the problem you want to solve.

And then do your research. While researching, you will encounter a lot of information which does not help to solve your current problem - but will you help later to solve other problems (at least you will know where to search for that later info).

That's called "experience" :-)

And if this does not help you solve a specific problem within a SF app, you always can ask here in the SF issues. As you can see, people are willing to help.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi @leovamos ,

and don't forget to close this issue as it is resolved :-)

Thanks and

with kind regards,

John

**Comment by leovamos** [comment]
Thanks for you help and for the tips, I surely will remind all of that. Many thanks, @JohnRanger
