### ISSUE TITLE
Not Null fails to validate when blanks are provided for a String data types

### ISSUE THREAD

**Issue by PAAutofac** [volkanceylan/Serenity#4623]
Hi,

Has anyone noticed within the Dialog any Required/Not Null fields user can bypass the validation or Red highlighter around the text area by providing a blank spaces.

Is there any thing within Serenity validation that can catch this type of bypassing blank spaces?

Thanks,
PA

**Comment by edwardch** [comment]
Check [#739](https://github.com/volkanceylan/Serenity/issues/739) and then also docs on [Field Flag Enumeration](https://serenity.is/docs/entities/fieldflags_enumeration)

Make sure it trims the field to null, and you can also add custom validation in your xyzRepository if you need, but you shouldn’t need custom validation if the trim is set correctly.

**Comment by PAAutofac** [comment]
Hi Edward

Thank you for the reply. Could you please explain with an example/sample .
It isnt clear.as I am new to serenity.

Thanks,
Pa

**Comment by volkanceylan** [comment]
This issue is caused by a change in jQuery validate itself. It used to trim spaces before validating required fields before, but not anymore.

https://github.com/jquery-validation/jquery-validation/issues/1886

We'll add a default normalizer function to Q.validateOptions as a workaround, you may edit CoreLib.js for now and add a normalizer.

**Comment by volkanceylan** [comment]
This issue is solved in recent versions by adding a trim function.
