### ISSUE TITLE
[BUG] paging with SqlServer dialect 2005+2008

### ISSUE THREAD

**Issue by hannesb** [volkanceylan/Serenity#4626]
I just ran into a bug with paging and the SQL Server 2008 dialect (same with 2005). Let's say you have a grid with page size set to 20 and navigate to page 2. The generated query will look like this:

SELECT * FROM (
  SELECT TOP 40 
  T0.[Field1] AS [Field1],
  T0.[Field2] AS [Field2],
  ROW_NUMBER() OVER (ORDER BY T0.[Field1], T0.[ID]) AS __num__ 
  FROM [dbo].[Table1] T0
) __results__ 
WHERE __num__ > 20;

The generated query uses a TOP clause without an ORDER BY!

The correct query has to be:

SELECT * FROM (
  SELECT TOP 40 
  T0.[Field1] AS [Field1],
  T0.[Field2] AS [Field2],
  ROW_NUMBER() OVER (ORDER BY T0.[Field1], T0.[ID]) AS __num__ 
  FROM [dbo].[Table1] T0
  ORDER BY T0.[Field1], T0.[ID]
) __results__ 
WHERE __num__ > 20;

The ORDER BY of the ROW_NUMBER() construct has to be repeated.

For some reason, most of the time the SQL Server chooses an execution plan that gives the expected result, but not always...

**Comment by JohnRanger** [comment]
Hi @hannesb ,

as both of these MS SQL versions are now even out of MS extended support (https://blogs.msdn.microsoft.com/sqlreleaseservices/end-of-mainstream-support-for-sql-server-2008-and-sql-server-2008-r2/) I would recommend to move the SQL backend up to a supported version.  Not many will still run such elderly versions of MS SQL so the chance that this will get fixed - if it does not also affect newer MS SQL versions is relatively low I guess. 

With kind regards,

John

**Comment by volkanceylan** [comment]
I think this is the commit that introduced this bug (pull request by dfaruque for theorically fixing an Oracle issue):

5dc4e94cc3ea4cc11d903a7bf1d2b1a97bb43e9a

I guess i should be more careful before accepting pull requests.

**Comment by kilroyFR** [comment]
The comment regarding the missing of the second 'ORDER BY' in main query is because use of TOP command at the beginning.
When using OracleDialect the generated code looks like (see following example) :

SELECT * FROM 
( SELECT  T0.MESSAGE_ID AS "MESSAGEID", T0.MESSAGE_TYPE AS "MESSAGETYPE", ROW_NUMBER() OVER (ORDER BY T0.MESSAGE_ID DESC) AS numberingofrow  
FROM BOL_MESSAGE T0   ORDER BY T0.MESSAGE_ID DESC) 
WHERE numberingofrow > 0 AND ROWNUM <= 100

which is almost correct but the additional 'ORDER BY T0.MESSAGE_ID DESC' is useless (and is degrading performances a lot).

Query generated this way : (without the duplicated 'ORDER BY T0.MESSAGE_ID DESC') is definitively better.

SELECT * FROM 
( SELECT  T0.MESSAGE_ID AS "MESSAGEID", T0.MESSAGE_TYPE AS "MESSAGETYPE", ROW_NUMBER() OVER (ORDER BY T0.MESSAGE_ID DESC) AS numberingofrow  
FROM BOL_MESSAGE T0) 
WHERE numberingofrow > 0 AND ROWNUM <= 100

**Comment by kilroyFR** [comment]
@volkanceylan  as long as TOP keyword is not used to retrieve data, the duplicated ORDER BY clause is useless (it decreases query performances for nothing).
Gonna make a pull request for this.
