### ISSUE TITLE
Inserting a Large Amount of Rows as fast as possible.

### ISSUE THREAD

**Issue by MarcusOy** [volkanceylan/Serenity#4633]
Hi there,

I am trying to insert a large amount of rows as quickly as possible. These rows pretty much have a bunch of foreign keys and an integer, so I'd consider them relatively small. In a single process, I could be looking at around 10k to 100k of these rows that I would need to insert at a single given time.

What are some things I should keep in mind while doing such task? At the moment, I am using a foreach loop that iterates through a List of these rows and using this line of code to insert the row to the db:
`connection.Insert(DataRow[x]);`

I've tried a process with about 12k rows and that took around 7 minutes to complete. Is there anything I can do to speed up this process? If not, should I look into solutions to perform this in the background, and if so, how? Many thanks in advance.

Best Regards,
Marcus

**Comment by kilroyFR** [comment]
For these kind of situations bulk insert is THE way to go, definitively.

**Comment by edwardch** [comment]
@kilroyFR do you use something like SqlBulkCopy, or something else (paid-for Dapper Plus)?

I'm curious because I have used SqlBulkCopy, which seems to work, but maybe what you are referring to is the right way, or maybe just another way. 

@MarcusOy even when you're using bulk inserts you might want to consider splitting your inserts into smaller batches, especially if you need to insert 100k + records. E.g You could split them into batches of 10k.

**Comment by MarcusOy** [comment]
@kilroyFR I am using SQLServer (hosted on Microsoft Azure). 

@edwardch I will take a look into this.

**Comment by kilroyFR** [comment]
yes i am referring to SqlBukCopy. it also works with Oracle (using OracleDataAccess driver - not the managed one thought)

**Comment by volkanceylan** [comment]
I usually prepare insert statements, get the DebugText of the query (might not work with all server types, only SQL server), add them to a List<string>, then partition them into batches with 500 insert statements or so and execute.
