### ISSUE TITLE
how to use the column-level encryption  and decryption of SQL server in serenity

### ISSUE THREAD

**Issue by dhanrajKumbhar** [volkanceylan/Serenity#4642]
I have a user table with multiple column
I want to add column level encryption for MobileNo and EmailID column
It decrypted when I fetch List or retrieve from repository 

Is it possible 
Thanks

**Comment by JohnRanger** [comment]
Hi @dhanrajKumbhar ,

if I understand your requirement correct, you want that the encrypted column value contains to be encrypted until you decrypt it on the user's device.

This - according to my understanding of colum level encryption - is not possible (see here for how it works: https://blog.netwrix.com/2019/06/13/sql-server-encryption-explained-tde-column-level-encryption-and-more/).

Because the SQL driver (SQL client) is on the webserver where the Serenity code is running, it must be decrypted there and then send over whatever connection to your web browser. In order to protect the  content between webserver and browser, use a decent TLS encryption (https) between your webserver and your webbrowser. This is secure. Just make sure that your webserver is patched and otherwise secured (physically and by network firewalling.

With kind regards,

John

**Comment by dhanrajKumbhar** [comment]
@JohnRanger Thanks for your replay

**Comment by teafmartins** [comment]
Hi @dhanrajKumbhar, did you find any solution for your problem?
