### ISSUE TITLE
Discussion about Serenity Policies

### ISSUE THREAD

**Issue by mafdy** [volkanceylan/Serenity#4648]
Hello Dear @volkanceylan and all of Serenity Community.

No one can deny that Serenity is a great template for developers. You did a great and Declarative tool and it has become very popular (546K installs in marketplace), yet this is not the whole picture, there' something wrong.
Why I'm saying this? 
There's many fundamental things had better to be reviewed, for good of serenity (I don't know all of them, and many aren't in my mind now, but I'll wrote some of them):

1- Technical improvement:
-- GitHub issues for issues only and create a "Serenity Forum" for community (It will handle so many problems).
-- The way serenity upgraded and contributed and to be known for world of developers must be enhancement.
-- Maybe you should consider to change the commercial licence packages, or the Services which are offered by Serenity for great income which will be a sponsors to achieve great improvements.

2- On the other hand, humans improvement:
-- How to make contribution are something beloved for contributors,
-- How you can benefit from community support.
Let me set an example:
@minhhungit @Estrusco @dfaruque @marcobisio @hannesb @DucThanhNguyen @rolembergfilho  @JohnRanger and many other contributors  made an undeniable and great efforts for serenity by contribution, yet many time you wasn't encouraging enough for them. On the contrary, some times your replays for some of their issues or pull requests were very disappointed. 
I just saw what happens between you @volkanceylan  and @minhhungit in issue #4634 , does it really worth to be handled like this way??? He is not only a contributor, but also make some of his customers to buy Serenity package!!! "there something called private message for handling such a problem".

That happens to me also, I was so exited to contribute many time (Dynamic report viewer, chat with SignalR, etc) but many bad situations happens and this was so hard from your side, I even made some pull requests but you just ignored them, that cause me to stop working with serenity from around a year ago, just was trying to keep the old projects running well with some upgrades and new added modules, but any new project I choose to work with any other template instead of Serenity as a result of what happens earlier.
I accidentally found a repository with StartSharp template while I was seeking to fix an issue I ran into, It's a public for any one (I Don't know it's owner, and maybe its public without he notice that), yet I refused to use it as it against my ethics and moral laws, but (with my all respect) you aren't friendly enough with community so I can tell you to take it into consideration.  

-- And so many others, just ask Serenity community and you will be surprised for their ideas.

Regardless of what I have written (Consider it all wrong), just please review all things about Serenity (For the future of serenity and for your efforts value). And please try to make sure you are on the right track. 
Consider it as advice from a brother to you.

You can delete this issue if you want, or even block me.

With my best regards
Mafdy

**Comment by JohnRanger** [comment]
Hi @mafdy ,

thanks for your thoughts which - at least I - appreciate.

Actually - I like the "issues" way to ask and solve problems which I have with using Serenity (because the search of github within issues is just great - and I find old things very fast - and Github nearly guarantees that these "issues" will stay available "forever") - although it takes a bit more effort to separate "real" issues with serene/serenity from the questions. But we have marked "real" issues in the past with "Possible bug". That always catched attention.

Within the last 10 years I have seen many useful websites just getting "off the air" (meaning they disappeared and I cannot find anymore the infos I once knew where to look for). So a rock-stable platform like Github which is backed by one of the most fortune IT companies of the world is IMHO better than a privately hosted forum.

----

I remember the "old" days when @volkanceylan was still working at the university of Istanbul and just the Saltarelle version of Serene was out. He helped me patiently and with great investment of his time to solve problems which at least 90% came from my clear lack of understanding how C#, the DOM, Javascript, HTML, MVC and all the other frameworks used in Serenity do work and how all this stuff can be cleverly combined. And this for free. So I deeply appreciate that and it showed me Volkan's real character. Also that he continuously updates the free serene/serenity stack until now.

-------

**Marketing** - or the lack thereof

But yes - I also think that marketing of Serenity is a bit lacking. I mean by that: 

- The extremely well written blogs here on the site do not have a new technical article since over 1.5 years
- The roadmap shows only one minor achievement in 2019 (and we are soon at the end of 2019)
- Resolved / inactive issues do not get closed anymore on a regular basis by the Serenity team
- The treatment of some well contributing people here (not me) in the "forum" could be a bit more sensitive

------

I deeply respect Volkan's courage and decision to try to make a living out of Serenity - which is not easy.  Probably the greatest thing Volkan could provide to his paying customers is consulting and the creation of custom features for either Serenity or StartSharp. This should IMHO be more announced here and on Serenity.is. I suggest to make an own subpage with consulting pricing and custom developing pricing - also showing some features already custom developed for customers (and not only showing them within serene demo).

I am not sure if the technical difference between Serenity free and Serenity StartSharp justifies the price. As I don't have access to StartSharp I cannot tell. The goal of course should not be to cripple the free SF but to add more features to StartSharp to make the difference bigger.

But what the whole Serenity Framework really demonstrates is the capabilities of its creator, namely:

- Have a big vision and put it into reality (and overcome all the obstacles on the way)
- Architectural Skills ( understand what business (and developers) requires, strategically understand and select the frameworks required, analyses the technical future of web development and guide SF towards it without braking everything of the past)
- Consulting Skills (can explain difficult things in an easy to understandable manner)
- Interdisciplinary programming skills (C#, MS SQL, Windows Server, Web development (DOM, Javascript, Typescript, Saltarelle, understands fast any new technology))

This is a very good "business card" for you - @volkanceylan. If I ever need a first class Consultant/Developer/Architect for a real big web app project, then I know where to find one :-). So it would make much sense that you promote your skills and abilities - e.g. on serenity.is.

------

With kind regards,

John

**Comment by marcobisio** [comment]
Dear @mafdy,
I'll skip the "Technical improvement" part (but let me say that I agree with @JohnRanger: private forum is a bad idea).
Normally I wouldn't even answer to your "issue" because I guess that github is the wrong place for this kind of "open letter", but considered that you mentioned me, well I'll give you my two cents.
Said that, I appreciate your sincerity, but imho you're making two mistakes:

- judging a guy that you don't even know
- taking all this thing too "personally"

You're speaking about "humans improvement" and humans relationship, but actually we are all just pressing keyboard keys from different places in the world...and this kind of interaction can't be classified as human relationship.
Maybe you should take a flight, go to Istanbul to meet @volkanceylan in person and only then you should consider "judging" him, but you cannot speak about empathy when we're using github to communicate.
Besides, probably you forgot that @volkanceylan is sharing his framework with us for free (excluding StartSharp of course), therefore he isn't obliged to answer to your issue or to your pull request: do you want some kind of SLA? Well buy the premium support and you'll get it.
And as a last bit, he answered to my issues so MANY times, even when the issues weren't directly related to Serenity itself (and even when the issue were related to my lack of skill in typescript, javascript, etc.), and he didn't ask me a single dollar for his support, so I guess that contributing to this project is just a way to say "thanks" and I don't expect nothing in return from him.

Regards
Marco Bisio

**Comment by mafdy** [comment]
Dear @marcobisio  and all, 
Please allow me to explain something important:
English isn't my native language, so, it's hard for me to choose the right words to make things clear enough. And this an example of what I'm talking about:
> You're speaking about "humans improvement" and humans relationship,
 
Regardless of what I meant, I confirm that I couldn't choose the right words. So,  please take that in consideration.

>  I guess that github is the wrong place for this kind of "open letter", 

I agree with you in that. In fact that's why I suggested a "Forum" instead of GitHub issues, beside that I noticed some problems occurs because of that issues need to be closed, and there's  no Milestone to keep things tracked and clear, and other many thing, but it's just an idea. If it good, why not, If it's not useful, then no problem it all. (I just want to highlighted it for discussion)

> * judging a guy that you don't even know

Of course I didn't meant to judge @volkanceylan , I just highlighted some situations, believing that they would disrupt the progress of serenity.

> * taking all this thing too "personally"

I didn't mean that neither, and when I mention some of my personal experience, that because I Just was trying to set an example of what I was trying to describe, no more.

Any way
It's just a "Discussion", which I hope that it may be useful for Serenity.

With Love and Regards to all
Mafdy

**Comment by minhhungit** [comment]
I think Github Issue is enough, we can search issue very easy, but maybe issue should be classified by labels, milestones...

![image](https://user-images.githubusercontent.com/2279508/66307192-fda8a980-e92d-11e9-8581-96738c369b3d.png)

and I also think 4rum is old way, nowadays not too much people use it. If we need 4rum we will need more effort, more moderstrators to manager it and it is not centralization (I mean you have to manage Github Issue, 4rum and even slack channel...)

So I personally comfortable with Github Issues !

**Comment by VictorTomaili** [comment]
Hello everyone,

Don't forget to Serenity Platform is OpenSource project what you can contribute. So if you wan't to developer forum instead github issues (I prefer github issues for only bugs etc.) you can create a blog, forum or use StackOverflow or something else.

**Comment by rolembergfilho** [comment]
Hi @mafdy 

I'm proud to have my name mentioned, and, of couse, a bit shame. The contributors i did is very small, like nothing, than Volkan did.

I have a special care with Serenity platform, because it was a mark, a deadline, when I decide to renew my knowledgments in Web development: I moved from ASP.NET web forms to ASP.NET MVC. A big change! And @volkanceylan  has a lot of patience to deal with my questions!

As a business man, I understand @volkanceylan angry and frustrated in issues: a lot of then are same, or repeated. I remembered a special one from Germany (if I mind): The guy ordered Volkan to look all code and point where it's wrong! That episode was special point to slow down and make StartSharp and payed support.

That's why I asked for a special citation about create a separated whatsapp, in order to talk with brazilian's developers in portuguese. You can check in #3599

And, for documentation, all issues talked in whatsapp are registered in our git: https://github.com/serenitybrasil/SerenityBrasil/issues

Why: I tried to do something to avoid worry @volkanceylan . He had a lot to do in serenity platform.

I suggest you do the same. Create a group in your location, country, continent. Register the issues in you git hub. And make it's open to share knowlegment.

To finish: a big thank's to @volkanceylan and other guys! This platform is amazing!

**Comment by BravoSierra** [comment]
I suggest a conference or a friendly gathering in Istanbul or anywhere else. That helps a lot in an Open Source community.

**Comment by volkanceylan** [comment]
Thanks to everyone for their support.

I'm not going to argue about critics, i know that temper sometimes can be a problem, and it may make you look wrong while you might be right.

About some StartSharp code being made public, i think i found who did that, he is a nice guy, and don't think he is aware that his repository is public (some other nice guy could warn him or us before, -- instead of forking). Anyway, such things happen and can't be completely prevented.

Serenity is here to stay, as i am also using it for hundreds of projects that i have to maintain, and i can't even dream of abandoning it. I'm not trying to force anybody to use it though :) If you find a better product for your needs, don't hesitate to use it.

**Comment by stixoffire** [comment]
@volkanceylan I appreciate the framework and I appreciate all of your helping others in this forum. 
Everyone needs to eat .. so there is no free lunch .. and this framework which you put together is appreciated as not only does it make it possible for you but it helps many others to do the same. To be perfectly honest I do think some people have been over the top in badgering you and fail to realize all the hard work that you have put into this framework. They don't mind putting a lunch in front of themselves using this framework  - but forget that you also would like to do the same. Since I am being clear here some have really made me want to reach out and 'instill' understanding. 

BTW: I have not seen a paypal donation link anywhere.

**Comment by SyndicateOfSwing** [comment]
Open up the whole thing and go the UMBRACO way... that's a working business model.

It's open source but there's a clear release cycle / release policy.

The community is key and the UMBRACO people are mostly there to teach and share their knowledge, which is a paying service.

And please... simplify the frontend... maybe it's time to really document the CSS system and allow people to move away from the "standard" design.

About those challenges : you may want to check what happened with the Sharepoint platform and how focusing on the basic server objects and their versatility and programmable access helped solve the old "interface" issues once and for all.

G

Serenity is awasome... but getting too big for a one-man show, Volkan.
