### ISSUE TITLE
Insert two fields of same row in form

### ISSUE THREAD

**Issue by leovamos** [volkanceylan/Serenity#4650]
Hi, guys, it's me again

My problem is as follows: I need to enter two information in the App form, Key and Value. Both are part of AppExtraRow. I don't know how to make each field fetch the right values. My attempt was to enter the Key field as NameField, but then Value would also have the Key values.

The fields of interest are the last two:
![smic_help_app_form](https://user-images.githubusercontent.com/38430921/66347054-d8b23780-e929-11e9-8322-94880c7e8844.png)

Here is how I made the code for both:
![smic_help_app_form_code](https://user-images.githubusercontent.com/38430921/66347065-dc45be80-e929-11e9-8868-ee42ed1bb0cd.png)

And here they are in AppExtraRow:
![smic_help_app_form_code2](https://user-images.githubusercontent.com/38430921/66347277-55ddac80-e92a-11e9-9392-b0d0df87c885.png)

By the way, both are byte array, and I imagine that to display this in Form there is some problem. In Grid I can create a Formatter as it is done in the tutorial.

Thanks in advance

**Comment by JohnRanger** [comment]
Hi @leovamos ,

 now I don't understand. Are these two fields similar like the hash field - I mean by that: Are these additional fields meant to pull their lookup data from the same "key/value source table" - one should have the key and the other should have the value? Sounds a bit strange to me. Can you quickly make a database diagram within SQL server and show us the relations between all these tables in graphical form?

With kind regards,

John

**Comment by leovamos** [comment]
Here it is, John

For App and AppExtra:
![smic_db_diagram](https://user-images.githubusercontent.com/38430921/66423577-5a659c00-e9e2-11e9-98c2-583069625287.png)

A portion of the schema:
![image](https://user-images.githubusercontent.com/38430921/66423649-78cb9780-e9e2-11e9-8f66-bdd16ac5e035.png)

**Comment by JohnRanger** [comment]
Hmm,

what I don't understand with your request: The appExtra key and value belongs together (are in the same AppExtra record). So it would only make sense to choose one record of the AppExtra table within a dropdown (LookupEditor) on AppDialog.

So the logic would be that you let choose the user on the AppDialog only the desired App Extra record (set the key field as your NameField within AppExtra table so that the key is automatically displayed within the dropdown. And then in the onChange-Event of the corresponding form field on AppDialog (the one with the AppExtra key), you will then query the AppExtra Lookup to get the value of the value field which you have tagged with [LookupInclude] in the AppExtraRow.cs - by using the AppExtraId value from the AppExtra Key field on the AppDialog.

And when you have so retrieved the value of the value field from the record, you just set this value to the value field (which must be a pure in-memory field tagged with [notMapped] in the AppRow.cs).

Then when your user within AppDialog chose a key from the AppExtra table, it also displays the corresponding value.

Regards,

John

**Comment by leovamos** [comment]
Hi @JohnRanger 

I tried your approach, what is similar with @luongnv6 in #4616, but I must admit, I am confused, 
not with your explanation but with the way how to do. What I tried is here:


The form is showing the key, with the NameField as KeyStr (a field that convert Key to String), but not showing Value:
![smic_help_app_form2](https://user-images.githubusercontent.com/38430921/66509522-a0396780-eaa9-11e9-9b6f-8abc7cc797dd.png)
![smic_help_app_form3](https://user-images.githubusercontent.com/38430921/66509520-a0396780-eaa9-11e9-9eb9-46b67c094b79.png)

Here are the codes for AppRow with the fields of interest:
![smic_help_app_form_code3](https://user-images.githubusercontent.com/38430921/66509634-d545ba00-eaa9-11e9-9f26-5fb9826196e7.png)

My doubt is if Value Field should be maintained like it is now or I should change it... Because I'm showing it in the grid too

Then ExtraLookup.cs and AppDialog.ts, respectively:
![smic_help_app_extralookup](https://user-images.githubusercontent.com/38430921/66509824-25bd1780-eaaa-11e9-9e2b-4d746aebc59d.png)
![smic_help_app_dialog](https://user-images.githubusercontent.com/38430921/66509832-29509e80-eaaa-11e9-8d6b-674c75bfc8f6.png)

**Comment by JohnRanger** [comment]
Hi @leovamos ,

either I don't understand fully what you want to achieve with the relation between App and AppExtra table and the 2 fields (Key and Value) - or you have a basic misconception of how these 2 SQL tables have to be related with each other :-)

Also I would not recommend using fields with the names "key" and "value" as these words do have special meanings either in SQL (Key) or within Serenity Framework (value) and thus can lead to confusion.

Rename them to something like AppExtraKey, AppExtraValue.

---

But the key concept is: You must only have one reference within the App record to the AppExtra table - and this must not be the key field but the Primary key of the AppExtra table - and this is AppId.

Actually it is bad practice to name the primary key field not similar like the table where it resides in. In your case this would be: AppExtraId.

And then you would put an AppExtraId field as the foreign key field within your App table - and then you set the correct relationship between these to tables via the AppExtraID field - depending on your need.

Either a 1:n or 1:1 relationship.

--------------------------------

You should remove the [notmapped] tag from your AppExtra key field as you will need to store the AppId (or better AppExtraId) from AppExtra table within App table's "key" field (but you must change this field to be the AppExtraId field) - otherwise you don't have any reference between these two tables - and you should not store the key's value but just the AppExtraId.

No lookupeditor on valuefield is required. This stays a simple text field. You will fetch the value with something like this directly from the lookup:

```ts
let AppExtraEntity = <yourNameSpace>.AppExtraRow.getLookup().items.filter(x => x.AppId.toString() === this.form.AppExtra.value)[0];
```

and then you simply update the value of the "value" field on AppDialog like this
```ts
this.form.value.value = AppExtraEntity.value;

If you don't understand my explanation, please ask your colleague which has already suggested to you the thing with the expression field. He surely can help you with a proper conception of how these 2 SQL tables must relate to each other. :-)

Kind regards,

John
