### ISSUE TITLE
Excell import error

### ISSUE THREAD

**Issue by HarunGazi** [volkanceylan/Serenity#4671]
When I click Import Excel button, I get the error as above, the window does not open.

SCRIPT ERROR! See browser console (F12) for details.
Message: Uncaught ReferenceError: CarilerExcelImportDialog is not defined

File: http://localhost:59952/Scripts/site/Serene.Web.js?v=MDid4AVSSU1HwMMNnl2ezw, Line: 2662, Column: 38

**Comment by JohnRanger** [comment]
Hi @HarunGazi ,

The error message tells it: You do not have a class called CarilerExcelImportDialog defined. 

If you think that you do have this class defined, maybe there is a spelling error or something like that.

Have a look within your xyzGrid.ts because you open the xyzDialog.ts from there. There must be some error shown in you xyzGrid.ts (look up the right side of your code window in VS).

Hope this helps.

With kind regards,

John
