### ISSUE TITLE
Save TextField in the Database NOT Id Field from Dropdown selection .

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4686]
I have a joined table (country) as part of my customers table.  I want to save the 3 letter ISO code into my Country Field of Customers table. I can save the Id value, and overriding the before save method - I can only see the country Id value, I cannot see the Iso3Code unless I do a separate query on that table I know I can modify beforeSave and afterSave in order to change the value to Iso3Code and then back to the value - but this seems so HACKISH .

I know by default Id is used in the dropdown value , should I just change the Idfield of ?? Not the countryrow because that will create issue for save country - I think ..

How can I do this a better way. 
My Customers Row 

Code example below:
```
        [DisplayName("Country"), Size(15), LeftJoin("jCountry", "[dbo].[Country]", "T0.Country = jCountry.CountryId"), TextualField("CountryName"), Width(80)]
        [LookupEditor(typeof(CountryRow),AutoComplete = true)]
        [DefaultValue(238)]
        public String Country
        {
            get { return Fields.Country[this]; }
            set { Fields.Country[this] = value; }
        }
        #region COUNTRY
        [DefaultValue(238)]
        [DisplayName("Country Id"), Expression("jCountry.[Id]")]
        public Int32? CountryId
        {
            get { return Fields.CountryId[this]; }
            set { Fields.CountryId[this] = value; }
        }
        [DefaultValue("United States of America")]
        [DisplayName("Country"), Expression("jCountry.[Name]")]
        public String CountryName
        {
            get { return Fields.CountryName[this]; }
            set { Fields.CountryName[this] = value; }
        }

        [DefaultValue("USA")]
        [DisplayName("ISO"), Expression("jCountry.[ISO3Code]"), LookupInclude]
        public String CountryISO3Code
        {
            get { return Fields.CountryISO3Code[this]; }
            set { Fields.CountryISO3Code[this] = value; }
        }

        [DisplayName("M49"), Expression("jCountry.[M49]")]
        public String CountryM49
        {
            get { return Fields.CountryM49[this]; }
            set { Fields.CountryM49[this] = value; }
        }

        #endregion
```

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

I don't really understand your problem :-)

It is always good to store information only once (fully normalized) - e.g. the ISO code should be stored only in the ISO code table and then referenced from your customers table via IsoCodeId.

What is the problem of having the country code within your customers table stored as IsoCodeId instead of the 3 chars?

Existing Database which you are not allowed to modify? :-)

----

If that is the case, I do it like this:

1) Create a notmapped (in-memory) field (e.g. CountryHelper) within customerRow.cs and add there the lookupEditor for the LookupScript form IsoCodeRow.cs. This field I show on the customersForm.cs only. The original Country code field I hide on the form (but it must still be on the form).

2) Within customersDialog.ts - In the Onchange-Event of the CountryHelper form field, I do a lookup query based on the ID from the the current value of the countryHelper field and get the Iso string value for the selected ID - and then set this value on the hidden "real" country field.

Then you don't have to change anything in the beforeSave methods on the server-side and there is no hack neccessary. Clean, pure workflow :-)

Hope this helps.

Reagards,

John

With that,

**Comment by stixoffire** [comment]
@JohnRanger I know it is not standard normalization -storage is cheap ; the user can not enter the wrong information as the drop down selects the country and they simply save and I handle placing the 3 letter code - I do this with states as well - however what I have there is Identity Column and my State Abbreviation is the PrimaryKey (not a normal configuration.  So for now I have changed my Country Table to be the same where ISO3Code is PrimaryKey - but I would have preferred another way - just to keep the table configuration straightforward  where my Identity column is also primary key. The two tables are static enumerations - for the purpose of ensuring that the user enters valid values. They pick the drop down and I assign the value in the table that references it.

**Comment by volkanceylan** [comment]
You may try a custom lookup if another field needs to be the ID in a lookup editor
