### ISSUE TITLE
JsonServiceClient error 400

### ISSUE THREAD

**Issue by PanChenhao** [volkanceylan/Serenity#4813]
Hello,

When i try to use below code to call a Serenity Application Service, it comes out error information '远程服务器返回错误: (400) 错误的请求 Error returned by remote server: (400) incorrect request'
Anyone could help me? thanks very much.
```
private void button1_Click(object sender, EventArgs e)
        {

            var client = new JsonServiceClient("http://localhost:55556/");
            client.Post<ServiceResponse>("Account/Login",
                new LoginRequest
                {
                    Username = "admin",
                    Password = "serenity"
                });

            var list = client.Post<ListResponse<Dictionary<string, object>>>(
                "Services/Northwind/Customer/List",
                new ListRequest
                {
                    Take = 100
                });
        }

```

For the class LoginRequest is created by myself. others are using from Serenity.

```
using Serenity.Services;

namespace CallSerenityWebService
{
    public class LoginRequest : ServiceRequest
    {

        public string Username { get; set; }

        public string Password { get; set; }

        public string TwoFactorGuid { get; set; }

        public int? TwoFactorCode { get; set; }
    }
}
```

**Comment by PanChenhao** [comment]
For the  LoginRequest is created by myself. for others are using from Serenity.
`using Serenity.Services;

namespace CallSerenityWebService
{
    public class LoginRequest : ServiceRequest
    {

        public string Username { get; set; }

        public string Password { get; set; }

        public string TwoFactorGuid { get; set; }

        public int? TwoFactorCode { get; set; }
    }
}`

**Comment by YoselYohan** [comment]
Calling "Account/Login" will invoke the method "Login(LoginRequest request)" in AccountPage.cs.
Are you using the core version? Antiforgery is being added at startup...

 You might be encountering an issue with the antiforgery token. If you add a decorator ( [HttpPost, JsonFilter,**IgnoreAntiforgeryToken**])to the login method, are you able to login?. 

`  [HttpPost, JsonFilter,**IgnoreAntiforgeryToken**]
        public Result<ServiceResponse> Login(LoginRequest request)
        {
            return this.ExecuteMethod(() =>
            {
                request.CheckNotNull();
...
`
This is only to pin point your issue. Remember that in the services you might have  attribute ServiceAuthorize...

`
namespace Serene.Northwind.Endpoints
{
    using Serenity.Data;
    using Serenity.Reporting;
    using Serenity.Services;
    using Serenity.Web;
    using System;
    using System.Data;
    using Microsoft.AspNetCore.Mvc;
    using MyRepository = Repositories.CustomerRepository;
    using MyRow = Entities.CustomerRow;

    [Route("Services/Northwind/Customer/[action]")]
    [ConnectionKey(typeof(MyRow)), ServiceAuthorize(typeof(MyRow))]
    public class CustomerController : ServiceEndpoint
    {
        [HttpPost, AuthorizeCreate(typeof(MyRow))]
      ...`
if you are having issues with antiforgery, JsonServiceClient might have to change in order to make a get first to get the token "X-CSRF-TOKEN" and send it back when trying to log in...

**Comment by PanChenhao** [comment]
@YoselYohan thanks very much. after i add IgnoreAntiforgeryToken on the EndPoint, then i runs successfully.

**Comment by PanChenhao** [comment]
@YoselYohan Could you give me an example about **get "X-CSRF-TOKEN" first and send it back?** 
thanks very much

**Comment by PanChenhao** [comment]
@YoselYohan thank for your help very much. I will close this issue.
if you could provide any example about **get "X-CSRF-TOKEN" first and send it back**, will be much more help for me. I still didn't figure it out.
