### ISSUE TITLE
[3.9.14.0] EntityGridDialog issue

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#4826]
I have installed the template of version 3.9.14.0,  i tryed the Entity GridDialog, the save buttons will be default displayed in the page.
![image](https://user-images.githubusercontent.com/16734387/72673590-a7f4a900-3aa7-11ea-89c5-60b203600a2c.png)
How to solve this issue? Should I have to upgrade to the new version 3.12.0.6?

**Comment by JohnRanger** [comment]
Hi @Nathan2020-0126 ,

as this is a premium feature (and I don't have premium) I cannot really help you - but when I look in the current demo: https://serenity.is/demo/AdvancedSamples/EntityGridDialog this problem is not there. Maybe you download the serene project again and try it one more?

With kind regards,

John

**Comment by Nathan2020-0126** [comment]
@JohnRanger, thanks for your feedback. I have downloaded another version project and the problem is not there. thanks very much.
