### ISSUE TITLE
Use Existing SQL server database

### ISSUE THREAD

**Issue by mrajalko** [volkanceylan/Serenity#483]
Is there any sample or guidelines on how this template can be used for an existing database, which do not have ID columns and specific stored procedures are used for CRUD.

**Comment by 107295472** [comment]
你把表弄到新数据库就好了，id列你用string ，identity去掉就行了

**Comment by 107295472** [comment]
Do you understand

**Comment by mrajalko** [comment]
No

 

Regards,

_________________________________________________________

Raja Majumdar

Cell: +91-9415542407

**Comment by 107295472** [comment]
id  change string

**Comment by 107295472** [comment]
Code generator    Use Existing SQL server database

**Comment by mrajalko** [comment]
What i meant was that a database with master and transaction tables which do not have identity columns as primary keys.

further there are other business logic built into stored procedures.
for example before allowing user to make an invoice the system is checking credit limit of party for which invoice is being generated.

i wanted help in finding out exact places to modify for UI related issues, Validation related issues and Business Logic related issues.

if anyone can guide me on this i would be obliged.

**Comment by 107295472** [comment]
That you are adding a column, the only label

**Comment by volkanceylan** [comment]
You can use Serenity for existing database, but it won't generate any code that will help you use your existing stored procedures. Everything is designed around dynamic SQL. But, if what you only want is for example call a stored proc on insert/update, instead of dynamically generated SQL statements, you can but you'll be on your own as I don't have a sample for it. I don't use stored procs for business rules unless there is a very strong reason to.

Anyway my guideline would be like this:

Generate code for your tables like you'd normally do. Don't need migrations, just use code generator to generate your code.

Then, replace Create, Update and Delete method contents in XYZEndpoint with your stored proc calls. These methods take an entity as request parameter and return a very simple response.

**Comment by volkanceylan** [comment]
See docs about Dapper on how to call stored procs.

**Comment by mrajalko** [comment]
Thanks a lot. i would give it a try.
