### ISSUE TITLE
Adding quickfilter to a URL?

### ISSUE THREAD

**Issue by dms2701** [volkanceylan/Serenity#4869]
I have a table with, for simplicity, "jobs" on different operating systems. I have a small dashboard, that has a pie chart for the job success rates for each operating system. The pie chart is hyper-linked, but for the life of me I can't work out how to create a hyper-link in such a way that auto-applies a filter based on the operating system chunk clicked upon.

i.e.

Windows 'chunk' of the pie chart - the hyperlink would auto-apply a quickfilter that filters the table to "Windows" only.

The Linux 'chunk' of the pie chart - the hyperlink would auto-apply a quickfilter that filters the table to "Linux" only.

Is this possible?

`<div class="box-footer no-padding">
                <ul class="nav nav-pills nav-stacked">
                    <li><a href="~/Blah/LatestJobs">Windows <span class="pull-right text-red"><i class="fa fa-windows"></i> @Model.WindowsJobs</span></a></li>
                    <li><a href="~/Blah/LatestJobs">Unix <span class="pull-right text-green"><i class="fa fa-code"></i> @Model.LinuxJobs</span></a></li>
                </ul>
            </div>`

**Comment by ga5tan** [comment]
I guess just pass ID of OS ?

**Comment by dms2701** [comment]
How exactly? I’m fairly new to this. What exactly do I add to my href on the pie chart chunks?

**Comment by JohnRanger** [comment]
Hi @dms2701 ,

as the quickfilter setting - in my understanding - in pure serenity-based projects - is not part of the url, you can't do that with out-of-the-box SF-based project.

At least not by completely modifying the xyzEndpoint.cs so that it accepts a parameter which contains the os type ID (e.g. 1 for Linux, 2 for Windows, etc).

As I have never done this myself, I cannot advice here any further - but have a look at how to pass url parameters to ASP.NET MVC controllers to get the idea.

And then you would have to extend one or more methods within your xyzEndpoint.cs to return the desired filtered list.

------------

Or - have a look at this demo: https://serenity.is/demo/BasicSamples/InitialValuesForQuickFilters.

Here the quickfilters are pre-set at page load. Create a grid view for each OS correctly filtered and link from your dashboard to it.

------------

Regards,

John

**Comment by dms2701** [comment]
> Hi @dms2701 ,
> 
> as the quickfilter setting - in my understanding - in pure serenity-based projects - is not part of the url, you can't do that with out-of-the-box SF-based project.
> 
> At least not by completely modifying the xyzEndpoint.cs so that it accepts a parameter which contains the os type ID (e.g. 1 for Linux, 2 for Windows, etc).
> 
> As I have never done this myself, I cannot advice here any further - but have a look at how to pass url parameters to ASP.NET MVC controllers to get the idea.
> 
> And then you would have to extend one or more methods within your xyzEndpoint.cs to return the desired filtered list.
> 
> Or - have a look at this demo: https://serenity.is/demo/BasicSamples/InitialValuesForQuickFilters.
> 
> Here the quickfilters are pre-set at page load. Create a grid view for each OS correctly filtered and link from your dashboard to it.
> 
> Regards,
> 
> John

Wouldn't each grid then need it's own independent Index.html page? How would I achieve this?

**Comment by volkanceylan** [comment]
Add a parameter in Page.cs to your action, pass it to your grid options in index.cshtml, use the parameter in your Grid.ts, this way just one of each.

**Comment by dms2701** [comment]
Thanks @volkanceylan Do you by chance have any example?
