### ISSUE TITLE
How to implement crystal report in serenity project?

### ISSUE THREAD

**Issue by nazrulbspi5** [volkanceylan/Serenity#4878]
Hello,
I need to integrate crystal reports into the serenity project. how to implement crystal reports in my project. anyone, please suggestions me.

thanks.

**Comment by brunobola** [comment]
You can do it like in regular MVC projects.

**Comment by stixoffire** [comment]
@nazrulbspi5  Download the Crystal Report Development libraries from SAP website and add them as a reference to your page - they have .NET and Java libraries ..

You then simply get your data rows from Serenity - and plop the data to your Crystal Reports .. and depending on how you want your report to come out. 
I did this a while back with SQL Reports (basically same thing) - the code was more prof of concept and worked - not well structured - but it worked .. if you want a sample of what I had I am willing to send it - code is not the best ..I did it about 4 years ago so can't remember everything.  
Crystal Reports is probably easier - you can simply put a Viewer in your Web page pull the data in and bind to the viewer  - bear in mind there are some issues that can crop up - and it does not support too many functions .

**Comment by nazrulbspi5** [comment]
When I implement the crystal report in my project. I get this error.
![Screenshot_2](https://user-images.githubusercontent.com/25577964/75655068-44a38c80-5c8b-11ea-9bfd-0d0894e4ff09.png)

**Comment by brunobola** [comment]
TIP 1. https://www.c-sharpcorner.com/article/use-crystal-report-in-mvc-net/
TIP 2. https://answers.sap.com/questions/9183832/asp-net--iis--crystal-reports--load-report-failed.html

Please try not to put unrelated serenity questions here.
Always try search for yourself before.

Thanks,

**Comment by stixoffire** [comment]
@nazrulbspi5 Your report file contains a database link in it already .. - did you fill the dataset with the info first .. Supply more code .. I know CR is not really straightforward as it sounds because some parameters you can not just override - so it becomes necessary to fill the dataset on your own and I am not sure if setdatasource works the way you think. I think there is an option for simply datasource - use it instead ..
I currently do not have my code but if I get some time I will have a look .
