### ISSUE TITLE
CommaSeperated with Multiple

### ISSUE THREAD

**Issue by vinaysalian** [volkanceylan/Serenity#4892]
I am getting the following error when using lookup editor with multiple =true   during save .Trying to save as integer in Databse .

![Capture](https://user-images.githubusercontent.com/18326019/76138987-2c0fe980-6072-11ea-8768-2397af8bd23a.PNG)

has anyone found the resolution for issue mentioned in 
CommaSeperated with Multiple = True   Issue = #1267

**Comment by JohnRanger** [comment]
Hi @vinaysalian ,

according to my understanding, this works only if you have a string field as the destination of such a "multiple" value field because the field needs to be able to store something like this: "12,78,34". This cannot be stored within an integer field and therefore cannot not be de-serialized correctly.

With kind regards,

John

**Comment by vinaysalian** [comment]
ok thanks
