### ISSUE TITLE
Image Disappearing after sometime

### ISSUE THREAD

**Issue by Shraddha996** [volkanceylan/Serenity#4897]
hello everyone
I have a module called student where I upload the image using ImageUploadEditor.
and using inlineimagesongrid I display it on my grid but after some time all images get disappear
![schoolERP1](https://user-images.githubusercontent.com/39983941/76289250-b18fd580-62ce-11ea-8c75-410547fbf88e.PNG)

PlEASE HELP!

**Comment by minhhungit** [comment]
then your path was wrong, f12 and check

**Comment by stixoffire** [comment]
This sounds like a cacheing issue .. is there a time out for your data to be cleared ?

**Comment by Shraddha996** [comment]
@minhhungit and @stixoffire 
Thanks for the quick replay!
 After f12 I got to know that the file name is not in that folder it gets deleted from the folder
I am using path \App_Data\upload\temporary for storing the images
I don't know why files get deleted from that folder

**Comment by JohnRanger** [comment]
@Shraddha996 ,

how long is "after sometime"? 

Because the store is - as its name says - only temporarily in my understanding. 

You have to process your temporarily uploaded files in the before- or aftersave methods on the server-side and store them (e.g. file copy them or import them as binary blobs into the DB) to where you really want them for permanent storage. That's what I do with such uploaded files.

With kind regards,

John

**Comment by JohnRanger** [comment]
@Shraddha996 ,

I normally change the server-side (beforeSave method in xyzRepository.cs) to get the uploaded files in-memory and then store the in-memory stream as binary blob within a [binary] field within my database - like this:

```cs
// *** Load the file from the temp location into memory ***
var JRXMLfilePath = Row.LayoutTempUploadFileName;

// *** Only do this if there is a path stored in the in-memory tempupload file name field *** 
if (Row.LayoutTempUploadFileName != null)
{

	// *** check if temp file still exists ***
	if (!File.Exists(JRXMLfilePath))
	{
		throw new Exception(String.Format(LocalText.Get("Dialogs.JRXMLFile.NotFound.Anymore"), JRXMLfilePath));
	}

	// Load the content of the file into memory ***
	byte[] jrxmlContent = File.ReadAllText(JRXMLfilePath);

	// *** Fill DB binary field with file content ***
	Row.ChainLayoutJrxml = jrxmlContent;

}
```


With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger What kind of field do you use in storing into the database - I thought I saw a StreamField and was wondering if I could bypass the temporary file creation and simply upload directly .

I know people use a variety of methods for storage , Image, blob, nvarchar(max) etc..

So I am wondering what type you use for the XYZ row, and the database. Also if you allow those images to be displayed - how are you accomplishing that task to display them in your form and or upload them ?

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

I use binary field type (varbinary I think is the type - have not a SQL db at hand at the moment to check). StreamField (if I understand this type of Field correctly - I never have used that so far) is like a passthrough solution which in fact then puts the file onto the file system of the SQL server and just keeps a reference to the file within the DB itself. This is surely nice if you plan to store large files within the database. This will keep the real DB file small but you can access the data within the streamed files via standard SQL commands.

In my case the files are not bitmaps but different kind of jasper report layouts which cannot be rendered as a graphical preview in my situation.

I just quickly googled how to retrieve the image data from the DB and then render it on the web page (the ASP.NET MVC way). This came closest to what I would try if I had to render image data from DB on an SF web site: [https://stackoverflow.com/questions/43566174/retrieve-image-from-database-using-microsoft-asp-net-mvc](url)

MVC means: Model - View - Controller. But as SF does much of the rendering on client-side (e.g. all the dialogs and the grid), you probably will retrieve the raw image data via service call and then you will have to decode and render it on client-side.

As I currently do not have any use for that in any of my SF projects, I cannot give you an end-to-end code sample.

But I hope this gives you the basic idea.

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger  Yes thank you for the helpful reply.

My issue really boils down to how serenity handles this since it handles a lot of things under the hood automagically - I don't want to do a lot of things that I do not have to (and prefer the serenity way makes things easy for upgrades and maintenance - there seems to be no example in serenity of how this is done from database to slickGrid / dialog. 

Typically image data can be stored in Database as NVarChar(MAX) , VarBinary(Max) , or  Image - not just a reference to the file. Given StreamField - I am not sure what db type would match (or if its purpose is for unmapped file path)- I know ImageField exists but I am not sure about its use case nor do I have any examples of it - I created a temporary test and database Image Data Type  comes back to serenity as StreamField and no mechanism for upload image data into the field or to display that. I am thinking all of that I will need to implement myself.

The functionality and theory of it I have an understanding - just implementing I can get bogged down.


Since you had posted the info on MVC (yes I follow that) 

Below is my understanding of SF
.. I thought I would provide the following .. perhaps someone else reading will find it useful it..


Yes Serenity uses the MVC model only it is integrated differently:
A basic breakdown of how I see it ..
Row= (kind of like your Model but I guess more related to Data Access Layer - DAL ).
Page= Controller (Note it derives from Controller) - the MVC action refers to the view.
.CSHTML = View. 
ServiceEndpoint =  I think a WCF component for client to server communications/
Columns = a Model specifically for use with the SlickGrid 
Form =  for the Dialog ( I am thinking a web form implementation but not sure here).
Repository =  this follows the Repository Pattern for DAL ..

Serenity has 2 parts  Server Side code and Client Side code.
Typically the server side code will perform 2 primary functions: 
1 directly server side related code processing 
2 it will execute and spit out the code to the client html and javascript.
[The client code slickGrid, Javascript and typescript files are included in this 2nd action of sending code to the client].

When the page loads the data is retrieved (generally server side first ) sent to the client.
The client when it wants to modify that data - a request is made to the service endpoint . Create, Retrieve, Update, Delete - that service endpoint then calls the Repository method to perform the action. (A lot of this happens automagically out of the box).

So from the database on server side the data will be sent to the field on the grid / dialogue. When the client wants to modify something .. an ajax type call is made to the server endpoint.

**Comment by volkanceylan** [comment]
Issue might be that he didn't put upload editor on row but form, so upload behavior didn't execute and he had temporary files saved. Since temporary folder is cleared in intervals, he lost images.
