### ISSUE TITLE
Graceful Exit of Save Handler with out Saving or GetNextNumber

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4903]
I have a field  [PONumber Sequence] in a job table that gets incremented when a save is executed on a Vendor Order , the format is this Job-Sequence. 

If more than one user is creating a PO for this Job at the same time - the sequence thus PONumber would be duplicated and that is a bad thing. This value in table can be utilized by more than one user and must not be duplicated for any given user. While the likelihood that 2 users would generate a request for this number at the same time - I still must handle the possibility.

I thought to put a lock on the process via a Static Class , if InProcess then EXIT Save and provide message to user . In my current scenario - in the MySaveHandler overriding beforeSave() I just throw(Exception("my Error Message"); but I am not sure this is the proper way to do it.

I was also looking in BasicSamples and found SerialAutoNumberDialog with the GetNextNumber() 
I am not sure how that works but maybe it is a better approach . 

> Would someone be kind enough to help me sort this out as to which approach is best and in the first case if that is proper or a better way ?

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

why don't you make the ponumber field an autom-incremental field (like the ID field)? Then at the save event it gets automatically an absolutely unique number - assigned by the SQL server. If you need to do anything with this ponumber, you can read it already within the aftersave event.

Could that help?

With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger The po number consists of a quote number and then a sequence (QNumber-sequence)
This is in MS SQL server and I think in MSSQL the only auto increment field is the identity column.

**Comment by JohnRanger** [comment]
Hi @stixoffire ,
could you separate the quote number from the sequence within the DB?

E.G: in one filed you store the quote number part and in the other you let MSSQL generate the unique sequence number?

Or does the sequence number for every quote restart new?

Regards,

John

**Comment by JohnRanger** [comment]
@stixoffire ,

how exactly is the workflow so that your users are able to create conflicting PONumber Sequence numbers?

Are they working together on a stack of jobs (work) and there 2 people could pick the same job and would try to process it?

John

**Comment by stixoffire** [comment]
@JohnRanger 
Different departments can create an order (different orders, different vendors) , and the order is based on the project number - so project and then a sequence number - currently this is done by one individual in a spreadsheet. I was thinking maybe leaving the po number to an authorized individual to press a button to generate the number and they be the only ones to do it - but would prefer not to do it that way as I would prefer it to be automatically generated on order creation. 

The order is generated  against an existing project. In the project table I am keeping a last sequence number used. 

I might need to generate this by overriding beforeSave and end up showing it after the fact . I would prefer it to be more automatically created in the form, but I have to consider somebody walking away from the browser or closing it out and not creating.

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

some more questions:
1) How bad would it be if there are "holes" within the sequence? Business-critical or no problem?

2) How bad would it be if the sequence number is only created at save event and not displayed within create form?

3) how bad would it be if the sequence numbers of a project don't have holes in the sequence but occasionally (when the user has been not finishing the order) the timing sequence would not match the number sequence? (E.G. reusing the sequence numbers of not finished orders after 24h)

Depending on the answer for above questions, there are some solutions :-)

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger 

You have put it very succinctly for me to visualize ..  sometimes the many 'hats' I wear clutter my thoughts.

Item 1: I do not think there would be an issue to have holes in the sequence as they are P.O. numbers - but the office people (perhaps as a matter of course using excel) if a number is missing - it might have meaning like oops oh my gosh there is a po number out there somewhere...

Item 2: I think this might be the least problematic - how ever perhaps the save button doesn't cause the dialog to close (like update) and then catch the value into that dialog. 
The issue is that when people desire a po number they want it before all the details are completed.. Like people on a job site say I need to get some xyz items now from vendor x .. ok here is a number.
So that process of giving a number before the information is completely filled out - causes the biggest hurdle - which is why I want it saved and displayed quickly and in the form.

Item 3: given the coding logic and complexities of implementing this _ I might not desire this.
Other point is that we can never have a duplicate.
Given operations of people as noted in item 2 , I can see people getting numbers and later nothing matching up.  So this option I would exclude.

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

from all your answers, I would have thought that it would become item 3. This is not too difficult to implement.

I would do it like this:

1) Have a separate POnumber table, where all POnumbers are stored. This represents the current Excel spreadsheet of the business. The table should have at minimum the following fields:

- ID (auto-increment, identity, Primary Index)
- ProjectID (foreign key from Project table)
- PONumber (unique POnumber)
- Timestamp_created (this holds the point in time when this POnumber has been given out - to determine how long the order has not been completed
- isOrderCompleted (default value = false (0) - this will be set to true in the onBeforeSave method in your main method.

2) When the form opens, fetch a unique POnumber (a POnumber whose order has never been completed within the last 24h - or if there is none, generate the next in line) PO number from the server-side (via a servicecall from the client-side. When you are doing this, within the called method on server-side, you do the following:

Check, if there is a POnumber which has isOrderCompleted = false and the timestamp_created is older than current timestamp-24h.
 --> If there is, set Timestamp_created to current timestamp in UTC and return the ID of this POnumber record.
--> If there is not (else) generate a new POnumber by using the high-watermark number which you already store within your project table and you store the following in your POnumber table:

- ProjectID (from the corresponding project)
- PONumber (Your just generated - unique - POnumber)
- Timestamp_created (current timestamp in UTC)
- isOrderCompleted = false (0)

As return value of the POnumber-generate method, you return just the ID of the record.

In your main table, you store only the ID of the POnumber record but you have a lookupscript/lookupEditor relationship there, so that it displays the desired POnumber within the form. You set that field within the form to read-only, so your users cannot manipulate it. Within the grid, you display the POnumber foreign field so that the real POnumber is shown and not the ID of it.

Then in the BeforeSave Method in the xyzRepository.cs of your main module, you simply set Row.isOrderCompleted = true (1). It will be saved together with the data entered in the form in the Save() event.

With that, you have all your criterias met:

- **User has immediately a guaranteed, unique POnumber visible** when he/she generates an order and he/she cannot manipulate it.
- **No unused POnumber. POnumbers** of not completed orders are automatically reused after 24h
- **No POnumber holes**

Elegant, isn't it? :-)

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger  thank you for your answer - it is pretty nice .. I will try to implement it, although I have to say it will take me more than 30 minutes. I wear many hats - doing this coding is one of the many hats I wear . I could see if all I did was write code for web pages / or desktop apps I might be faster.  I do appreciate the time you have taken to produce this guide for me. 

I have seen your conversation about the cache (read the whole thing through) - I usually search the issues table before I do things - because many times I come across someone who has experienced the same things. 
BTW: I like your documentation in the WIKI - basic building blocks.  Everything I have seen you post has been clear and concise - not to mention very helpful for the entire community. 

Hope you are doing well and this virus thing is not causing you too much trouble or stress ..

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

thanks for your kind words. As I myself also do programming as a "side effect" of my job, I am slow to understand basic stuff like object oriented programming, DOM manipulation or Typescript. But if I then have understood something, I like to describe it as I have understood it - Which normally makes it easy for others to understand it also.  - And yes - I am doing well. Hope, you too.

If you have trouble in doing the above, tell me and I will help. But when I see your knowledge when you help out others here in the forum, I think you can do it :-)

Regards,

John
