### ISSUE TITLE
Error when clicking languages Item on main menu bar

### ISSUE THREAD

**Issue by mrhb** [volkanceylan/Serenity#4928]
this is the message:
SCRIPT ERROR! See browser console (F12) for details.
Message: Uncaught TypeError: Cannot read property 'LanguageName' of undefined

File: http://localhost:10160/Scripts/jquery-3.3.1.js?v=sOh1Wwq3GgpK6kfDtYm0fg2, Line: 3827, Column: 3

**Comment by JohnRanger** [comment]
Hi @mrhb ,
that's an old one - See fix here on: https://github.com/volkanceylan/Serenity/wiki/Fix:-Language-Selection-does-not-work-in-IE11-and-recent-Serenity-Frameworks

Regards,

John

**Comment by mrhb** [comment]
I think it's not that problem...
this error appears in this path: "http://localhost:10160/Administration/Language"

**Comment by stixoffire** [comment]
@mrhb The reason the languages table is not showing is because it is doing the same thing in release mode that it is doing in debug mode. The object to get the column field does not have a value like get From TableX.Field1 when TableX is not defined (i.e. the object is null) you can't get any column values because the columns don't exist on the 'null' object.

There are two files that you need to investigate for the error .. since you are running IE 
Place a break point in LanguageSelection.ts before and after it tries to  get the language object

Then place a break point in LanguageSelection.ts and also in LanguageGrid.ts run your project using the IE browser selection in Visual Studio ..

This way you can find out EXACTLY where the error is occurring and will be able to fix your issue.  

If it had found the table object and just did not have data you would look to declare a LookupInclude on the LanguageName property in your LanuageRow.cs (But this is not your issue according to the error you gave.)

**Comment by mrhb** [comment]
> @mrhb The reason the languages table is not showing is because it is doing the same thing in release mode that it is doing in debug mode. The object to get the column field does not have a value like get From TableX.Field1 when TableX is not defined (i.e. the object is null) you can't get any column values because the columns don't exist on the 'null' object.
> 
> There are two files that you need to investigate for the error .. since you are running IE
> Place a break point in LanguageSelection.ts before and after it tries to get the language object
> 
> Then place a break point in LanguageSelection.ts and also in LanguageGrid.ts run your project using the IE browser selection in Visual Studio ..
> 
> This way you can find out EXACTLY where the error is occurring and will be able to fix your issue.
> 
> If it had found the table object and just did not have data you would look to declare a LookupInclude on the LanguageName property in your LanuageRow.cs (But this is not your issue according to the error you gave.)

**Comment by mrhb** [comment]
> > @mrhb The reason the languages table is not showing is because it is doing the same thing in release mode that it is doing in debug mode. The object to get the column field does not have a value like get From TableX.Field1 when TableX is not defined (i.e. the object is null) you can't get any column values because the columns don't exist on the 'null' object.
> > There are two files that you need to investigate for the error .. since you are running IE
> > Place a break point in LanguageSelection.ts before and after it tries to get the language object
> > Then place a break point in LanguageSelection.ts and also in LanguageGrid.ts run your project using the IE browser selection in Visual Studio ..
> > This way you can find out EXACTLY where the error is occurring and will be able to fix your issue.
> > If it had found the table object and just did not have data you would look to declare a LookupInclude on the LanguageName property in your LanuageRow.cs (But this is not your issue according to the error you gave.)

thanks for the detailed responce... I will check it
