### ISSUE TITLE
Exam/Test Model

### ISSUE THREAD

**Issue by srinivas1910** [volkanceylan/Serenity#4932]
Hi,
does any one tried with a student exam/test model in Serenity. Can any one suggest with same.

**Comment by JohnRanger** [comment]
Hi @srinivas1910 ,

what exactly do you want to achieve? (Are you are asking for a full SF-based app which could be used as an exam app?)

If Yes - Then I think that your question is too broad - as in this forum, normally only single technical details are discussed. 

But in general - If your exam app could be implemented as a browser-based app, then it also can be done with Serenity and you will have a great framework for multi-language and client-to-server-side database access. 

But there are extremely many thing unclear from your broad question. Things like how you want to present the exam questions, should the students have a wizard-like GUI where they can proceed back and forth between questions, etc. 

I recommend that you split your vision of your exam app into smaller parts - and then ask specific technical questions for each of the parts, so we can help you find solutions for specific technical challenges. 

Otherwise this would be more of a consulting job :-)

With kind regards,

John

**Comment by srinivas1910** [comment]
Hi @JohnRanger,
Thank you for your prompt reply, Due to Corona Lock-down in India am engaged in other awareness programs.
So am not able to spend time on the above project.  Will prepare a outline of the project and let you know ASAP.

With Regards,
Srinivas
