### ISSUE TITLE
Error In Build 

### ISSUE THREAD

**Issue by Surenthiran** [volkanceylan/Serenity#4939]
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The command ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\NodeJs\node" "C:\Users\Suren\source\repos\FutureCare\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\..\tools\tsc\tsc.js" -p ./tsconfig.json" exited with code 1.	FutureCare.Web	C:\Users\Suren\source\repos\FutureCare\FutureCare\FutureCare.Web\FutureCare.Web.csproj	2031

**Comment by stixoffire** [comment]
@Surenthiran You have not provided anything on what versions of serenity you are running. (I am guessing somewhere around > 3.8; however I can tell you that this error is usually caused by an error in your code, whether c-Sharp code or your typescript code - but generally your c-sharp code has an error in it and does not allow your code to compile. Check your error window on build and you will most likely find why you get that error.
