### ISSUE TITLE
Form builder

### ISSUE THREAD

**Issue by KishanVaishnani** [volkanceylan/Serenity#4941]
I want to generate Form based on some properties defined in single class with multiple formScript dynamically, can it possible to generate dialog with several Form properties?

your help is highly appreciated, Thanks!

**Comment by JohnRanger** [comment]
Hi @KishanVaishnani ,

I suggest that you look into Serenity.Codegenerator. This is the app which creates **static** forms and dialogs out of existing SQL tables. As the browser on client-side understands javascript and HTML - and javascript can be dynamically created and executed (eval function) and HTML can be dynamically created and then attached to the existing DOM, the generic answer is yes.

But it will require a very good understanding of many things:
- Serenity framework
- jQuery (including jQuery UI Dialog)
- HTML
- javascript
- the DOM
- ASP.NET MVC

and I never have heard here in the forum that somebody already has generated a dynamic form.

Actually, the dialog is dynamically created according to the field definition in xyzForm.cs.

The question is, what you really do want to achieve. Dynamically creating a dialog which looks like a standard serenity dialog - or  just a jQuery UI dialog with completely random content.

So in order to possibly help a bit further, we need more details. Maybe you can add here a mockup on what you want to achieve.

With kind regards,

John

**Comment by KishanVaishnani** [comment]
hey @JohnRanger 

Thanks for your reliable answer,

Yes, I want create a dialog using standard serenity dialog with passing dynamic form fields

**Comment by JohnRanger** [comment]
Hi @KishanVaishnani ,

I think that it then boils down to:
1) dynamically create the xyzForm class in-memory
2) dynamically create the required client-side scripts (this is normally statically done with T4 transform - but I don't yet understand all the details. Here you will have to investigate on your own). 3) Feed the so generated client-side representation of the dynamic form class into a corresponding xyzDialog.ts.

For how to create dynamic c# classes, please have a look at this SO article: https://stackoverflow.com/questions/3862226/how-to-dynamically-create-a-class

Hope this gives you a generic idea of how to accomplish your goal.

As I so far never had to do this, I cannot really give you a step-by-step help. But again - Serenity.Codegenerator does all of this statically. Please have a look at its source code and follow its internal workflow in order to find out what exactly is done "left and right" when it generates a xyzForm.cs.

Hope this helps a bit.

With kind regards,

John

**Comment by KishanVaishnani** [comment]
@JohnRanger Thanks for the clarifications, I got nearly solution with the help of Serenity.PropertyGrid, through we can pass propertyItems[] and based on that we need to pass the xxxForm editors.

Thanks!

**Comment by reach2rv** [comment]
@KishanVaishnani can you please put some more information on how you have achieved it.

**Comment by stixoffire** [comment]
@KishanVaishnani 
This would be a nice thing to include in the WIKI if you have achieved it. 
Each one of us has different requirements at different times and it just makes things quicker for each one when there is an example provided in the wiki.

**Comment by KishanVaishnani** [comment]
@stixoffire Sure I will try to create one sample example

**Comment by kevin100702** [comment]
> @stixoffire Sure I will try to create one sample example


I have encountered this problem recently. Can you explain it in detail or provide a simple example?

**Comment by reach2rv** [comment]
Hi @KishanVaishnani

Looking forward for a sample. your support is highly appreciated. Thank you.
> @stixoffire Sure I will try to create one sample example

**Comment by Nafhaa** [comment]
@KishanVaishnani any progress on this? I'm also interested on this topic

**Comment by Nafhaa** [comment]
> Hi @KishanVaishnani
> 
> Looking forward for a sample. your support is highly appreciated. Thank you.
> 
> > @stixoffire Sure I will try to create one sample example

@stixoffire did you got chance to look on this
