### ISSUE TITLE
Details Editor Dialogue SAVE button caption

### ISSUE THREAD

**Issue by stixoffire** [volkanceylan/Serenity#4954]
I have a master details relation .  My editor and dialogue works well enough but I am having some trouble changing the text from 'Save' to 'Add to List'. 
While I can change the text ,
```
this.toolbar.findButton('save-and-close-button').text('Add to List');
```
 I no longer have my image on the button nor is the sizing quite right

![save_ Dialogue](https://user-images.githubusercontent.com/9748682/78734759-b4eaa100-790e-11ea-8860-bfb01f5b74e0.png)

How can I change the size of the button for a better fit of the text and also leave the existing image which is in the serenity css file?

I am aware that for the grid and editor I can 
`getAddCaption()  {} `

bu the dialogue does not seem to have a method to set it.

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

for me it looks like you have removed the class "save-and-close-button" from it.

So - first find where in your code the class for this button gets removed. --> Remove the removal.

Then within the afterLoadEntity event within xyzDetaildialog.ts, you can find the element and change its text with something like this (have a look at jQuery UI button):
```ts
$('.save-and-close-button').button('option', 'label', 'Add to list');
```

(I have not tested the above but should work). If not, look at the DOM with F12 when your dialog is visible and find out how to access the element where the button text resides.

Does this make sense? 

John

**Comment by stixoffire** [comment]
Greuzi John 

Yes I used F12  to inspect the element to know what to find  - this is my go-to method .. I also am forced to use IE in order to debug the typescript - so I can look at the objects I find and know if I have the object or not.

I am attempting this on a DetailsList - the dialog that Adds to the List -( so I click the Add Button  - which I changed the Caption on getaddCaption() ) and the dialog window pops open and instead of the 'Save', I want 'Add to List'  ..
(because it is not a save but only adds to the list - I am trying to make sure users do not mis-understand the function).

My problem is the only thing that is working to change that text is the upper level of the tree which results in a terrible UI  .

I tried getting just the text to replace the division with JQuery as well , trying to change just text then also the entire division and it does not work.

I have tried setting titles and hints in the getButtons() and assigning to title there  .. no dice ..

I do not know why it does not work..


```
<div class="tool-button save-and-close-button">
<div class="button-outer">
<span class="button-inner">Save</span>
</div>
</div>

```

**Comment by JohnRanger** [comment]
Hmm,

why using IE? - I do typescript debugging within chrome absolutely successfully. Can set breakpoints on nearly anything and step through anything I want with even newest SF project (full .net). 

As long as I don't have to (by business reason) - I don't use IE anymore - because debugging of typescript has been really well integrated by now into newest Visual studio 2019.

Wherever in your code you did before your text changing, try the following code:

```ts
this.toolbar.findButton('save-and-close-button').find('.button-inner').text('Add to list');
```

If you were able to change the text from "save" to "add to list" but it has changed the appearance of your button, replace your code with the above and it _must_ do the right thing. 

Otherwise there is an error within your jquery instance or so. As your html DOM which you have shared is exactly correct and the same as mine where I showed you the screenshot of.

What happens if you press F12 and manually change the text from "save" to "add to list"? Does it what you want?

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger 

I can find the button and the inner - I have the object with length 1  so I know it has it.   
I am doing this in the constructor for the dialog.
I have used Chrome - I guess they made an update .. I am now using VS2017.

I checked my console for script errors and everything seems fine - no errors. 
I can go in to the F12 inspector and change the text and that works.

It is being a real pain I have spent hours and hours trying to figure out what the issue is ...

**Comment by JohnRanger** [comment]
Hi @stixoffire ,

in the constructor is normally too early. 

I recommend VS 2019, most up-to-date version - together with newest Chrome (the new Chromium- edge does not yet work properly in my environment (call from VS does not launch the website on iis express but rather something arbitrary)).

If you do it in the constructor, then at least put it into a settimeout function and give it - as a start - 1000ms wait time and then try to use my above command to change the text. And then you can gradually reduce that time until it does not work anymore - and then you double that value and you should have something that works for the moment.

As I don't have it in mind which method to override would be the best in regard of the necessary timing, the above method is a hack - but should work fine :-)

Otherwise you will have to look into the dialog class within serenity from where you detail dialog is derived - to see what kind of methods there are. then you can put all methods within your new xyzDialog.ts and just do a super.xyz() in each of these override methods and put a breakpoint on each of these super.xyz(). Then you see in which sequence they are called. And you can choose one which is executed mostly at the end of the whole sequence so that your code is executed the most late possible. Then your chance of setting the "final word" on this save button description is very high :-)

Try this and let me know...

Regards,

John

**Comment by stixoffire** [comment]
@JohnRanger 

I accomplished this in the updateInterface method - I thought I had tried that before but I guess not.
Or it could have been something else. 

I know that there are times when typescript appears to transform that it does not always .. the response in the command window claims success but for what ever reason something is amiss.

I will close this . 
Thank you very much for all of your help .
Your one of the top people on the list here .. If I can ever be of assistance to you in anyway let me know.

**Comment by JohnRanger** [comment]
HI @stixoffire ,

thanks for the laurels :-) - but I am really not very good. I am amazed how you got the impression that I am good in SF. I don't even understand how all this server-side types from cs are so "miraculously" transported to the client-side when I do a T4 transform - and how the editors from client-side TS are created on the server-side so we can use them as "tags" within the CS classes (like xyzRow.cs or so). I just start to discover to poke around within the Serenity (not Serene) code to see how things are done behind the scene - after I finally got a sufficient understanding, how classes and inheritance do work.

The really good people here are @minhhungit , @marcobisio , @Estrusco, @dfaruque, @brunobola - I surely am missing some others - and of course the Mastermind behind SF, Volkan.

But if I can be a bit of a help by sharing my hard-learned lessons in doing SF projects, that makes joy :-)

...and thanks for your offer - I surely will hit some road blocks in some of my projects and will post them here in the forum. And if you know a solution for them, I would be glad to receive your help.

Regards,

John
