### ISSUE TITLE
Applying a lookupeditor to quick filter dropdown

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#4955]
Hi all,

is there any builtin method within SF which I could overwrite in order to dynamically change the text of each item within a quick filter dropdown?

What I would like to do is to replace the standard texts which are pulled from the NameField of the lookup table with a translation for the language of the user. Somethin like localization - but using the translation framework of SF.

**Hint:** the ChangingLookupTextEditor.ts does what I want for modifying Dropdowns within forms - but how to apply this to the quick filter select2?

**Hint2:** https://github.com/volkanceylan/Serenity/issues/4105 comes as close as possible:  - but I would like to change the behavior of an existing quick filter which is generated automatically by adding the [quickfilter] tag on the relevant field within xyzRow.cs.

Thanks for any help.

With kind regards,

John

**Comment by stixoffire** [comment]
@JohnRanger I think you might be able to use the format function of the select 2 in order to do that. 

There is an example in the wiki of formatting the output result - so this might be one route to go - it might not be the manner in which you want to approach it - as I think we all would prefer the automagically on the fly option.

**Comment by VictorTomaili** [comment]
Closed due inactivity

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
If you still need help, you can ask this on stackoverflow with our new tag.
https://stackoverflow.com/tags/serenity-platform
