### ISSUE TITLE
Is there a way to rename uploaded file using FileUploadEditor

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4964]
Hi;

I need a requirement to rename when a file is uploaded. In my xxForm there is a property name filename that user types and then I want the uploaded files to be renamed with this property. I am not going to save original. I am using FileUploadEditor.

Secondly I want to add feature to force user to only upload PDF files not other files. I wonder if such thing is possible and can I write custom editor on top of it?

Thank you

**Comment by Nathan2020-0126** [comment]
It is not possible to rename the file when uploading. See this issue  #1141

**Comment by KishanVaishnani** [comment]
@marcobisio Yes it's possible, just you need to create your own editor with base of existing. You need to required some changes. And cheers!

**Comment by ms4hafiz** [comment]
@marcobisio 
Any samples would really help. Thank you

**Comment by gfo2007** [comment]
The easiest way to do this is to create a field in your Row class. When declaring the file format, put the file name inside a pipe **| |**  so that FileUploadEditor will recognize it as a variable and pick the content you will type in the text field.

 **Example**

```
 [DisplayName("MI Number"), Column("MINumber"), Size(500), NotNull, QuickSearch(SearchType.Contains), Unique]
        public String MiNumber
        {
            get { return Fields.MiNumber[this]; }
            set { Fields.MiNumber[this] = value; }
        }
```

```

        [DisplayName("Mi File"), Column("MIFile"), Size(1000), FileUploadEditor(FilenameFormat = "020 Level plans and MIs/MI Register/Final/|LevelUgLevelName|/|MiNumber|")]
        public String MiFile
        {
            get { return Fields.MiFile[this]; }
            set { Fields.MiFile[this] = value; }
        }
```

In the code snippet, MiNumber contains the name I want the file to have. So in the FileUploadEditor, MiNumber is the last value in pipe **| |** . This will ensure that whatever I write inside MiNumber textfield becomes the file name. 

Hope this helps @ms4hafiz
