### ISSUE TITLE
build error with new serenity project

### ISSUE THREAD

**Issue by Nathan2020-0126** [volkanceylan/Serenity#4967]
I created a new poject (asp.net, the version of Serenity is 3.9.14.0), when i try to build the project,i always got below error.

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is **..\..\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\Microsoft.TypeScript.MSBuild.props.**	NIKI.Web	D:\02_工作\05_我的项目\NIKI\NIKI\NIKI.Web

**Comment by JohnRanger** [comment]
Hi @Nathan2020-0126 ,

So did you try what the error suggests? To perform a **nuget Package restore**?

See: https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore

The problem is that on your computer, not all necessary nuget packages to run the solution are installed. 

With kind regards,

John

**Comment by Nathan2020-0126** [comment]
@JohnRanger , I have try retore, but i didnot work.

After I deleted below lines in csproj file, then I can successfully build project. But I don't konw if it would cause other problems.

```
 <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\Microsoft.TypeScript.MSBuild.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\Microsoft.TypeScript.MSBuild.props'))" />
    <Error Condition="!Exists('..\..\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\Microsoft.TypeScript.MSBuild.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Microsoft.TypeScript.MSBuild.3.4.0\build\Microsoft.TypeScript.MSBuild.targets'))" />
  </Target>
```

**Comment by Nathan2020-0126** [comment]
There is an error about transfer T4 template.
Below is C# class
![图片](https://user-images.githubusercontent.com/16734387/79044621-baaaf400-7c38-11ea-828f-8fb7dbb97e9a.png)
Below is the typescript
![图片](https://user-images.githubusercontent.com/16734387/79044643-cf878780-7c38-11ea-903f-9e72f9d4d1da.png)
There is an error about cannot find namespace serenity. I  don't know if this error is related with the action that I delete some lines in csproj file.

**Comment by JohnRanger** [comment]
Hi @Nathan2020-0126 

your first statement where you say that it completes after you deleted certain error conditions which check if you have MS typescript installed, makes me think that you indead do **not** have typescript correctly installed. Please make sure that - under extensions in Visual Studio - you install a recent typescript version:

![image](https://user-images.githubusercontent.com/2699447/79047253-c46f3000-7c15-11ea-9d9a-1cdaf479e26b.png)

And please put back the error condition checks. Removing these is like taking strong pain killers when you have serious pain - instead of curing the problem :-)

Your project has to pass them - if it does not, your project (or the current setup of your computer) does indeed not meet the requirements which SF needs to successfully compile.

Some of the most important conditions are:
- current NodeJS installed 
- recent TypeScript version installed
- If your computer is behind a corporate firewall and you must use a proxy to access the internet, this often causes problems. If this is the case, try to find a way to connect your computer directly to the internet - if that is allowed by your corporate IT. If not, then you have to google for the following themes:

- NPM behind proxy
- nuget package manager behind proxy
- visual studio behind proxy

Please check the above.

With kind regards,

John

**Comment by Nathan2020-0126** [comment]
I installled TypeScript 3.8.2 for Visual Stuido, but it still didnot work.

I just created a  .Net Core version project,  I can successfully build it.

**Comment by minhhungit** [comment]
you might need to install nodejs

**Comment by minhhungit** [comment]
check more here https://serenity.is/docs/getting_started/README

**Comment by JohnRanger** [comment]
Hmm - that's strange. I just very recently have created a new (real) .NET  SF project from the visual studio template (3.9.14) and that worked without any problem.

But I have quite some problems with new .NET core projects as - at least when I do it - the generated Serene projects do lack a lot of what goes within /wwwroot/.

(Copying them over from a real .NET SF project does solve this problem though.)

**Comment by Nathan2020-0126** [comment]
@minhhungit I have installed node js, still didnot work.
@JohnRanger @minhhungit  thank for you both very much.
