### ISSUE TITLE
Is it possible enable LookupScript through user interface

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#5007]
Hi;

I have a requirement that I need to enable end user to be able to enable and disable LookupScript through user interface. I would like to know if this is possible?

Thank you

**Comment by stixoffire** [comment]
@ms4hafiz  What you can do is show or hide the lookup select2 lookup - there is a command getLookups() in your xyzGrid - use that feature to enable it (hide or show) the lookup .

I am guessing you are referring to this for a lookup search drop down rather than say a lookup row . 

If this is not what you are looking for reply back with more details ..
