### ISSUE TITLE
How to auto refresh grid every n seconds or if it has updates

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5066]
Is there any way to auto refresh grid every n seconds or refresh if it has updates?

**Comment by nareshIntelegain** [comment]
Hello, Please use below code which solve your issue. 

MyGrid.prototype.onClick = function (e, row, cell) {
                _super.prototype.onClick.call(this, e, row, cell);
                var testgrid= this;
                setTimeout(function () { testgrid.refresh(); }, 2500);
            };

**Comment by stixoffire** [comment]
@welcometoall - your key question is "If it has updates" 
Not to sound stupid but this will ..
Why are you desiring to refresh .. ? 

Now my reason for asking such a dumb question ..
Because the user updated the data and it is not appearing in the grid ..
Because another user updated the data and all other users on the page need to see the updates ...

**Comment by JohnRanger** [comment]
Hi @welcometoall ,
if you need to instantly refresh the grid to all users currently viewing this grid- when a record within the related table changes/gets added/gets deleted, you will have to use SignalR and SQLTableDependency (look both up in google).

With SQLTableDependency you get the possibility to run c# code the moment something changes within you MS SQL DB (this exists only for MS SQL - not available for MySQL or SQLlite or PostGreSQL).

And with SignalR you can establish a realtime connection between your Webserver (where your SF-App sits) and all the browsers which are currently using your SF app. And then simply trigger a testGrid.refresh() on client-side.

IF you don't have a MS SQL backend, you will have to construct your own detection method for when Records do change.

for this, I recommend to add an additional field to your table which is called TimeStampChanged - And you have to add a trigger which fires on any change and sets the current time into this new timestamp field.

And then you must have a periodically running process on your server which every few seconds (don't do it too frequently as this can bring your SQL server to its knees - maybe fastest = every 15 seconds) checks if there are records within the desired table which have a value within TimeStampChanged which carries a timestamp which is newer than the timestamp of your previous check (do a "select count(0)" or a "select count(1)"). If the count is greater than 0 then you trigger a broadcast with signalR to all connected clients to refresh their grid (this must only be the clients which currently show that grid - extra logic hast to go into the SignalR-Hub).

**Hint:** This is all higher-level stuff - and I have not yet done this because I didn't had the urge for it within my SF projects so far to have real-time refresh of the SF-grid.

**P.S:** The periodic auto-refresh solution of @nareshIntelegain is much easier to implement but can lead to unnecessary refreshs and SQL queries when nothing has changed within your table. The periodic auto-refresh therefore does not scale very well while the proposed solution via SQLTableDependency and SignalR is much more optimized and will scale much better.

Hope this gives you the basic idea.

With kind regards,

John
