### ISSUE TITLE
How to close Tab Attribute assigned on form

### ISSUE THREAD

**Issue by reach2rv** [volkanceylan/Serenity#5207]
Hi @volkanceylan , @minhhungit 

Thank you for your support!!

Can you guys suggest how I can close Tabpane and show further fields in the category or in the form instead of Tab.

I have tried till now

in Form
```C#
        [Category("TaxDetails")]
        [Tab("TAX")]
        [PurchaseTaxEditor]
        public List<Entities.PurchaseTaxRow> TaxDetails { get; set; }

        [Tab("Add")]
        [AdditionalChargesEditor]
        public List<Entities.PurchaseChargesRow>ChargesDetails { get; set; }
```
in Dialog
```JavaScript
        constructor() {
            super();
            this.form.ChargesDetails.element.append('</div>');
```
Regards,

Arvind

**Comment by reach2rv** [comment]
@volkanceylan any suggestion on this??

**Comment by JohnRanger** [comment]
Hi @reach2rv ,

I don't understand what you want to achieve. The moment you start with TABs, even your 1st (main) "form" is on a TAB.

Can you please add a mockup from what you want to achieve?

With kind regards,

John

**Comment by reach2rv** [comment]
hi @JohnRanger 

following is my form class
![tab2](https://user-images.githubusercontent.com/16520558/94339458-c8520b80-0017-11eb-9dc2-eaf2284f22bc.png)

UI tab 1 selected
![tab1](https://user-images.githubusercontent.com/16520558/94339475-e3248000-0017-11eb-9ca9-919047448ac3.png)
UI tab2
![tab3](https://user-images.githubusercontent.com/16520558/94339479-e4ee4380-0017-11eb-93ad-30e2ea806601.png)

as you can see Tab 2 has fields like Pieces Net weight etc. I want them to be outside of the tab. Having said that those fields can not be placed above the tab-pane as that will change the scope of design.

PS: shipment field is hidden in row so that wont be visible in the form.

**Comment by JohnRanger** [comment]
Hmm,

I understand now your desired outcome, but...

As I never had to design such a complex UI like you seem to do here, I am probably of no help.

Your UI is strongly different from a standard Serenity form. In standard Serenity projects, the Tabs are your top level logical separator / "field grouping possibility". With them you group the elements which have to be logically together on one form into different TABs. And from then on downwards within the form you are in this TAB structure.

But one thing which I don't understand is: If all of the fields which you currently show within your TAB 2 should be outside of TAB 2 - why at all do you put the fields in the 1st TAB into a tab? Then you would only have 1 TAB - which makes no sense. Then just leave all the fields within the main form and don't use TABs, no?

As I understand it, there is currently no builtin way within Serenity to "end" the last tab and to continue adding elements in the main form - At least I never have seen something like this in any of the issues here since many years.

@All: If someone knows a way how to do this, I would be glad to be proven wrong :-)

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi @reach2rv ,

I see that in your 1st attempt to force close the tab, you do it in the constructor. In my experience, many things are happening too early when done within the constructor.

Try to do it in one of the many different overridable methods - for example within the afterLoadEntity method as this is executed relatively late within the sequence.

And then look at your DOM with Chrome + F12 - and see where the DOM is not correct (e.g. a closing DIV too much or so later down the DOM tree - and try to programmatically "open" that closing 2nd div so that the DOM is correct again.

Just an idea...

With kidn regards,

John

**Comment by reach2rv** [comment]
> Hmm,
> 
> I understand now your desired outcome, but...
> 
> As I never had to design such a complex UI like you seem to do here, I am probably of no help.
> 
> Your UI is strongly different from a standard Serenity form. In standard Serenity projects, the Tabs are your top level logical separator / "field grouping possibility". With them you group the elements which have to be logically together on one form into different TABs. And from then on downwards within the form you are in this TAB structure.
> 
> But one thing which I don't understand is: If all of the fields which you currently show within your TAB 2 should be outside of TAB 2 - why at all do you put the fields in the 1st TAB into a tab? Then you would only have 1 TAB - which makes no sense. Then just leave all the fields within the main form and don't use TABs, no?
> 
> As I understand it, there is currently no builtin way within Serenity to "end" the last tab and to continue adding elements in the main form - At least I never have seen something like this in any of the issues here since many years.
> 
> @All: If someone knows a way how to do this, I would be glad to be proven wrong :-)
> 
> With kind regards,
> 
> John
> 

As you can see Tab1 has taxes, tab2 will have grid pertaining to additional charges. we have not added it as of now because we are awaiting a solution ( trying different methods from our end too) we can easily add the desired additional charges grid besides taxes but then user need to scroll the form ( additional charges will be used rarely). Also as both additional charges and pieces along with rest fields after it fits in tab2 per current structure the form looks messy.

**Comment by reach2rv** [comment]
> Hi @reach2rv ,
> 
> I see that in your 1st attempt to force close the tab, you do it in the constructor. In my experience, many things are happening too early when done within the constructor.
> 
> Try to do it in one of the many different overridable methods - for example within the afterLoadEntity method as this is executed relatively late within the sequence.
> 
> And then look at your DOM with Chrome + F12 - and see where the DOM is not correct (e.g. a closing DIV too much or so later down the DOM tree - and try to programmatically "open" that closing 2nd div so that the DOM is correct again.
> 
> Just an idea...
> 
> With kidn regards,
> 
> John

Will try this. Thank you for your kind support. ☺️😊

**Comment by reach2rv** [comment]
@volkanceylan your views on this will be really helpful can you please shed some light on possibilities if any?

**Comment by VictorTomaili** [comment]
@reach2rv you can check serenity.is for premium support. It's extra custom feature just only for your project. 

Extra I close this issue because we have new stackoverflow tag for community support. You can move this discussion to there. 
https://stackoverflow.com/tags/serenity-platform

Also check the issue [guidelines](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines).
