### ISSUE TITLE
Preserve Navigation bar (Hide/Show) when navigated to Other module

### ISSUE THREAD

**Issue by welcometoall** [volkanceylan/Serenity#5232]
How to preserve the navigation bar (minimized position) when navigated to other module.
![image](https://user-images.githubusercontent.com/11242099/94514278-6e7f5a80-023e-11eb-8348-7f0c2e89424d.png)

**Comment by dfaruque** [comment]
In the `Views\Shared\_Layout.cshtml` file
put `sidebar-collapse` css class in the body tag

**Comment by welcometoall** [comment]
I don't want it as default. It should be like Theme Preference.

**Comment by VictorTomaili** [comment]
Closed because it's does not meet the issue [requirements](https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines). 
If you still need help, you can ask this on stackoverflow.
https://stackoverflow.com/tags/serenity-platform

Hint: run a simple js code on cshtml file which you want to collapse navigation.

**Comment by minhhungit** [comment]
I answered this issue on stackoverflow but in case someone want to search issue on github here is code and link

https://gist.github.com/minhhungit/54367f416d589e707e42a04772a2ef63

https://stackoverflow.com/questions/64334820/preserve-navigation-bar-hide-show-when-navigated-to-other-module
