### ISSUE TITLE
Do you have plan about these concepts?

### ISSUE THREAD

**Issue by glikoz** [volkanceylan/Serenity#621]
* Material Design
* Code First Approach (Creating UI via Entities)
* Upgrade to Asp.Net 5.0
* Meeting with an another developer in İstanbul :)

**Comment by volkanceylan** [comment]
Material design is possible as long as there is an open source quality one is available. I m not a designer :(

UI is already code first, but maybe i didnt understand your idea.

I have plans to make a .NET core version, with Yeoman possibly for project template that could work on VS Code. Waiting for it to stabilize. Currently that platform is a bit blurry.

Sure :) just contact me with details.

**Comment by jsbUSMC** [comment]
I think by Code First, he means Entity Framework Code First. Which is when you make POCOs for your model and have the controllers/views scaffolded for you. You've already pretty much done something so similar with the Fluent Migrator library and how we have to create and run a migration, defining the properties of the entity, and after the migration is run we use sergen to generate the entities, repositories, controllers, views, and behavior classes for each. I think Code First in the way that Entity Framework uses it would not be good because of the structure of the Row classes. Material Design would be nice though.

**Comment by glikoz** [comment]
I could not find contact info,
I've sent message via LinkedIn.

**Comment by volkanceylan** [comment]
I don't see anything in LinkedIn
