### ISSUE TITLE
Disable Add button on Grid not remove

### ISSUE THREAD

**Issue by 4lamosky** [volkanceylan/Serenity#633]
Afterclose dialog i need to disable Add button in grid if record itemMax = 10.
```javascript
    protected override void InternalRefresh()
        {
            base.InternalRefresh();
            ....            
            if (itemMax == 10)
            {
                disable Add button
            } 
            else
            {
                enable Add button
            }
        }

**Comment by volkanceylan** [comment]
this.toolbar.FindButton("add-button").ToggleClass("disabled", true/false)

**Comment by 4lamosky** [comment]
Thanks volkan, you are the best..always

**Comment by sayuga** [comment]
I hate to bring this up again because I know it's asked much too often but I'm not seeing any update for the typescript version of removing the add-button from the grid all together. I've referenced through the questions on here and the guide. I've ended up attempting the following items in the xyzGrid.ts file but after rebuild and T4, I still have the button persisting. 

Here is what I've Tried. 

first try: 
        protected addButtonRemove() { this.toolbar.findButton('add-button').toggleClass('disabled', true)} 

second try: 
getButtons() {
            var buttons = super.getButtons();
            var MyRow = AccountingDataReportRow.Fields;

            buttons.push(FMCDashboardv3.Common.ExcelExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit(),
                service: 'Reports/AccountingDataReport/ListExcel',
                separator: true
            }));

            buttons.push(FMCDashboardv3.Common.PdfExportHelper.createToolButton({
                grid: this,
                onViewSubmit: () => this.onViewSubmit()
            }));              
            this.toolbar.findButton('add-button').toggleClass('disabled', true);
                
            return buttons;


third try:
buttons.push(({
                this.toolbar.findButton('add-button').toggleClass('disabled', true),
                onViewSubmit: () => this.onViewSubmit()               
                }));

**Comment by volkanceylan** [comment]
var buttons = super.getButtons();
buttons = super.getButtons.splice(0, 1);
return buttons;
