### ISSUE TITLE
Northwind: product localization

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#696]
Dear @volkanceylan,
I found a bug in the product dialog: if I try to set a localization value, I always get this:
![image](https://cloud.githubusercontent.com/assets/17425690/15361682/c620291a-1d12-11e6-95e1-33cf28d05093.png)

Btw I would like to know how to re-use this mechanism: I really like the implementation that "changes" the dialog with a button and I seen that the logic it's all in the EntityDialog_Localization.cs class...the best practice here is to extend (again) the entity dialog ?

Thank you very much
Bye

**Comment by volkanceylan** [comment]
Another TS conversion issue. Fixed in 2.1.8

To use this with your own entities, you simply repeat basic steps applied to ProductRow. Create a localization row like ProductLangRow that contains only localizable fields. Add a [LocalizationRow] attribute to your row, matching them. Make changes in your repository and endpoint about Localization just like in ProductRepository and ProductEndpoint. And return some languages from getLanguages method like in ProductDialog.ts.

**Comment by marcobisio** [comment]
Copy that!
Thank you very much!
Bye
