### ISSUE TITLE
AsyncLookupEditor and Cascade

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#721]
Dear @volkanceylan,
there is a way to use both the AsyncLookupEditor and the Cascade functionality?
I really like the performance of a deferred loading of the lookups, but I miss the cascade funcionality...there is a way to emulate that behaviour (like the getItems() override in the dialog I mean).

Thank you very much
Bye

**Comment by volkanceylan** [comment]
Currently i am not even sure if AsyncLookupEditor works correctly. I tried once to make everything, including dialogs etc. async, but it caused too much backward compability problems so gave up.

**Comment by marcobisio** [comment]
Copy that!
Thank you very much!
Bye

**Comment by florin-nitulescu** [comment]
@marcobisio I think the problem is the _LookupEditorBase.CascadeFrom setter_ which is calling the sync version of _UpdateItems_ method instead of checking if the widget is async. So one solution is to override the _CascadeFrom_ setter and to check for other similar issues. 

I've taken a quick fix instead and solved the issue by overriding the UpdateItems() method because it will route all the wrong calls of the sync version to the async one.

```
        protected override void UpdateItems()
        {
            if (IsAsyncWidget())
            {
                UpdateItemsAsync();
                return;
            }

            base.UpdateItems();
        }
```

**Comment by marcobisio** [comment]
Thank you very much @florin-nitulescu!
I'll try this way :-)

Bye
