### ISSUE TITLE
Regarding generation of lookup and master-detail.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#884]
This issue is moved from https://github.com/volkanceylan/Serenity/pull/878 pull request.

I would like to send a pull request regarding placing lookup editor for foreign fields during code generation. and later try to generate master with details fields.
what do you think about?

volkanceylan commented:
How do you plan to determine if a particular table has a lookup script (custom or on table)? Reflection, parsing code?

**Comment by dfaruque** [comment]
If I place lookup script during generation by checking the table references. What is wrong with that?
Or if I place lookup script on all tables then what will happen. Does it affects performance?

Let me know if it will be very difficult or not.

**Comment by volkanceylan** [comment]
Lookups might be used in tables that implement INameRow and IIdRow. I would generate [LookupScript] attribute on them and it would work. But for large tables lookups are not suitable. It might be an option per table to generate lookup or not. But, when generating code for another table, you need to load app assembly in reflection only mode, check if the table row has a [LookupScript] attribute and generate lookup editor for it only if it has. 

Otherwise, if user didn't have LookupScript attribute on that row, when you generate code for another table, it will not work, and a generated code that doesn't work is something i would like to avoid.

**Comment by volkanceylan** [comment]
Meanwhile, if you are generating code for multiple tables, and lookup table is also one of tables being generated, that will have a [LookupScript] attribute, then you don't need to go reflection way.

**Comment by dfaruque** [comment]
Thanks I will try...
