### ISSUE TITLE
MultipleFileUploadEditor with AllowNonImage = true

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#940]
Dear @volkanceylan,
I have some trouble while uploading some kind (I mean extension) of file, like .exe or .dll with the MultipleFileUploadEditor.
The same files renamed (with a custom extension like ".123" for example) are uploaded flawlessly...
I have already set the AllowNonImage property to true, but I think that my issue is not related to this setting...
This is the exception that I have:

    An exception of type 'System.ArgumentOutOfRangeException' occurred in Serenity.Web.dll but was not handled in user code

    Additional information: Specified argument was out of the range of valid values.

This is the partial stack trace:

`   at Serenity.Services.MultipleImageUploadBehavior.ParseAndValidate(String json, String key) in P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 71
   at Serenity.Services.MultipleImageUploadBehavior.OnBeforeSave(ISaveRequestHandler handler) in P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 93
   at Serenity.Services.SaveRequestHandler3.BeforeSave()......`

I don't know if it's something related to the jquery plugin, to the MultipleImageUploadBehavior or IIS itself.
Do you have any idea/hint?

Thank you very much as always
Bye

**Comment by rolembergfilho** [comment]
Hey Marco,

I didn't try with Serenity yet, but when I developed tradicional Asp.Net web form, i had this issue too.

In my case, the problem was with Windows Server Firewall, that blocked exe and dll files. And the server farm had another pc with firewall (symantec) to control all internet requisitions against iis.

so, we created a rule in both firewall. After that, all became good!

**Comment by marcobisio** [comment]
Thanks for your feedback @rolembergfilho!
Do you remember what kind of firewall rule you have implemented? I just tried to disable the firewall on my development environment, but the "issue" is still here...

**Comment by volkanceylan** [comment]
Share what JSON is submitted to server. The error you gave only occurs when a file name is used twice in upload request.

**Comment by marcobisio** [comment]
This happens with a .exe file:

![image](https://cloud.githubusercontent.com/assets/17425690/16990011/b3fb9714-4e96-11e6-90f5-05c4eabf71b4.png)

![image](https://cloud.githubusercontent.com/assets/17425690/16990027/c2433872-4e96-11e6-8a4d-40e07e14454b.png)


If I try the upload with the same renamed file (uTorrent.123 instead of uTorrent.exe) the I have the following payload:

![image](https://cloud.githubusercontent.com/assets/17425690/16990156/46c0580a-4e97-11e6-8aba-991e036a7a0f.png)

I also tried to "play" with the "requestFiltering" setting and the "fileExtensions" child (I mean in web config), but without any luck...

**Comment by volkanceylan** [comment]
It won't allow exe uploads, it's a security hole.

**Comment by rolembergfilho** [comment]
Marco,
If I remember,  the infra team did 2 steps:

1 - in firewall: they configured a specific role to deal exe and dll uploads directly to server (i don't remember exactly how..)

2 - in antivirus (symantec): the same thing.

sorry, i don't remember the exactly configurations because it's happened in 2005... 2006...


remember that your windows have windows firewall AND windows defender. In WIndows Defender, you have to access configuration pane -> real time protection and uncheck the box "activate real time protection"


another way is before the download you change extension name, eg exe to txt or something like this.

**Comment by volkanceylan** [comment]
This is not about firewall now, Serenity has such a check in UploadProcessor.cs file

**Comment by marcobisio** [comment]
Thanks guys!
I'll check the UploadProcessor.Cs file then...I know that allow exe upload may be a security hole, but I want to allow just dll and other two types...now I know where to put the screwdriver!

Thanks again
Bye
